### ISSUE TITLE
Add an animated loader to the entire website. 👀

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#101]
Add an animated loader for the website which matches the concept of the website.

**Comment by rohitsinghind** [comment]
hey, can u assign this to me

**Comment by Spyware007** [comment]
Hello @rohitsinghind  assigned to you. 🌟
I will merge if the logo matches the concept of the website. 🤩

Star the repo if you like it. 👀

**Comment by rohitsinghind** [comment]
yeah sure

**Comment by Spyware007** [comment]
@rohitsinghind  Any updates on this issue?

**Comment by Sayyidalijufri** [comment]
Hi, Can you assign this issue to me please🙂

**Comment by Sayyidalijufri** [comment]
@Spyware007 I Very sorry when i run your react its turn into an error

**Comment by Spyware007** [comment]
@Sayyidalijufri  Do you still want to work on this issue?

**Comment by Sapna127** [comment]
I want to work on this issue please assign it to me @Spyware007

**Comment by Sayyidalijufri** [comment]
@Spyware007 I am think in my npm there is a problem so when I've fix that problem I want work again (In this issue)

**Comment by Spyware007** [comment]
@Sapna127 Any updates on this issue.
