### ISSUE TITLE
Alignment of the button that takes us to top of page

### ISSUE THREAD

**Issue by linga66** [Spyware007/Animating-Buttons#1014]
### Details

The button that takes you to the top of the page is not in the correct position. I want to fix the error

Please assign me this issue @Spyware007 

### Screenshots

![Screenshot (492)](https://github.com/Spyware007/Animating-Buttons/assets/103192975/85cd344b-b5c4-4736-bf3f-e00fbf9baaf5)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
