### ISSUE TITLE
[Add] To add a new button

### ISSUE THREAD

**Issue by Explorer003** [Spyware007/Animating-Buttons#1035]
### Details

- want to add a button which will look like the screenshot provided below

### Screenshots

![Screenshot (164)](https://github.com/Spyware007/Animating-Buttons/assets/107935613/16571357-f898-4965-aad1-72e5d87bd623)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
