### ISSUE TITLE
[Add] New Order Button 

### ISSUE THREAD

**Issue by Killer2OP** [Spyware007/Animating-Buttons#1037]
### Details

**Order Button** 
It has a animation of folding and shooting out from a canon.
Assign me this under GSSoC'23

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/111378171/d2c9f7d4-e520-4328-b978-e92b68922936

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
