### ISSUE TITLE
[Add] New Donate Button

### ISSUE THREAD

**Issue by Killer2OP** [Spyware007/Animating-Buttons#1039]
### Details

**Donate button**
It has an enter amount with sending it animation.

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/111378171/eb1e11af-0523-497a-b309-d5918c345d62

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
