### ISSUE TITLE
Add dark mode styles to the download button. 🌆

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#104]
Currently the styles for download button are same in both Light and Dark mode!
Make sure to add different styles for the dark mode! ⭐

**Comment by itsmanojthapa** [comment]
Hey, can you assign this issue to me? i would love to solve this.

**Comment by Spyware007** [comment]
@itsmanojthapa Assigned to you! 🚀
Star the repo if you like it! ⭐

**Comment by itsmanojthapa** [comment]
sure

**Comment by Saloni2004** [comment]
Hey,please assign me this

**Comment by Spyware007** [comment]
Hey, @itsmanojthapa Any updates on this issue? 🤔

**Comment by itsmanojthapa** [comment]
actually i am still learning react and trying to figure out this issue
