### ISSUE TITLE
The social media icons in the footer are not aligned properly

### ISSUE THREAD

**Issue by Shreyans2004** [Spyware007/Animating-Buttons#1041]
### Details

The social media icons in the footer are aligned in the right corner where there are already two buttons present.
As seen in the screenshot I can change the icon's position so that they are not mingled with the right corner's button.

### Screenshots

Original 

![WhatsApp Image 2023-06-06 at 00 00 24](https://github.com/Spyware007/Animating-Buttons/assets/128773151/27e2af84-37f7-46f8-9523-97ba435e6086)

After updating

![WhatsApp Image 2023-06-06 at 00 04 46](https://github.com/Spyware007/Animating-Buttons/assets/128773151/aa2d9ed9-c547-4090-8334-c76a2ab42795)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
