### ISSUE TITLE
[Add] Workflow for updating dependencies

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Spyware007/Animating-Buttons#1044]
### Details

Workflow to update dependencies: This workflow will handle updating dependencies as demonstrated in the image provided.

### Screenshots

![image](https://user-images.githubusercontent.com/74038190/243422997-69ba6152-51a7-4c2e-8975-5c2af7cc0c89.png)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
