### ISSUE TITLE
[Add] Workflow to close old Issues

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Spyware007/Animating-Buttons#1046]
### Details

- I propose creating a GitHub Actions workflow to automatically close issues that have been open for `30` days.
- Please let me know if this workflow would be relevant to the project.
- I will write the workflow with proper conventions

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
@Anmol-Baranwal 
I want a few issues to be open for more than 30 days.
Can I achieve it, with your PR?

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal 
> I want a few issues to be open for more than 30 days.
> Can I achieve it, with your PR?

What we can do is, just show some form of activity in the issue, like commenting or even editing the description. That would remove it from an inactive state, and thus it will be open till 30 days from the day it is edited. 
Writing a workflow with unknown scenarios would result in complex and undesired result.

**Comment by Spyware007** [comment]
@Anmol-Baranwal Okayh Cool!

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
