### ISSUE TITLE
[Add] Add neon button

### ISSUE THREAD

**Issue by Abhinavcode13** [Spyware007/Animating-Buttons#1055]
### Details

A neon button refers to a button that replicates the appearance of a neon sign or light. It typically features bright, vibrant colors and a glowing or illuminated effect, reminiscent of the distinctive lighting commonly seen in neon signs. Neon buttons are often used to create eye-catching and visually appealing elements in user interfaces or web design.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Abhinavcode13** [comment]
@PoorviShetty please assign me this

**Comment by Spyware007** [comment]
# Please check #1346
