### ISSUE TITLE
Button hover effect using transform

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1056]
## Description

As part of our ongoing development, we aim to implement a button hover effect using the CSS `transform` property. This will enhance the visual appeal and interactivity of our buttons, providing a smooth transition and engaging user experience.

### Problem Statement

Currently, our buttons lack dynamic visual feedback when users interact with them. The absence of hover effects can make the buttons feel static and less engaging. This may impact the overall user experience and diminish the visual appeal of our interface.

### Proposed Solution

The goal of this issue is to introduce a button hover effect using the `transform` property to create an interactive and visually appealing experience. When users hover over a button, it should smoothly transition in response to the hover action, such as scaling, rotating, or changing color. This effect will provide immediate visual feedback and enhance the perceived interactivity of our buttons.

Adding a hover effect to  buttons will significantly enhance the user experience by providing a visually appealing and interactive interface.

### Screenshots

![Screenshot (799)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/71dc4424-6a99-4e05-9fd7-f374696b1281)
![Screenshot (800)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/4e351526-3e3b-4f2f-9bf5-72a6e6e0c8b2)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Nishusk** [comment]
Please assign this issue to me under GSSOC'23.

**Comment by afreen-ahmed12** [comment]
@Nishusk hey...could you please assign me this ?

**Comment by Spyware007** [comment]
# Please check #1346
