### ISSUE TITLE
[Add] <Emoji button>

### ISSUE THREAD

**Issue by MukulsinghRajpurohit** [Spyware007/Animating-Buttons#1060]
### Details

i want to add Emoji button when clicking this btn emoji move randomly onclick and event will be use.

plx assign this to me 

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by MukulsinghRajpurohit** [comment]
Hello! Thank you for assigning me this task. I have created pull request related to the issue and will it be happy if you check it for merging.

**Comment by Spyware007** [comment]
# Please check #1346
