### ISSUE TITLE
[Add] Yes & No button

### ISSUE THREAD

**Issue by khushbumaheshwarii** [Spyware007/Animating-Buttons#1061]
### Details

want to add yes and no ,when button turn of it will show cross ❌and button turn on it will show right ✔️

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by afreen-ahmed12** [comment]
hey...could you please assign me this ?
