### ISSUE TITLE
[ADD] : Magnifying button 

### ISSUE THREAD

**Issue by iamparas0** [Spyware007/Animating-Buttons#1093]
### Details

In this button type when the cursor hover the button it will magnify and some animation shows , i have past 9 months of experience in Adobe illustrator, figma and AdobeXd.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by KHADIJA-09** [comment]
@iamparas0 please assign me this problem to solve.
