### ISSUE TITLE
Added New Button 5 [ROCK THEME]

### ISSUE THREAD

**Issue by umeshsakinala** [Spyware007/Animating-Buttons#1099]
### Details

Hello!
@Spyware007
I would like to the contribute to this project, and I have Created new Button in the theme of ROCK.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/91596032/c8c5b098-13a2-42ef-ba1f-69b8465f2a46)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [X] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by MrCuber** [comment]
I have already created the pull request
Please review it
@PoorviShetty @Spyware007
