### ISSUE TITLE
[Add] <Add a 3D CSS Button with Hover Glow Effect>

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1112]
### Details

Create a new 3D CSS button component with an eye-catching hover glow effect. The button should have a visually appealing 3D design, giving it depth and dimension. When users hover over the button, it should emit a subtle glowing effect to provide feedback and enhance the interactivity.

The button should be customizable and reusable, allowing developers to easily adjust its size, color, and other properties to fit different design requirements. It should also be accessible and responsive, ensuring a seamless user experience across various devices and screen sizes.

### Screenshots

![Screenshot (812)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/f751c5da-3243-42a2-9523-b8e698d208da)
![Screenshot (816)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/6ff7f3b1-4c1d-4a1d-897f-28636d855fc8)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
