### ISSUE TITLE
Button with RIpple Effect

### ISSUE THREAD

**Issue by Mukesh751** [Spyware007/Animating-Buttons#1116]
### Details

A beautiful and colorful ripple arises whenever the button get clicked.

### Screenshots

![Screenshot (135)](https://github.com/Spyware007/Animating-Buttons/assets/91366697/43b253de-9784-403d-9155-398d41a139a9)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Mukesh751** [comment]
> # Please check #1346

Apologies for not reading this comment on time, if merging isn't possible then I'll add in the new website.
