### ISSUE TITLE
[Add] Add new animated button with icons and hover effect 

### ISSUE THREAD

**Issue by Geeta259** [Spyware007/Animating-Buttons#1123]
### Details

Add new button component with cool hover effect animation with icons inside the button .

### Screenshots

![Screenshot (341)](https://github.com/Spyware007/Animating-Buttons/assets/75520947/0f0eb3c4-0a6b-48a9-ab1e-caea0bdb4a90)

I would like to contribute on this project under GSSOC'23 by add a new button.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
