### ISSUE TITLE
[Add] YES/NO SLANTED BUTTON WITH COOL HOVER EFFECT

### ISSUE THREAD

**Issue by sabhisharma-ise** [Spyware007/Animating-Buttons#1124]
### Details

Would like to add the below button in the website :-

Screenshot below :-

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/100849696/08e545ce-79a1-4878-a6ab-a5e524585fae)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Aman13-08** [comment]
Hello ,Sabhi Sharma
I would like to work on the this Issue.
Thanks
