### ISSUE TITLE
[Add] SPARKLY SHINY TEXT BUTTON

### ISSUE THREAD

**Issue by sabhisharma-ise** [Spyware007/Animating-Buttons#1126]
### Details

Adding a sparkly shiny text button in the website!

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/100849696/872c5fbc-fa0c-44f5-8a45-ee1e6eacbe1b)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
