### ISSUE TITLE
[Add] SEND ANIMATION BUTTON

### ISSUE THREAD

**Issue by sabhisharma-ise** [Spyware007/Animating-Buttons#1129]
### Details

Adding a cool and awesome dynamic button, which on hover acts like this (in the video below) :- 

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/100849696/bace0e96-a696-4f90-8f01-7cfe2a7307de

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
