### ISSUE TITLE
[Add] POWER BUTTON WITH ANIMATED ICON

### ISSUE THREAD

**Issue by sabhisharma-ise** [Spyware007/Animating-Buttons#1131]
### Details

I would like to add a Power Button with an animated icon. Watch the below video :-

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/100849696/31347f43-c7b8-457f-8c8b-11a0f1f874d5

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
