### ISSUE TITLE
[Add] NEON GLASS BUTTON

### ISSUE THREAD

**Issue by sabhisharma-ise** [Spyware007/Animating-Buttons#1133]
### Details

Willing to add a Neon Glass Button to the website. Video below :-

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/100849696/9166f391-363b-4ae5-8a64-1f0699fc54eb

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
