### ISSUE TITLE
💡 [ADD]: ANIMATED CHECKMARK BUTTON 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [Spyware007/Animating-Buttons#1141]
### Details

- This issue is about adding animated checkmark button
- The button's checkmark will be checked with a nice animation once the user clicks the button

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/92252895/15726e2d-1b16-411b-b019-66e300de0197

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
