### ISSUE TITLE
💡 [ADD]: ANIMATED CONFIRMATION BUTTON 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [Spyware007/Animating-Buttons#1143]
### Details

- This issue is about adding  a new animated confirmation button
- The confirmation is conformed once the user clicks the button
- This button has animation for both states during hover & after it's click

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/92252895/c898b138-f2a9-457e-8c68-2f7e636536cb

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by NAYAN-KUMAR-SINGH** [comment]
I would like to work on this project. Please assign it to me

**Comment by Spyware007** [comment]
# Please check #1346
