### ISSUE TITLE
[Add] Beer Pong Button

### ISSUE THREAD

**Issue by khushbumaheshwarii** [Spyware007/Animating-Buttons#1144]
### Details

when you click on button , boll will jump and hit the cup

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by khushbumaheshwarii** [comment]
please assign me this issue

**Comment by Spyware007** [comment]
# Please check #1346
