### ISSUE TITLE
3D buttons and hovered outlined buttons

### ISSUE THREAD

**Issue by Kashish-29** [Spyware007/Animating-Buttons#1145]
### Details

I would like to enhance the user's view in this by adding the animated 3D buttons. Sir, please assign me this so that I would work for you. It will consist of child buttons each of which will get active on pressing it. It will enhance user's view for your website.
Another thing, I would like to mention is hovering outlined buttons definitely gives a different user's attention. So that could also be considered  in it.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Kashish-29** [comment]
Ok sir, I’ll be doing that. My end semester exams are going on just give me
some time. I’ll be completing this.

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
