### ISSUE TITLE
[Add] 3D SOCIAL MEDIA ICON - REAL

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1148]
### Problem:
The current set of social media icons used in the project are two-dimensional and lack depth and realism. This affects the visual appeal of the project and doesn't align with the modern design trends. We want to enhance the user experience by adding a 3D social media icon that provides a realistic and engaging visual representation.

### Solution:
The goal of this issue is to create a new 3D social media icon that can be used in the project. The icon should accurately depict a popular social media platform (e.g., Facebook, Twitter, Instagram) with a three-dimensional design that adds depth and realism. The icon should maintain consistency with the project's overall design language.

### Expected Deliverables:
- 3D model of the social media icon in the chosen format.
- Code implementation for displaying the 3D social media icon in the project.
- Documentation detailing the process, challenges, and decisions made during implementation.

### Screenshots

![Screenshot (824)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/d9aff4e5-bf5d-456c-ab92-caf1609384fb)
![Screenshot (825)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/249ea990-0b12-40ce-820d-12ee9bbcb9ca)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
