### ISSUE TITLE
[Add] <Button that changes depending on cursor's location>

### ISSUE THREAD

**Issue by anushkaMohan** [Spyware007/Animating-Buttons#1154]
### Details

Creating a location-dependent button that dynamically changes its appearance and behavior based on the position of the cursor.
This button will enhance the user interface and make it more fun to interact with.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/123250698/7e78b90f-98cb-4fa1-8de6-2bafd2565ceb)
![Screenshot 2023-06-09 102604](https://github.com/Spyware007/Animating-Buttons/assets/123250698/a856ae8f-1206-49c0-800e-4bc731006323)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
