### ISSUE TITLE
"An initiative by GDSC-DYPCOE." not seen clearly in dark mode

### ISSUE THREAD

**Issue by Shreyans2004** [Spyware007/Animating-Buttons#1161]
### Details

"An initiative by GDSC-DYPCOE." is not seen properly in the dark mode. I can resolve this issue so that it becomes more visible in the dark mode also. Can you assign this task to me?

### Screenshots

Original
![WhatsApp Image 2023-06-09 at 12 35 46](https://github.com/Spyware007/Animating-Buttons/assets/128773151/380dd0dc-0942-49fa-a4d4-0aea52139a48)

After updating
![WhatsApp Image 2023-06-09 at 12 36 10](https://github.com/Spyware007/Animating-Buttons/assets/128773151/2bb5e667-0114-4214-81af-8da6ab39193b)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
No more UI fixes as of now because I had updated the UI and it will be live on Monday!
