### ISSUE TITLE
[Add] I mproving Scroll To Top

### ISSUE THREAD

**Issue by Deepanshu0703** [Spyware007/Animating-Buttons#1162]
### Details

Scroll to top is too big for the page 

![image](https://github.com/Spyware007/Animating-Buttons/assets/114489502/b6288b21-fad3-405e-9db0-6890e6285592)

and it's color and UI is also not matching with the website and overlapping with elements.

![image](https://github.com/Spyware007/Animating-Buttons/assets/114489502/8028abd6-b608-4dd7-bd2c-3aaafdda9211)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
No more UI fixes as of now because I had updated the UI and it will be live on Monday!
