### ISSUE TITLE
[Add]3D Button with Hover Shadow Effect

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1166]
### Details

I would like to propose the addition of a 3D button component to the open source project. The button should have a 3D appearance with a subtle shadow effect that disappears on hover.

Features:
1. 3D Appearance: The button should have a visually appealing 3D design, giving it depth and making it stand out on the page.
2. Hover Shadow Effect: When the user hovers over the button, the shadow should fade out smoothly, providing visual feedback to the user.
Expected Outcome:

By adding this 3D button component with a hover shadow effect, we can enhance the visual appeal of the project and provide a more engaging user experience.

### Screenshots

![Screenshot (830)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/7dd8fcf1-8c68-498e-8844-df0bb4656d60)
![Screenshot (831)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/2b8b688c-d2a8-44cb-8150-ce162ee4af34)
![Screenshot (832)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/4bd51542-8061-4361-a917-ad44c8a286d6)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Nishusk** [comment]
Please assign this issues to me under GSSOC'23.

**Comment by Spyware007** [comment]
# Please check #1346
