### ISSUE TITLE
[Add] Buttons Description Section's Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [Spyware007/Animating-Buttons#1167]
### Details

Enhancement in the design of the buttons description section by making some design adjustments. By making some design changes, I can make this section look even better.

### Current Design
![task (1)](https://github.com/Spyware007/Animating-Buttons/assets/115794049/666bcaac-686e-4e9c-bb16-c1769155dfa7)
### Updated Designer on "Created by" Area
![task (3)](https://github.com/Spyware007/Animating-Buttons/assets/115794049/d3635dce-2459-4f8e-aebc-7350e632a87e)
### Updated Designer on Hover effect of buttons below "Created by" Area 
![task (2) (1)](https://github.com/Spyware007/Animating-Buttons/assets/115794049/3c410be2-6f0d-4ca8-9d6f-cface6d10220)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
No more UI fixes as of now because I had updated the UI and it will be live on Monday!
