### ISSUE TITLE
[Add] <new button add>

### ISSUE THREAD

**Issue by richaroy7** [Spyware007/Animating-Buttons#1169]
### Details

Added a new button

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by richaroy7** [comment]
Kindly, assign me this.

**Comment by Spyware007** [comment]
# Please check #1346
