### ISSUE TITLE
[Add] Button Change

### ISSUE THREAD

**Issue by Roshnijeewani3457** [Spyware007/Animating-Buttons#1172]
### Details

I want to add new Button.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/89697445/2031f108-7b74-42dd-8e99-3f2839557893)

https://github.com/Spyware007/Animating-Buttons/assets/89697445/ddaca5ea-5acc-44a8-b974-a1e5552503cc

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Roshnijeewani3457** [comment]
I would like to work on this issue under GSSOC'23.Please assign me this task.

**Comment by Spyware007** [comment]
# Please check #1346
