### ISSUE TITLE
[Add] A 3D Touch Button

### ISSUE THREAD

**Issue by lakhan06** [Spyware007/Animating-Buttons#1175]
### Details

Want to add a 3d touch Button 

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/119161467/aabb0f4f-a85b-45f7-8857-5cec2e5e1db2)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Souravvmishra** [comment]
@lakhan06 Can You Please Tell Me If The Issue Was Assigned To You Yet ? Go Through The Contribution Guidelines Again

**Comment by lakhan06** [comment]
> @lakhan06 Can You Please Tell Me If The Issue Was Assigned To You Yet ? Go Through The Contribution Guidelines Again

no it was not assigned
