### ISSUE TITLE
Add a contact us page in footer and update header

### ISSUE THREAD

**Issue by Bhuvanchand26** [Spyware007/Animating-Buttons#1190]
### Details

I will add the contact us feature containing phone numbers, email, and names on the footer page so we can contact them.
And also want to add contact us button on the nav 

@Spyware007 Assign me this
I can solve this

### Screenshots

![Screenshot (535)](https://github.com/Spyware007/Animating-Buttons/assets/131843589/3f7ff0de-454f-437a-baae-3da11ceadb5c)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
No more UI fixes as of now because I had updated the UI and it will be live on Monday!
