### ISSUE TITLE
Improvement of footer in dark mode 

### ISSUE THREAD

**Issue by Bhuvanchand26** [Spyware007/Animating-Buttons#1191]
### Details

If in dark mode, the content in the footer is not visible. I want to make it visible even in dark mode

@Spyware00 Assign me this
I can solve this

### Screenshots

![Screenshot (535)](https://github.com/Spyware007/Animating-Buttons/assets/131843589/91e0c88c-0446-4d48-b6a8-f79a711f99ef)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
No more UI fixes as of now because I had updated the UI and it will be live on Monday!
