### ISSUE TITLE
Adding New buttons

### ISSUE THREAD

**Issue by shruuti321** [Spyware007/Animating-Buttons#1192]
### Details

I would like to add a new button palette.
Kindly assign me this issue under gssoc'23

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by anamithrak15** [comment]
I would like to add a 3d button. Kindly assign me this issue under gssoc'23.
