### ISSUE TITLE
[Add] 3D Black and White Button Component

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1195]
### Details

I propose the addition of a new button component to our project that features a 3D black and white design. This component will provide a modern and visually striking button style that can be used in various parts of the project.

Key Features:
- 3D Design: The button will have a three-dimensional appearance, giving it depth and dimensionality.
- Black and White Style: The button will be designed in a black and white color scheme, providing a sleek and minimalist look.
- Hover Effect: When the user hovers over the button, a subtle animation or shadow effect can be applied to enhance the interactive nature of the buttons.

By adding this 3D black and white button component, we aim to introduce a visually appealing and modern button style to our project. This will enhance the overall aesthetic appeal, provide consistency across different sections, and improve the user experience by making the buttons visually engaging.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Nishusk** [comment]
Please assign this issues to me under GSSoC'23

**Comment by Spyware007** [comment]
# Please check #1346
