### ISSUE TITLE
[Add] Add 3D Button Component

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1196]
### Details

I propose the addition of a new button component to our project that features a 3D design. This component will provide an eye-catching and interactive button style that can be used throughout the project.

Key Features:
- 3D Appearance: The button will have a visually appealing 3D design, giving it depth and making it stand out on the page.
- Hover Effect: When the user hovers over the button, a subtle animation or shadow effect can be applied to enhance the interactive nature of the buttons.

By adding this 3D button component, we aim to introduce a visually appealing and interactive button style to our project. This will enhance the overall user experience, provide consistency across different sections, and make the buttons more engaging.

Please feel free to provide your feedback, suggestions, or any considerations regarding the implementation of this component. Your input will be valuable in enhancing the overall quality of our project.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Nishusk** [comment]
Please assign this issues to me under GSSoC'23.

**Comment by Spyware007** [comment]
# Please check #1346
