### ISSUE TITLE
[Add] Add 3D Button Demo & Download

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1197]
### Details

I propose the creation of a demo and download option for the 3D button component in our project. This will provide users with a visual representation of the button and the ability to download the necessary code or assets to use it in their own projects.

Key Features:
- Interactive Demo: The demo will showcase the 3D button component in action, allowing users to interact with it and experience its visual effects.
- Code Download: Users will have the option to download the HTML, CSS, and JavaScript code required to implement the 3D button component.
- Assets Download: In addition to the code, users can download any necessary assets, such as images or icons, that are used in the button component.

Expected Outcomes:
By creating a demo and download option for the 3D button component, we aim to provide users with a convenient way to visualize the button's appearance and functionality. This will empower them to incorporate the 3D button into their own projects, promoting its usage and expanding its reach.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Nishusk** [comment]
Please assign this issues to me under GSSoC'23

**Comment by Spyware007** [comment]
# Please check #1346
