### ISSUE TITLE
[Add]  Add Pure CSS3 Customizable Pressure 3D Button

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1198]
### Details

I propose the addition of a set of Pure CSS3 Customizable Pressure 3D Buttons to our project. These buttons will provide a visually appealing and interactive user interface element that can be easily customized to fit different design requirements.

Key Features:
- Pure CSS3 Implementation: The buttons will be created using only CSS3, avoiding the need for additional JavaScript or external libraries.
- Pressure Effect: The buttons will have a 3D appearance with a pressure effect, giving them depth and a tactile feel.
- Customizable Styles: Users will be able to customize the buttons' colors, sizes, gradients, shadows, and other visual properties to match their project's design.
- Responsive Design: The buttons will be responsive and adapt to different screen sizes and devices.
- Cross-browser Compatibility: The buttons will be tested and optimized for compatibility across major web browsers.

Implementation Details:
- CSS Stylesheet: Create a dedicated CSS file to define the styles and animations for the Pressure 3D Buttons.
- HTML Markup: Use HTML markup to create the button elements and apply the necessary CSS classes and attributes.
- Customization Options: Define CSS variables or classes that allow users to easily modify the button styles and effects.
- Documentation: Provide clear instructions on how to use and customize the Pressure 3D Buttons, including code examples and demos.
- Browser Testing: Ensure that the buttons are tested on different web browsers and devices to ensure compatibility and consistent rendering.

Expected Outcomes:

By adding the Pure CSS3 Customizable Pressure 3D Buttons to our project, we can enhance the user interface and provide a versatile and visually appealing element for developers to incorporate into their projects.The customizable nature of the buttons allows for flexibility in design, making them suitable for various applications and themes.

Please feel free to provide your feedback, suggestions, or any considerations regarding the implementation of the Pure CSS3 Customizable Pressure 3D Buttons. Your input will be valuable in refining the design and functionality of the buttons.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Nishusk** [comment]
Please assign this issues to me under GSSoC'23.

**Comment by Spyware007** [comment]
# Please check #1346
