### ISSUE TITLE
[Add]3D Social Media Buttons using HTML & CSS

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1199]
### Details

I propose the addition of 3D Social Media Buttons to our project, created using only HTML and CSS. These buttons will provide an attractive and interactive way for users to connect with our project's social media channels.

Key Features:
- HTML & CSS Implementation: The buttons will be implemented using only HTML markup and CSS styles, without the need for additional JavaScript or external libraries.
- 3D Design: The buttons will have a visually appealing 3D appearance, giving them depth and making them stand out on the page.
- Icon Integration: Each button will include the respective social media icon, such as Facebook, Twitter, Instagram, or any other social media platform.
- Hover Effects: The buttons will have interactive hover effects, providing visual feedback to users when they interact with the buttons.
- Responsive Design: The buttons will be responsive and adapt to different screen sizes and devices.

Implementation Details:
- HTML Markup: Use HTML markup to create the button elements and include the necessary CSS classes and attributes.
- CSS Stylesheet: Create a dedicated CSS file to define the styles, animations, and 3D effects for the Social Media Buttons.
- Icon Integration: Choose appropriate social media icons and incorporate them into the buttons using CSS techniques, such as pseudo-elements or background images.
- Hover Effects: Implement CSS transitions or animations to create engaging hover effects that enhance the user experience.
- Documentation: Provide clear instructions on how to use the 3D Social Media Buttons, including code examples and customization options.
- Browser Testing: Ensure that the buttons are tested on different web browsers and devices to ensure compatibility and consistent rendering.

Expected Outcomes:
By adding the 3D Social Media Buttons to our project, we can enhance the user interface and provide an intuitive way for users to connect with our social media channels. The use of HTML and CSS ensures simplicity and ease of integration, making it accessible for developers to incorporate the buttons into their projects.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Nishusk** [comment]
Please assing this Issues to me under GSSoC'23

**Comment by Spyware007** [comment]
# Please check #1346
