### ISSUE TITLE
Fix broken buttons 💔

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#12]
Fix any button which looks broken or needs some changes.
Align the buttons in center if not any.

**Comment by Kitashi14** [comment]
please assign this issue to me

**Comment by Spyware007** [comment]
@Kitashi14 
Check for any broken buttons and open a PR. 🌟

**Comment by sumeetk10** [comment]
hey i would like to work on this. Just want to know that i have to fix all buttons?

**Comment by Spyware007** [comment]
@sumeetk10 
Check all the buttons whether they are properly styled in both dark and light mode and all buttons are centred aligned.

**Comment by sumeetk10** [comment]
@Spyware007 got it, can you assign.

**Comment by vk20july** [comment]
sir @Spyware007 i want to work on this issue under GSSOC 23

**Comment by Spyware007** [comment]
@vk20july 
Check for any broken buttons and raise a PR.
I will assign and merge it.
All the best.

**Comment by rafiya2003** [comment]
can you please assign me this issue under GSsoc'23

**Comment by vk20july** [comment]
> @vk20july Check for any broken buttons and raise a PR. I will assign and merge it. All the best.

ok sir

**Comment by vk20july** [comment]
sir can you assign this issue to someone else @Spyware007

**Comment by rafiya2003** [comment]
I want to work on this issue under GSSOC 23
