### ISSUE TITLE
Footer text is not clearly visible in dark mode

### ISSUE THREAD

**Issue by Palakkgoyal** [Spyware007/Animating-Buttons#1204]
### Details

Footer looks good when its light mode. But when it turns to dark mode it lose its visibility. As the text color black.

### Screenshots

![Screenshot 2023-06-11 144145](https://github.com/Spyware007/Animating-Buttons/assets/116902573/0131b409-34d6-4808-b9c2-fff63b18c889)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
No more UI fixes as of now because I had updated the UI and it will be live on Monday!
