### ISSUE TITLE
[Add] Add new buttons for Register, Sign-in, Sign-out, Add Cart➡️

### ISSUE THREAD

**Issue by arcVaishali** [Spyware007/Animating-Buttons#1208]
### Details

# I want to add new buttons for-

- [x] Register
- [x] Sign-in
- [x] Sign-out
- [x] Add Cart

These buttons will look like the buttons as shown below. **@Spyware007** Kindly assign me this issue.

### Screenshots

<img width="175" alt="button-issue" src="https://github.com/Spyware007/Animating-Buttons/assets/98754461/3306585a-de3b-41fc-9daa-caf97a87f520">

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
