### ISSUE TITLE
Improve buttons Style

### ISSUE THREAD

**Issue by Ayush9951** [Spyware007/Animating-Buttons#1220]
### Details

Hi, @Spyware007, I am a contributor in gssoc'23.
I want to work on updating styles of button I've added.
please assign me this task under label gssoc'23

### Type of Contribution

- [X] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
