### ISSUE TITLE
Enhancement in the footer section

### ISSUE THREAD

**Issue by Aditi323** [Spyware007/Animating-Buttons#1222]
### Details

The scroll button is too close to the twitter icon and the footer section need to be made more attractive 
please assign this to me as a GSSOC'23 Contributor
![Screenshot (101)](https://github.com/Spyware007/Animating-Buttons/assets/114893448/6345ca13-b32d-4cab-8598-4436528b426a)

### Type of Contribution

- [X] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
No more UI fixes as of now because I had updated the UI and it will be live on Monday!
