### ISSUE TITLE
ISSUE: Repetition of Buttons

### ISSUE THREAD

**Issue by DivyanshiNarang** [Spyware007/Animating-Buttons#1226]
The following buttons are repeated.
https://github.com/Spyware007/Animating-Buttons/assets/74779601/75486a1e-78eb-4b34-a775-d2747e72adc1

We can improve user experience by removing the same buttons.

*Please assign this issue to me under GSSoC'23*
@Spyware007

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by DivyanshiNarang** [comment]
Hello, @Spyware007 there were some repeated buttons. I just removed those.

https://github.com/Spyware007/Animating-Buttons/assets/74779601/32dfb3ed-6b32-45f7-9771-d1534fdc7578

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
