### ISSUE TITLE
[Add]: "Buy Me Coffee" Section Is Not Proper Visible

### ISSUE THREAD

**Issue by NarendraKoya999** [Spyware007/Animating-Buttons#1227]
## [Issue Description]: Buy Me Coffee Section is Not Proper Visible 
- When Click on Buy Me Coffee Icon, then It's not shows Full Image Design Card.

### This Problem OR Issue Solve in 2 Ways

Scenario 1:
- Remove The `Too Much Margin-Bottom OR Margin-Top` of This Link given in Bottom of The Coffee Design Card.

Scenario 2:
- Add` Scroll Bar Feature `On Buy Me Coffee Design Card.
   

### Scenario 1:(SCREENSHOTS)

**Screenshot-1**
<img width="960" alt="animating button-1" src="https://github.com/Spyware007/Animating-Buttons/assets/84512164/8020c0c1-8cfc-49b5-a45d-d9e942d97c0a">

**Screenshot-2**
<img width="333" alt="animating buttons-2" src="https://github.com/Spyware007/Animating-Buttons/assets/84512164/cf1bae50-4937-40ed-9a24-2b7271c6fbf7">

### Scenario 2:(SCREENSHOT)

- **Add Scroll Bar Feature On Above Buy Me Coffee Design Card.**

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
No more UI fixes as of now because I had updated the UI and it will be live on Monday!
