### ISSUE TITLE
[Add] <Create a unique subscribe button with exquisite animations>

### ISSUE THREAD

**Issue by karthiknadar1204** [Spyware007/Animating-Buttons#1230]
### Details

Create a unique subscribe button with exquisite animations

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by karthiknadar1204** [comment]
yes

**Comment by karthiknadar1204** [comment]
Pushing the button now
