### ISSUE TITLE
Add a new add button

### ISSUE THREAD

**Issue by Shreyans2004** [Spyware007/Animating-Buttons#1242]
### Details

I want to add a  add button.

### Screenshots

![WhatsApp Image 2023-06-14 at 17 29 45](https://github.com/Spyware007/Animating-Buttons/assets/128773151/cc6deed2-45a8-4e20-9d15-04b8d5d47b52)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
