### ISSUE TITLE
[Add] 3D Rotating Button using CSS

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1245]
### Details

I would like to contribute to the open-source project by implementing a 3D rotating button using CSS. The goal is to create an interactive button that rotates on the z-axis when hovered over by the user. This will add a visually appealing and engaging element to the user interface.

To achieve this, the button should have the following characteristics:
- When the mouse cursor hovers over the button, it should smoothly rotate 360 degrees on the z-axis.
- The rotation animation should be visually smooth and seamless, creating a polished user experience.
- The button's size, color, and other visual properties can be customizable through CSS classes or inline styles.
- The rotation effect should respond to user input and smoothly transition between the initial and hover states.

Expected Outcome:
The implemented 3D rotating button should provide a visually appealing and interactive user experience. Users should be able to hover over the button and witness the smooth rotation effect on the z-axis. The animation should enhance the overall design aesthetics and engagement of the user interface.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
