### ISSUE TITLE
[Important] Re-direct user_1 to their correct github account

### ISSUE THREAD

**Issue by sabhisharma-ise** [Spyware007/Animating-Buttons#1246]
### Details

If a contributor creates more than one button, then according to the repository, he/she have to create new folder in public/Buttons like user_1, user_2 etc.

This creates a problem as seen in the below attached video:
If a visitor wants to go the github of a contributor (who has contributed multiple buttons), the user_1 or user_2 is not re-directing to the correct user github and maybe give 404 error (or re-direct to someone else's account)

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/100849696/2bad6200-e2a6-4c1c-8000-6c7e4d457e98

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
Its fixed in the new version!
