### ISSUE TITLE
[Important] Comma not added after many "usernames" in Data.js

### ISSUE THREAD

**Issue by sabhisharma-ise** [Spyware007/Animating-Buttons#1252]
### Details

After forking and trying to run the website locally, the website server is giving errors because of many "usernames" in the Data.js file not having a comma (,) after their username, which is the main reason for the errors.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/100849696/13c300b8-3d2d-46e4-943f-93b9309ba8ad)
| *Comma not added after many such usernames in Data.js* |

![image](https://github.com/Spyware007/Animating-Buttons/assets/100849696/c13895fc-1cf4-4658-9925-cba24cffc386)
| *React app not able to run due to these errors in Data.js* |

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by sabhisharma-ise** [comment]
@Souravvmishra Hey, I think this issue got solved after a contributor added commas along with their Button Addition. See this PR
https://github.com/Spyware007/Animating-Buttons/pull/1251

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
