### ISSUE TITLE
Added New Download Button: Button-6

### ISSUE THREAD

**Issue by MrCuber** [Spyware007/Animating-Buttons#1255]
### Details

Hello @Spyware007 @PoorviShetty 
I would like to the contribute to this project, and I have Created new Button-6 Download Button.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/91596032/e38342ac-81d2-4cdc-bec1-d2744bc1740f)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [X] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [ ] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
