### ISSUE TITLE
Creating a new button

### ISSUE THREAD

**Issue by Uzmakh** [Spyware007/Animating-Buttons#1261]
I want to contribute by creating a new animated button, which has a moving dotted line below it.

**Comment by Souravvmishra** [comment]
can you share some demo or idea

**Comment by Uzmakh** [comment]
It is animated dotted line,that moves to and fro.
I will share it through demo.

**Comment by Uzmakh** [comment]
Though it is a group of buttons, I will create a single button.
https://github.com/Spyware007/Animating-Buttons/assets/91914613/f34dbb54-3f8d-4b4d-b1cf-425d869147bd

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Uzmakh** [comment]
ok checked

**Comment by Uzmakh** [comment]
I must work on any other button now. Is the same button creation assigned to  @Souravvmishra?

**Comment by Uzmakh** [comment]
ok,thanks

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
