### ISSUE TITLE
[Add] <Add sea mode button>

### ISSUE THREAD

**Issue by madhurafulkar** [Spyware007/Animating-Buttons#1262]
### Details

 Sea mode button

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/120560129/72885586-0bd0-4d9a-9610-5e5f3283555f

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
