### ISSUE TITLE
[Add] 3D  flat shaped Button

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1263]
### Details

I would like to propose the addition of a new feature to the open-source project: a 3D flat-shaped button. This new button style will enhance the user interface by providing a modern and visually appealing design option.

Feature Details:
- Button Appearance: The 3D flat-shaped button will have a clean, flat surface with subtle shadows and gradients to create a sense of depth.
- Hover Effects: When users hover over the button, it will smoothly transition to a slightly raised position, giving a tactile feel and visual feedback.
- Click Interaction: Upon clicking the button, it will respond with a subtle animation or color change, indicating that the action has been triggered.
- Customization Options: The button should allow for customization of colors, sizes, and text styles to align with various design requirements.
- Accessibility: The button should be designed with accessibility in mind, ensuring it is easily distinguishable, readable, and interactable for users of all abilities.

Expected Benefits:
- Enhance User Experience: The 3D flat-shaped button will add a visually appealing element to the user interface, improving the overall user experience.
- Design Flexibility: By offering this new button style, developers will have more options to create engaging and modern interfaces for their projects.
- Contribution Opportunities: The addition of this feature can attract new contributors to the project, who are interested in UI/UX design and frontend development.

I am excited about contributing to the project by implementing this feature and would appreciate any guidance or suggestions regarding the implementation approach.

### Screenshots

![Screenshot (819)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/925f8916-5893-4a15-ac52-50b4bbd5a3e5)
![Screenshot (821)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/6fabc91f-6fec-4ab1-8b39-ab158dee66fc)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Nishusk** [comment]
Please assign this issue to me under GSSoC'23.

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
