### ISSUE TITLE
[Add] Adding a new animated button

### ISSUE THREAD

**Issue by Manudasari265** [Spyware007/Animating-Buttons#1264]
### Details

Hello @Spyware007 
I would like to propose my animated button design to your project. A simple yet minimalistic design where the flash of white covers the button when we hover to the button. 

### Screenshots
![Screenshot (224)](https://github.com/Spyware007/Animating-Buttons/assets/122810482/fe8d7422-30e7-4ca2-8fc1-1b7ff7d4df6c)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Manudasari265** [comment]
@Spyware007 Please assign me this issue under GSSoC'23

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
