### ISSUE TITLE
[Enhance] Add margin to the button boxes from both the sides

### ISSUE THREAD

**Issue by sabhisharma-ise** [Spyware007/Animating-Buttons#1266]
### Details

I would like to add good margin from both the sides so that the button boxes look good!

The current website, when opened looks like this :-

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/100849696/08d47aa0-b8b8-4eff-9a8b-92d516f57c21)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
No more UI fixes as of now because I had updated the UI and it will be live on Monday!
