### ISSUE TITLE
[Add] Animated delete button

### ISSUE THREAD

**Issue by shraddha761** [Spyware007/Animating-Buttons#1277]
### Details

I want to add an animated button 

### Screenshots

![Screenshot 2023-06-15 225314](https://github.com/Spyware007/Animating-Buttons/assets/106100728/4bcbf541-f6d8-4cab-ac9c-6054ba3ce8e0)
![Screenshot 2023-06-15 225320](https://github.com/Spyware007/Animating-Buttons/assets/106100728/f6ab9c10-a17a-45fc-a578-3b14063f9a0e)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
