### ISSUE TITLE
[Add]3D Flat-Shaped Button with Hover Effect

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1284]
### Details

The purpose of this feature is to add a visually appealing 3D flat-shaped button to the project, which will exhibit an interesting hover effect. When the button is hovered over, it will undergo a transformation to enhance its appearance and provide an engaging visual interaction. This effect aims to enhance the user experience and create an attractive button design.

By incorporating the 3D flat-shaped button with hover effect, we can add an eye-catching and interactive element to the project. Users will enjoy the visually appealing transformation and engaging experience provided by this button. Ensure to test the implementation thoroughly and consider providing customization options to suit different project requirements.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
