### ISSUE TITLE
[Add] Downloading button

### ISSUE THREAD

**Issue by shraddha761** [Spyware007/Animating-Buttons#1286]
### Details

Animated downloading button

### Screenshots

![Screenshot 2023-06-16 182640](https://github.com/Spyware007/Animating-Buttons/assets/106100728/65f5230f-e8d4-4752-89d8-111d14b22ad1)
![Screenshot 2023-06-16 182645](https://github.com/Spyware007/Animating-Buttons/assets/106100728/919d0bff-ae63-4088-869a-f2fa57a172f0)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
