### ISSUE TITLE
[Add] New Button

### ISSUE THREAD

**Issue by shraddha761** [Spyware007/Animating-Buttons#1287]
### Details

New animated button 

### Screenshots

![Screenshot 2023-06-16 183847](https://github.com/Spyware007/Animating-Buttons/assets/106100728/af5513fe-afe4-466c-85ce-c97aab4e4adc)
![Screenshot 2023-06-16 183851](https://github.com/Spyware007/Animating-Buttons/assets/106100728/25dc7e05-d146-42b5-be8e-29a74c5d6d30)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
