### ISSUE TITLE
[Add] Animated Downloading button

### ISSUE THREAD

**Issue by shraddha761** [Spyware007/Animating-Buttons#1288]
### Details

An animated downloading 

### Screenshots

![Screenshot 2023-06-16 184427](https://github.com/Spyware007/Animating-Buttons/assets/106100728/da0fbb85-f98b-493d-96b2-4b2005bf637e)
![Screenshot 2023-06-16 184432](https://github.com/Spyware007/Animating-Buttons/assets/106100728/481f4777-afe4-4730-bad2-63468cff7e14)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
