### ISSUE TITLE
[ADD] Share button with on-click menu

### ISSUE THREAD

**Issue by Jacinth-Mahanta** [Spyware007/Animating-Buttons#1291]
### Details

- A circular button is made with a share symbol in between. 
- On click, the button rotates by 360 deg, and 8 small button are displayed surrounded the share button with borders appearing around each button on hover.

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/96361743/165be6e6-aeb2-4996-bae2-9b431e9177b9

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
