### ISSUE TITLE
Adding dependabot.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [Spyware007/Animating-Buttons#1297]
*We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.*

@Spyware007 please assign me this issue under gssoc'23.

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by adity2911** [comment]
will this not lead to application malfunction?

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
