### ISSUE TITLE
[Add] Animating Button

### ISSUE THREAD

**Issue by Anshika-Jain02** [Spyware007/Animating-Buttons#1299]
### Details

*I want to add the below Button.*

@Spyware007 Please assign me this under gssoc'23.

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/104912087/5502e08a-3342-4c96-8257-9afe7b3b7093

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
