### ISSUE TITLE
new button

### ISSUE THREAD

**Issue by Sushilverma002** [Spyware007/Animating-Buttons#1300]
### Details

wan to add new button.

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/114687502/1fe80d7b-d08d-4b9e-bca9-3e2c2f1e91bd

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Sushilverma002** [comment]
okay i have created PR please merge it.

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
