### ISSUE TITLE
Improve the Footet

### ISSUE THREAD

**Issue by dheeraj1129** [Spyware007/Animating-Buttons#1302]
### Details

Improve the Footer section 
1. Contact Information
2. Navigation Menu:
3. Social Media Links:
4. Copyright Information: 
5. Back to Top Button: 
6. Additional Links:

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue
- [ ] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
No more UI fixes as of now because I had updated the UI and it will be live on Monday!
