### ISSUE TITLE
[Add] <new button>

### ISSUE THREAD

**Issue by Ashasindhu** [Spyware007/Animating-Buttons#1309]
### Details

adding a new animated button

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Ashasindhu** [comment]
sir can you please assign me this under GSSO'c'2023 and please check my pull request.
