### ISSUE TITLE
[Feat] Implementing Submit code within the website.

### ISSUE THREAD

**Issue by adity2911** [Spyware007/Animating-Buttons#1312]
### Details

For this the following set of implementation needs to be done.

- [ ]  Adding a backend server within the website that will manage the database of the users and their submitted code.
- [ ]  Adding a submit new button page to allow the users to submit their codes. 
- [ ] Adding a login functionality so that the users can login and submit their codes.

These are the three things that is needed to be taken care of.
I will start working on these as soon as this issue is submitted. Kindly assign this issue to me along with the appropriate labels.

Also it will be helpful if I get help of a designer with me for this project.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by adity2911** [comment]
@Spyware007 kindly go through this issue and let  me know what you think about my proporsal as well

**Comment by Spyware007** [comment]
Hello @adity2911 
I tried to contact you!
Can we connect on discord for this?

And regarding the issue, we are working on it, added firebase as backend!

**Comment by adity2911** [comment]
I did not see any recent messages.
