### ISSUE TITLE
[Add] Scroll to Top button

### ISSUE THREAD

**Issue by pavitrachavda97** [Spyware007/Animating-Buttons#1327]
### Details

**Problem:**
When user scroll down then there should be button to back to top of the website which is not present here so they have to scroll again to back to top.

**Solution:**
I would like to add scroll to top button so that user can went to top of website in a single click.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
It's already added in the new UI!
Closing as completed!
