### ISSUE TITLE
Certain button cards are not working  i.e no buttons displayed

### ISSUE THREAD

**Issue by shruuti321** [Spyware007/Animating-Buttons#1330]
### Details

Certain button cards are not working  i.e no buttons displayed. These are  disturbing the uniformity of the website.Therfore I would like to remove them.
Kindly assign me this issue under gssoc'23.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/114770273/43e15933-be3f-479f-b4e3-3d3a5cfddb9c)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
@shruuti321 Removing them is not an option.
The code of this button is present. Can you fix those?

**Comment by shruuti321** [comment]
In the buttons folder there is no file named samriddhi15 but it is added in the data.js that is why it is showing empty on the website. They have been added in the form of samriddhi15_1.So the simple fix is to remove samridhhi15 from data.js and similarly for some other user names.
So I would like to try this issue and fix it.
![image](https://github.com/Spyware007/Animating-Buttons/assets/114770273/d9df80c7-9c36-461b-bc7e-b65f9f487e30)

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
