### ISSUE TITLE
[Add] <Add a New Button>

### ISSUE THREAD

**Issue by zul132** [Spyware007/Animating-Buttons#1333]
### Details

I want to add a new 'Click Me' Button that changes colour and glows when you hover over it. Also the spacing between the letters increases and the button looks like it is stretched when you hover.

### Screenshots

Before hover:
![btn1_before](https://github.com/Spyware007/Animating-Buttons/assets/98112914/c290e436-aba9-48da-a792-99e9f15e0132)

After hover:
![btn2_after](https://github.com/Spyware007/Animating-Buttons/assets/98112914/f45d07f5-4d98-41dc-b619-75bd501eb551)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by zul132** [comment]
Please assign this issue to me @Spyware007

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by zul132** [comment]
Got it. Will try to add the button by today
