### ISSUE TITLE
[Add] <Add Rotating Rainbow Button>

### ISSUE THREAD

**Issue by zul132** [Spyware007/Animating-Buttons#1335]
### Details

I would like to add an animated rainbow coloured button whose colours rotate by 180 degree on hover.

### Screenshots

Before hover:
![btn2_before](https://github.com/Spyware007/Animating-Buttons/assets/98112914/94655ab3-564f-44f1-8b1f-6ae33d2bd9ef)

After hover:
![btn2_after](https://github.com/Spyware007/Animating-Buttons/assets/98112914/6483b60c-68e0-49c3-aa9b-321c0508fa33)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by zul132** [comment]
Kindly assign this issue also to me @Spyware007

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by zul132** [comment]
Okay. I will add the button before 20th July

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
