### ISSUE TITLE
Creative CSS Button with Ripple Effect

### ISSUE THREAD

**Issue by Samriddhi15** [Spyware007/Animating-Buttons#1357]
### Details

I want add a new button by using simple html and css concepts. Please assign me this issue under gssoc'23, I will complete it by 20th June.
Here is the demo video of the buttons:

https://github.com/Spyware007/Animating-Buttons/assets/106501626/d173833a-0514-4c42-bc0f-488070a542a5

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
