### ISSUE TITLE
[Add] <Candy Color Button Animation>

### ISSUE THREAD

**Issue by devasyarajguru** [Spyware007/Animating-Buttons#1372]
### Details

Add candy color button which animates on hover effect.

### Screenshots

<img width="114" alt="a" src="https://github.com/Spyware007/Animating-Buttons/assets/84851506/e56e727e-1adb-4a8a-8b32-86f2538519df">
<img width="124" alt="b" src="https://github.com/Spyware007/Animating-Buttons/assets/84851506/c9c16fc8-a62e-4f7b-bf66-ba99c1e57410">

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by devasyarajguru** [comment]
Its a level-2 task , so please add level-2 tag. Thank You!

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
