### ISSUE TITLE
[Add] Background glowing button

### ISSUE THREAD

**Issue by AdityaKumar2408** [Spyware007/Animating-Buttons#1376]
### Details

I want to add a new  "Next"  Button that changes color in background and enlighten the text when you hover over it. Also the stretching part make it look more catchy to the eyes of viewers.

### Screenshots

**Before Hover**
![WhatsApp Image 2023-06-19 at 22 37 58](https://github.com/Spyware007/Animating-Buttons/assets/110921916/f103b913-5361-4e8a-b79c-95c214d5d4a8)

**After Hover**
![Screenshot (447)](https://github.com/Spyware007/Animating-Buttons/assets/110921916/53d481bb-b99b-4eec-9779-a83854361628)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [x] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by AdityaKumar2408** [comment]
Please assign this issue to me @Spyware007

**Comment by anoopgangwar4** [comment]
sir i know about this issue please assign me.

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
