### ISSUE TITLE
[Add] <write what you want to add>

### ISSUE THREAD

**Issue by marshadkhn** [Spyware007/Animating-Buttons#1387]
### Details

Hey @Spyware007 
I want to add a button

### Screenshots

![Screenshot 2023-06-20 120150](https://github.com/Spyware007/Animating-Buttons/assets/80325579/f7b81946-57c7-45f9-82d7-59b2e780d34d)

**Branch name - marshadkhn**

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by marshadkhn** [comment]
I opened it on 20

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!

**Comment by marshadkhn** [comment]
I'll appreciate  that
