### ISSUE TITLE
Added new hover button

### ISSUE THREAD

**Issue by BhumicaPG** [Spyware007/Animating-Buttons#1391]
### Details

The button is a circular button which on hover/click is pushed and tiny blots of yellow colour seem to be coming out. it looks amazing when played. I am sure it will add value to the project. I have made the changes. Please assign me the task to add it in the repo, under GSSoC'23.

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/95531637/c7d37a26-72f4-492e-9b00-3d05c22c4285

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
