### ISSUE TITLE
[GSSoC'23] Add Readme file to display all the existing buttons 

### ISSUE THREAD

**Issue by palakag29** [Spyware007/Animating-Buttons#1394]
### Details

i want to add a readme file to display all the existing buttons so that the contributers will know which buttons have been already done. 

Will add a video preview of each button and will attach the path to that button.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [X] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by palakag29** [comment]
so what kind of contributions can i make to this pull request

**Comment by palakag29** [comment]
@Spyware007
