### ISSUE TITLE
 copyright year issue 

### ISSUE THREAD

**Issue by mandliyarajendra11** [Spyware007/Animating-Buttons#1395]
### Details

we can add new Date() method for copyright year then we dont need to update year in future it will update automatically 

### Screenshots
![copy](https://github.com/Spyware007/Animating-Buttons/assets/119125519/1faf569a-c855-4029-b2d8-078dc9d97f65)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by mandliyarajendra11** [comment]
> # Please check #1346

i did not understand , 1346 for button

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
