### ISSUE TITLE
[Add] Glow button 

### ISSUE THREAD

**Issue by srujana-16** [Spyware007/Animating-Buttons#1404]
### Details

I want to add a neon glow button. This button will glow on clicking. 

### Screenshots

![Screenshot_button](https://github.com/Spyware007/Animating-Buttons/assets/82603720/2a5ed5d0-d7a4-46e9-924f-4424c39f8efb)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
