### ISSUE TITLE
[IMPROVE]  Improve UI of Home page 

### ISSUE THREAD

**Issue by ajit1201** [Spyware007/Animating-Buttons#1410]
### Details

I want to improve the UI of the home page. I can make UI clean and reallocate social media links to other section of the page.
I will also add a different kind of transition effects and make the website more professional. 

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/91869854/6bedd723-24c4-498e-8b20-a990165e7849)

This is just a demo version add more changes to future part also 

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by ajit1201** [comment]
But my issue is regarding home page.

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
