### ISSUE TITLE
[Add] SVG Play Buttons

### ISSUE THREAD

**Issue by lakhan06** [Spyware007/Animating-Buttons#1415]
### Details

I want to add SVG play buttons in which their is some light effect

https://github.com/Spyware007/Animating-Buttons/assets/119161467/012a0a3d-e905-452d-aa0a-2fdaf1a542b4

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/119161467/d4e98d54-12b5-4046-b485-efbf1ebc37d6)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by lakhan06** [comment]
@Souravvmishra  I am writing to kindly request your attention and consideration in reviewing and assigning this issue. I would greatly appreciate it if you could allocate some time to review the issue and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly.

**Comment by Souravvmishra** [comment]
This Exact Button Exist

**Comment by lakhan06** [comment]
> This Exact Button Exist

ok  @Souravvmishra then can you please assign me my other issues #1388   #1386

**Comment by Spyware007** [comment]
# Please check #1346
