### ISSUE TITLE
[Add] Bird Entry Animation Button

### ISSUE THREAD

**Issue by lakhan06** [Spyware007/Animating-Buttons#1424]
### Details

i want to add a Bird Entry Animation Button

https://github.com/Spyware007/Animating-Buttons/assets/119161467/6ee9ae74-d533-4eeb-b114-c2bf2cdfc744

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/119161467/b1dc5f26-3b7d-4cb1-b750-db66d3f525c6)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by lakhan06** [comment]
@Souravvmishra I am writing to kindly request your attention and consideration in reviewing and assigning this issue. I would greatly appreciate it if you could allocate some time to review the issue and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly.

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by lakhan06** [comment]
@Souravvmishra please assign me this issue

**Comment by lakhan06** [comment]
@TANYA-CHAN  I am writing to kindly request your attention and consideration in reviewing and assigning this issue. I would greatly appreciate it if you could allocate some time to review the issue and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly

**Comment by adity2911** [comment]
@lakhan06 I can see you have already made a lot of issues about you wanting to add many buttons. I don't think any other buttons should be considered by you since you have been considered for a lot of buttons PR earlier also.
Kindly follow #1346

**Comment by TANYA-CHAN** [comment]
> @lakhan06 I can see you have already made a lot of issues about you wanting to add many buttons. I don't think any other buttons should be considered by you since you have been considered for a lot of buttons PR earlier also. Kindly follow #1346

I am getting a lot of mails, kindly do not rewrite comments on already written remarks, please mark/label them if required.

**Comment by TANYA-CHAN** [comment]
> > @lakhan06 I can see you have already made a lot of issues about you wanting to add many buttons. I don't think any other buttons should be considered by you since you have been considered for a lot of buttons PR earlier also. Kindly follow #1346
> 
> sorry @adity2911 @TANYA-CHAN for inconvenience occur by me . Just trying to contribute as much as i can to move up in the leaderboard. But no worries I will try to contribute in new projects . Thank you for merging all my pull request because of which my current rank in leaderboard is 16 . so thank you and again sorry for inconvenience
The reply I had sent was not for you, please keep contributing, stay motivated

**Comment by TANYA-CHAN** [comment]
> > @lakhan06 I can see you have already made a lot of issues about you wanting to add many buttons. I don't think any other buttons should be considered by you since you have been considered for a lot of buttons PR earlier also. Kindly follow #1346
> 
> sorry @adity2911 @TANYA-CHAN for inconvenience occur by me . Just trying to contribute as much as i can to move up in the leaderboard. But no worries I will try to contribute in new projects . Thank you for merging all my pull request because of which my current rank in leaderboard is 16 . so thank you and again sorry for inconvenience

The reply I had sent was not for you, please keep contributing, stay motivated
