### ISSUE TITLE
[Add] Adding a new ON&OFF Button

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1425]
## Overview
The ON and OFF button component provides a user interface element that allows users to toggle between two states: ON and OFF. It is commonly used in applications, websites, or any other interactive system where the user needs to control the state of a particular feature or functionality.

## Key Features

1. **Toggle Functionality:** The ON and OFF button allows users to switch between the ON and OFF states by clicking or tapping on the button.

2. **Visual Indication:** The button visually represents the current state, providing clear visual feedback to the user.

3. **Customizable Design:** The button component can be customized to match the overall design and theme of the application or website. This includes the button's color, size, shape, and any additional visual effects.

4. **Event Handling:** The ON and OFF button component can trigger events or callbacks when the state is changed, allowing developers to perform specific actions or update the application's state accordingly.

## Usage

To use the ON and OFF button component in your project, follow these steps:

## Conclusion

The ON and OFF button component provides an intuitive and user-friendly way for users to control the state of a feature or functionality in your application or website. By following the usage instructions and leveraging the provided API, you can easily incorporate the ON and OFF button component into your project.

### Screenshots

![Screenshot (871)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/5b9eab5c-ff3e-47c0-af33-8ecb2cb53372)
![Screenshot (872)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/0291fdbd-01c7-4721-a294-4b3568e6d68b)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Nishusk** [comment]
Please assign this issues to me under GSSoC'23.

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
