### ISSUE TITLE
[Add] MULTI-STEP GROWING LIKE BUTTON

### ISSUE THREAD

**Issue by lakhan06** [Spyware007/Animating-Buttons#1427]
### Details

I want to add a MULTI-STEP GROWING LIKE BUTTON

https://github.com/Spyware007/Animating-Buttons/assets/119161467/88b81d6f-c60b-4fa4-ad48-21e20bc84e54

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/119161467/7d82c195-3af0-4de9-9088-ab3a575c4172)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by lakhan06** [comment]
@Souravvmishra Thankyou sir for your regular support
  I am writing to kindly request your attention and consideration in reviewing and assigning this issue. I would greatly appreciate it if you could allocate some time to review the issue and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly.

**Comment by Spyware007** [comment]
# Please check #1346
