### ISSUE TITLE
[Add] POWER BUTTON WITH ANIMATED ICON

### ISSUE THREAD

**Issue by lakhan06** [Spyware007/Animating-Buttons#1429]
### Details

I want to add POWER BUTTON WITH ANIMATED ICON

https://github.com/Spyware007/Animating-Buttons/assets/119161467/045f768d-f537-427d-b229-ce89b517e523

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/119161467/4ab1765f-fc74-49d3-b9b3-0a4e95075c2b)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by lakhan06** [comment]
@Souravvmishra I am writing to kindly request your attention and consideration in reviewing and assigning this issue. I would greatly appreciate it if you could allocate some time to review the issue and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by lakhan06** [comment]
@TANYA-CHAN  Can you please assign me this issue if possible
