### ISSUE TITLE
[Add] Button Hover State Border Radius Fun

### ISSUE THREAD

**Issue by chinmayjain08** [Spyware007/Animating-Buttons#1431]
### Details

I want to add this amazing button. 
Here is the video :

https://github.com/Spyware007/Animating-Buttons/assets/92749015/457b530b-7f34-48d0-b369-993dc35d2ee0

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/92749015/5265686b-afbb-43aa-9212-dca696546714)
![image](https://github.com/Spyware007/Animating-Buttons/assets/92749015/ae307ec0-84e9-4a3a-90a1-c7f61c7b50cb)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by chinmayjain08** [comment]
I have created the issue on 20th only and also I have created the button. Even the PR is ready. Can you assign this one. After this I will be contributing to the website directly.

**Comment by adity2911** [comment]
Assigned. make sure to merge today only

**Comment by chinmayjain08** [comment]
@adity2911 I have solved this issue in PR #1536 with no merge conflicts.
