### ISSUE TITLE
[Add] CUSTOM ANIMATED CARTOON Button

### ISSUE THREAD

**Issue by lakhan06** [Spyware007/Animating-Buttons#1432]
### Details

i want to add a CUSTOM ANIMATED CARTOON Button

https://github.com/Spyware007/Animating-Buttons/assets/119161467/c406aa1b-4397-446f-8beb-ff97bbeb6c32

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/119161467/97c41162-ec70-4b7d-ac90-ef1e208118c2)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by lakhan06** [comment]
@Souravvmishra I am writing to kindly request your attention and consideration in reviewing and assigning this issue. I would greatly appreciate it if you could allocate some time to review the issue and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly.

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by lakhan06** [comment]
@TANYA-CHAN  Can you please assign this issue to me it will be very helpfull for me

**Comment by TANYA-CHAN** [comment]
> @TANYA-CHAN Can you please assign this issue to me it will be very helpfull for me

Even if you create a PR it can be only merged after a few days when the firebase conversion happens

**Comment by TANYA-CHAN** [comment]
> ok @TANYA-CHAN but thankyou for considering my request means a lot

No problem
