### ISSUE TITLE
[Add] Hover Button 

### ISSUE THREAD

**Issue by Durgesh4993** [Spyware007/Animating-Buttons#1435]
### Details

Technologies used:
HTML
CSS

![image](https://github.com/Spyware007/Animating-Buttons/assets/98798977/83967805-b16d-41ea-a26b-d93d683daeab)

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/98798977/bc871dec-bee3-430e-a71d-10f7faa07d69

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Durgesh4993** [comment]
@Souravvmishra Please assign this task to me sir

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Durgesh4993** [comment]
@Spyware007 Ok sir it's mean i can directly send the PR
