### ISSUE TITLE
Dark Mode for Footer ▓

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#145]
Add dark mode styles for footer 🚀

**Comment by bamidelee** [comment]
please assaign this to me

**Comment by Spyware007** [comment]
Okay @bamidelee  Assigned to you.

**Comment by Spyware007** [comment]
Hey @bamidelee  any updates regarding this issue and #144

**Comment by Sayyidalijufri** [comment]
Hi, Can you assign this issue to me?
