### ISSUE TITLE
[Add] Input box with search button with hovering effect

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Spyware007/Animating-Buttons#1450]
### Details

- Input box will be hidden until the search button is not pressed
- On pressing the search button will open the input box 
- Using animations to move the search button
- Adding rolling effect will attract the users
- Adding hover effect on button will create a attractive look
- Just creating this effect using CSS only

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Avdhesh-Varshney** [comment]
@Souravvmishra Sir, please assign this task to me to work on it and contribute in this repository under GSSoC'23 program
/assign

**Comment by Spyware007** [comment]
@Avdhesh-Varshney On what basis you are going to search?

**Comment by Avdhesh-Varshney** [comment]
> @Avdhesh-Varshney On what basis you are going to search?

@Spyware007 
- Adding this button on the navebar to search any item like electronic gadgets on electronic website, etc.
- Searching for a newsletter, blogs, etc.

We can add that button there which will takes little space as input box is hidden inside the search button on pressing the button inpux box will come up.

**Comment by Spyware007** [comment]
# Please check #1346
