### ISSUE TITLE
[Add] want to add modern button mostly used for (generate with ai) with sparkle icon ✨

### ISSUE THREAD

**Issue by balaji-sivasakthi** [Spyware007/Animating-Buttons#1452]
### Details

I would to like to create a generative ai button with sparkle icon for this project.

### Screenshots

![Screenshot (252)](https://github.com/Spyware007/Animating-Buttons/assets/65065614/b43f7ae2-8b7e-4ff2-bef5-cdaca5f2b512)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by balaji-sivasakthi** [comment]
ok
