### ISSUE TITLE
[ GSSOC'23 ] New Button : New Fizzy Button

### ISSUE THREAD

**Issue by md-rosh02** [Spyware007/Animating-Buttons#1459]
### Details

New interesting button😊 Download Button.. 

### Screenshots

![IMG_20230621_093035](https://github.com/Spyware007/Animating-Buttons/assets/132879891/d639d846-2fbd-4e77-94da-d8a7298286ef)
![IMG_20230621_093017](https://github.com/Spyware007/Animating-Buttons/assets/132879891/53e553ed-25e5-42c0-9171-408ff6af174b)
![IMG_20230621_092957](https://github.com/Spyware007/Animating-Buttons/assets/132879891/cad325fa-4936-40a9-bbfa-9f1558e4aa9e)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by md-rosh02** [comment]
@khushbumaheshwarii could you plz assign me this issue??

**Comment by md-rosh02** [comment]
@Souravvmishra Could you plz assign me this issue???

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
