### ISSUE TITLE
[Add] 'PLAY NOW 'BUTTON 

### ISSUE THREAD

**Issue by Dimple-Choudhary** [Spyware007/Animating-Buttons#1462]
### Details

I want to add a PLAY NOW button having a hover effect, when hovered it shows a bat. 

### Screenshots

Before:
![playnow](https://github.com/Spyware007/Animating-Buttons/assets/96401557/275a87c5-9bd2-41a2-8825-22ba7db2fd53)
 hover effect:
![playnow bat](https://github.com/Spyware007/Animating-Buttons/assets/96401557/7732a7b2-74d0-463b-baf2-438a8b9e6111)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by aditi-chaurasia** [comment]
Please assign this issue to me under GSSOC'23 . I want to work on this.

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
