### ISSUE TITLE
[Add] <Bubble click effect Button>

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Spyware007/Animating-Buttons#1465]
### Details

I will be adding a button with bubble animation when clicked

### Screenshots

[Screencast from 21-06-23 02:20:55 PM IST.webm](https://github.com/Spyware007/Animating-Buttons/assets/85278243/4459a941-966f-4c6c-9e5a-95dfcc3477be)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
