### ISSUE TITLE
Typing error in README.md 

### ISSUE THREAD

**Issue by barkhaaroraa** [Spyware007/Animating-Buttons#1470]
### Details

there's a typing error. it should've been 'Table of Contents' instead of 'Table of Content'

### Screenshots

<img width="731" alt="image" src="https://github.com/Spyware007/Animating-Buttons/assets/115429121/bb26e4d8-7f95-4de7-8a88-f9dfcd9104ae">

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [X] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Riyazul555** [comment]
Just solved the typo in the Readme file.....

**Comment by Riyazul555** [comment]
@barkhaaroraa please check it

**Comment by Riyazul555** [comment]
@Spyware007 please review it

**Comment by barkhaaroraa** [comment]
@Spyware007 but i raised the issue... shouldn't i be fixing it?
@Riyazul555 the person who first picks the issue gets to fix it and its still there.

**Comment by barkhaaroraa** [comment]
@Riyazul555 and you can't raise a pr till the issue gets assigned to you

**Comment by Riyazul555** [comment]
Ok @barkhaaroraa
