### ISSUE TITLE
[Add]  Want to add hover effects on button

### ISSUE THREAD

**Issue by HimanshuNarware** [Spyware007/Animating-Buttons#1475]
### Details

The website front page social icon button icon is missing hover effect, I want to work on this issue.

### Screenshots

![34](https://github.com/Spyware007/Animating-Buttons/assets/83147410/e5d9a806-3e42-42c5-b3a0-915d7531716e)
![33](https://github.com/Spyware007/Animating-Buttons/assets/83147410/0b5a8bd5-b077-46dc-a64e-793ef9170c40)

### Type of Contribution

- [X] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
