### ISSUE TITLE
[Bug] Share Image not visible

### ISSUE THREAD

**Issue by Avinash905** [Spyware007/Animating-Buttons#1487]
### Details

- When you share this website on any social media then no image will be visible as it lacks image url in meta tags like open graph and twitter (verified by social share preview).
- Also some meta tags like language, keywords, robots, author and many more are missing.

Adding them to your website will increase your SEO

### Screenshots

![Screenshot (517)](https://github.com/Spyware007/Animating-Buttons/assets/56786344/489d6bec-41e1-4251-9abd-560a90db20bc)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
