### ISSUE TITLE
[Enhancement] Missing proper alt attributes on img tags

### ISSUE THREAD

**Issue by Avinash905** [Spyware007/Animating-Buttons#1488]
### Details

Many people just write one or two words explaining about the image in alt attributes which is not the correct way to describe the image.
So, I would like to add proper alt attributes which describe the images.

**Benefits of enhancing the alt attributes include:**

Accessibility: Alt attributes provide essential information to individuals who cannot see the images directly, allowing them to understand the visual content through alternative text descriptions.

Compliance: By following best practices and guidelines, such as those outlined in the Web Content Accessibility Guidelines (WCAG), we can ensure our project meets accessibility standards, which is important for inclusivity and legal compliance.

SEO (Search Engine Optimization): Meaningful alt attributes can improve search engine rankings by providing search engines with more context about the images. This can result in increased visibility and organic traffic to our project.

### Screenshots

![Screenshot (518)](https://github.com/Spyware007/Animating-Buttons/assets/56786344/c73f4200-d0d3-451c-9fca-8cc971495388)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
