### ISSUE TITLE
[Improve] Optimize Performance by Adding Lazy Loading to Image Tags

### ISSUE THREAD

**Issue by Avinash905** [Spyware007/Animating-Buttons#1489]
### Details

As part of optimizing the project's performance, we need to implement lazy loading for the <img> tags used throughout the project. Lazy loading is a technique that defers the loading of images until they are about to be displayed on the user's screen, reducing the initial load time and improving the overall user experience.

To accomplish this, we need to modify the existing <img> tags and add the loading attribute with the value of "lazy". This attribute instructs the browser to delay the loading of the image until it becomes visible within the viewport.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by adity2911** [comment]
Kindly go through the codebase. I think there is already an implementation of lazy loading.

**Comment by Avinash905** [comment]
> Kindly go through the codebase. I think there is already an implementation of lazy loading.

I have checked it's only present for the pages not for images

**Comment by Avinash905** [comment]
Hey, @adity2911 what does delayed label mean?

**Comment by Avinash905** [comment]
> Kindly go through the codebase. I think there is already an implementation of lazy loading. If you think that the lazy section still needs some improvements then kindly be on hold. we are currently working on changing the website on a major scale. After that you can work on it.

Ok

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
