### ISSUE TITLE
[Add] Plum effect Button

### ISSUE THREAD

**Issue by lakhan06** [Spyware007/Animating-Buttons#1494]
### Details

I want to add a plum effect button

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/119161467/0b3e5bc1-db96-4fe8-a76b-924d11993b13

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by lakhan06** [comment]
@Souravvmishra I writing to bring you attention towards considering and reviewing the issue and assigning me this issue.
so please can you assign me this issue

**Comment by lakhan06** [comment]
@TANYA-CHAN PLease assign me this issue

**Comment by lakhan06** [comment]
@Spyware007 please assign me this issue

**Comment by lakhan06** [comment]
@adity2911 please assign me this issue

**Comment by adity2911** [comment]
Did you check the announcements?
No more buttons PR will be added after 20th june.

**Comment by adity2911** [comment]
assigned. make PR asap
