### ISSUE TITLE
Some buttons aren't supporting the dark theme. 😟

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#150]
**Light** mode:
<img width="526" alt="Screenshot 2022-10-23 at 1 25 55 AM" src="https://user-images.githubusercontent.com/89961974/197360119-7b4f3f16-68f1-409d-bb42-731de26ef9be.png">
**Dark** mode:
<img width="428" alt="Screenshot 2022-10-23 at 1 26 54 AM" src="https://user-images.githubusercontent.com/89961974/197360145-277fbd4d-aef0-42b7-b236-ecc289843f92.png">

Find such **buttons** and **fix** them.

**Comment by Sapna127** [comment]
i want to work on this issue please assign it to me @Spyware007

**Comment by Spyware007** [comment]
@Sapna127 Assigned to you

**Comment by amitkroutthedev** [comment]
@Spyware007  I can contribute in this problem?

**Comment by Spyware007** [comment]
Assigned to you @amitkroutthedev

**Comment by Sayyidalijufri** [comment]
can assign this issue to me please

**Comment by rbeaujon** [comment]
This ticket is not ready with the PR Buttons dark theme #210?
