### ISSUE TITLE
[Add] pause button

### ISSUE THREAD

**Issue by Kalivarapubindusree** [Spyware007/Animating-Buttons#1500]
### Details

I want to add pause button using HTML CSS javascript.
Can you please assign me this task under GSSOC'23 contribution @Spyware007 @t

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by adity2911** [comment]
Not accepted.
Check https://github.com/Spyware007/Animating-Buttons/issues/1347
