### ISSUE TITLE
[Add] Scroll to top button

### ISSUE THREAD

**Issue by Devil1205** [Spyware007/Animating-Buttons#1502]
### Details

Scroll to top button is a must for good user experience. I would to add it, kindly assign.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by adity2911** [comment]
Not accepted.
Check https://github.com/Spyware007/Animating-Buttons/issues/1347
