### ISSUE TITLE
[Add] Adding new 3D Button 

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1503]
### Details

Description:
I propose adding a new 3D button component to enhance the user interface of our open source project. This button will provide a visually appealing and interactive element that can be used for various actions, such as adding items to a cart, submitting forms, or initiating important actions.

Features and Specifications:
- The 3D button should have a modern and sleek design, with a subtle gradient and shadow effects to give it a sense of depth.
- It should support different sizes to accommodate various use cases and fit seamlessly into different layouts.
- The button should have hover and active states to provide visual feedback to users when they interact with it.
- It should be accessible and comply with web accessibility standards, ensuring that users with disabilities can easily interact with it.
- The button's code should be modular, allowing for easy customization and integration into our existing codebase.
- Considerations should be made for responsiveness, ensuring that the button adapts well to different screen sizes and devices.
- It would be great to include CSS animations or transitions to provide smooth and engaging visual effects when the button is clicked or hovered over.

By adding this 3D button component and providing detailed documentation, we can improve the user experience of our project and empower developers to easily incorporate visually appealing buttons into their applications.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Nishusk** [comment]
Kindly assign this issue to me under GSSoC'23. Thank you.

**Comment by adity2911** [comment]
Not accepted.
Check https://github.com/Spyware007/Animating-Buttons/issues/1347
