### ISSUE TITLE
[ADD] <ADD TO CART BUTTON>

### ISSUE THREAD

**Issue by Riya1922** [Spyware007/Animating-Buttons#1504]
### Details

i eagerly want to add this button. please assign this to me.
The add-to-cart button is a feature of ecommerce stores that allows customers to choose items to purchase without actually completing the payment.
it is coded in html, css, js

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by adity2911** [comment]
Not accepted.
Check https://github.com/Spyware007/Animating-Buttons/issues/1347
