### ISSUE TITLE
[Add]  Add Fancy Exploding Button Component with Shape Icon Splatter

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1510]
### Details

Description:
The project aims to introduce a visually appealing and interactive feature by adding a Fancy Exploding Button component to the existing open-source project. This component will be developed using ReactJS for functionality and GSAP for animation. When the user interacts with the button, it will trigger an explosion effect and scatter shape icons randomly across the screen.

Additional Considerations:
- Make the explosion effect configurable, allowing users to customize parameters such as explosion speed, size, and intensity.
- Consider providing options to control the type and number of shape icons used for the splatter effect.
- Ensure the component is responsive and works well on different screen sizes and devices.
- Maintain code quality by following best practices, writing clear and concise code, and adding appropriate comments and documentation.

### Screenshots

![Screenshot (877)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/d9f3813e-d7b5-4bd8-9f5e-7c2f752c4224)
![Screenshot (878)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/1d39d509-ee2a-415d-8b55-21fb38747efe)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Nishusk** [comment]
please assign this issue to me under GSSoC'23. Thank you!

**Comment by adity2911** [comment]
Not accepted.
Check #1347
