### ISSUE TITLE
[Add] Butterfly Hexagon Button

### ISSUE THREAD

**Issue by lakhan06** [Spyware007/Animating-Buttons#1515]
### Details

I want to add a Butterfly Hexagon Button

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/119161467/8cafb796-4462-4c57-94f0-2683bfb86f34

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by lakhan06** [comment]
@Souravvmishra please assign me this issue

**Comment by lakhan06** [comment]
@TANYA-CHAN Please assign me this issue

**Comment by lakhan06** [comment]
@Spyware007 please assign me this issue

**Comment by lakhan06** [comment]
@adity2911 please assign me this issue

**Comment by lakhan06** [comment]
hey @adity2911 can I give issues for improving tha UI of website

**Comment by adity2911** [comment]
You can be on hold for the moment. You can contribute more after the new website is deployed.

**Comment by lakhan06** [comment]
> You can be on hold for the moment. You can contribute more after the new website is deployed.

OK @adity2911

**Comment by lakhan06** [comment]
hey @TANYA-CHAN Can now i can give issues?

**Comment by TANYA-CHAN** [comment]
> hey @TANYA-CHAN Can now i can give issues?

Not right now actually, please check Discord for updates on when you can :)
