### ISSUE TITLE
[Add] <Adding Titles in the navbar Animating Buttons with the hover effect>

### ISSUE THREAD

**Issue by Shreya111111** [Spyware007/Animating-Buttons#1516]
### Details

It will help to describe the outsider to know what the website is all about.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Shreya111111** [comment]
@Spyware007  kindly assign me...

**Comment by aditi-chaurasia** [comment]
Please assign this issue to me under GSSOC'23 . I want to work on this.

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
