### ISSUE TITLE
New Line Hover Button

### ISSUE THREAD

**Issue by Durgesh4993** [Spyware007/Animating-Buttons#1522]
### Details

Technology used:
HTML
CSS

ScreenShort 
![image](https://github.com/Spyware007/Animating-Buttons/assets/98798977/a5ef0c3f-2f7e-43f5-809b-4aaaca72907c)

### Screenshots

Demo Vedio

https://github.com/Spyware007/Animating-Buttons/assets/98798977/71daaeca-f811-4b04-9145-01c9b5ac1dd1

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
