### ISSUE TITLE
[Add] I want to add a dog animation button that follows the cursor.

### ISSUE THREAD

**Issue by adity2911** [Spyware007/Animating-Buttons#1526]
### Details

It is a very neatly written code with all the extra information needed for anyone to implement it on their codebase.

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/72987111/87c9114d-c53a-4e9b-a42e-aaab84e2fe59

### Type of Contribution

- [X] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
