### ISSUE TITLE
Circular Hover Button

### ISSUE THREAD

**Issue by Durgesh4993** [Spyware007/Animating-Buttons#1527]
### Details

Technologies Used:
HTML
CSS

ScreenShort:
![image](https://github.com/Spyware007/Animating-Buttons/assets/98798977/6f13340d-edf8-41ff-8379-6e0c43be73b3)

### Screenshots

Demo Vedio:

https://github.com/Spyware007/Animating-Buttons/assets/98798977/eec64d96-8ba4-4aa3-8195-0e816c2e6384

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by aditi-chaurasia** [comment]
Please assign this issue to me under GSSOC'23 . I want to work on this.

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
