### ISSUE TITLE
Improve the UI of the homepage

### ISSUE THREAD

**Issue by akash0708** [Spyware007/Animating-Buttons#1532]
### Details

The padding on the sides is very less giving rise to a cluttered view. increasing the padding will provide a better view.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/110753356/b8b98bd4-5009-41ac-b7c3-baedd7adda27)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
