### ISSUE TITLE
[Add] New Hover Liquid animation button

### ISSUE THREAD

**Issue by Aryan5464** [Spyware007/Animating-Buttons#1535]
### Details

New Button

* A liquid hover animation button with purple color is a type of button that changes its appearance when the cursor hovers over it. The button will typically start out as a solid color, but when the cursor hovers over it, the color will start to "flow" or "ripple" outward. This creates a visually appealing effect that can help to draw attention to the button.

* The color of the liquid hover animation button can be customized, but purple is a popular choice because it is a vibrant and attention-grabbing color. The shade of purple can also be customized, so you can choose a color that matches your website's branding.

### Screenshots

![Screenshot 2023-06-23 231017](https://github.com/Spyware007/Animating-Buttons/assets/111825539/b535625e-6056-448d-ae26-504988d1844a)
![Screenshot 2023-06-23 230951](https://github.com/Spyware007/Animating-Buttons/assets/111825539/c5568f12-d1a5-488f-b19d-05157d9a4137)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Aryan5464** [comment]
@adity2911 Please assign me the issue.

**Comment by adity2911** [comment]
Not Possible Check Announcements. Closing the issue now
