### ISSUE TITLE
[Add] Flickering Animation Button

### ISSUE THREAD

**Issue by Aryan5464** [Spyware007/Animating-Buttons#1537]
### Details

***Flickering Animation Button***
A flickering hover animation button is a button that changes its appearance when the mouse cursor hovers over it. However, the animation is not smooth and instead, the button appears to flicker. 

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/111825539/a20fc2df-2968-4eca-9201-84d5505d4c5d

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Aryan5464** [comment]
@TANYA-CHAN  @Souravvmishra  @Spyware007 

Please Assign me the issue

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
