### ISSUE TITLE
[Add] Animated Button with particle effect. [gssoc'23]

### ISSUE THREAD

**Issue by smty2018** [Spyware007/Animating-Buttons#1539]
### Details

Want to add a button with particle animation: When the user hovers over the button, it releases a burst of particles or confetti. The particles can move in various patterns or form a specific shape, adding a playful and celebratory feel.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by smty2018** [comment]
@Souravvmishra @Spyware007 @adity2911 can you please assign me this issue

**Comment by Souravvmishra** [comment]
Checkout The Latest Guidelines
