### ISSUE TITLE
Improve Text Visibility in Dark Mode for Enhanced User Experience

### ISSUE THREAD

**Issue by unicorndiddy** [Spyware007/Animating-Buttons#1542]
### Details

Issue Description:
When using dark mode, the current implementation of bright white text can lead to reduced legibility and an unappealing visual experience. This issue aims to enhance the visibility of text in dark mode, ensuring that users can easily read and comprehend the content without straining their eyes.

Current Behavior:
In dark mode, the text color remains a bright white, which contrasts sharply with the dark background. This high contrast can cause discomfort for users, making it difficult to focus on the text.

Expected Behavior:
The text color in dark mode should be optimized to provide sufficient contrast against the background while maintaining readability and visual appeal. The improved text visibility will enhance the overall user experience, making it easier for users to read the content without unnecessary visual strain.

Proposed Solution:
To address this issue, I suggest exploring the following potential solutions:

1. Adjusting Text Color: Consider using a slightly softer or off-white color for text in dark mode. By reducing the contrast between the text and background, legibility can be improved while still maintaining visual harmony.
2. Text Shadowing: Introduce a subtle text shadow in dark mode to create a visual separation between the text and the background. This technique can improve readability by adding depth to the text and reducing the strain caused by high contrast.
3. Theme Customization: Provide users with the option to customize text colors in dark mode. This approach allows individuals to select a text color that suits their personal preferences and visual needs, ensuring optimal legibility for a broader range of users.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/113543711/1b9cee7f-dec0-4a5f-8649-09836a7a0bff)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [X] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
