### ISSUE TITLE
[Add]  A new icon button

### ISSUE THREAD

**Issue by komalioruganti** [Spyware007/Animating-Buttons#1544]
### Details

 Buttons are used to display various icons for social media and other operations. It is better to have icons in certain places than buttons. So I thought of making a button inside which any kind of icon can be placed. This icon would be round and have a solid color which changes upon hover effect.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/95839946/6ed770b6-26ec-4f82-84b0-fbfc16fe54e8)
![image](https://github.com/Spyware007/Animating-Buttons/assets/95839946/46fcf373-7950-45d6-a47e-9053eb3be58b)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by komalioruganti** [comment]
Can you assign me this issue? I would love to work on it.

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
