### ISSUE TITLE
[Add] Adding a new Animated button 

### ISSUE THREAD

**Issue by Manudasari265** [Spyware007/Animating-Buttons#1545]
### Details

This Animated button will have a boundary line surfing through all the corners of the button when hovered onto the button makes the button look beautiful and minimalistic.

### Screenshots

![Screenshot (232)](https://github.com/Spyware007/Animating-Buttons/assets/122810482/6fe8b484-b7fd-422d-9cde-a038cc9bf520)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Manudasari265** [comment]
@TANYA-CHAN Kindly assign this issue/task to me

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
