### ISSUE TITLE
[Add]3D flip button

### ISSUE THREAD

**Issue by Kalivarapubindusree** [Spyware007/Animating-Buttons#1548]
### Details

I want to add 3d flip button using html,css and javascript.
can you please assign this task under gssoc'23 contribution. @TANYA-CHAN @sp

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by aditi-chaurasia** [comment]
Please assign this issue to me under GSSOC'23 . I want to work on this.

**Comment by TANYA-CHAN** [comment]
> Please assign this issue to me under GSSOC'23 . I want to work on this.

No PRs at the moment, check discord for more updates please

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
