### ISSUE TITLE
copyright year is not dynamic

### ISSUE THREAD

**Issue by techmannih** [Spyware007/Animating-Buttons#1550]
### Details

hello @Spyware007  ,
I found an issue in your website " Animatung-Buttons" in which copyright year is not dyanamic for moblie and tablet devices please check it
And I want to work on this issue ...please assign me of this issue

### Screenshots

![2023-06-24-20_32_18-screenshot](https://github.com/Spyware007/Animating-Buttons/assets/125847751/011fefde-032a-409b-8652-9c2c56c541f6)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
