### ISSUE TITLE
Fix Styling of Create Button in Navbar. 📌

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#1557]
The create button styling is not proper which is present on the Navbar.

**Comment by scove-viber** [comment]
It's little bit large I guess relative to other buttons in navbar. Is that the only problem?
Or will it be fine It gets completely changed?

**Comment by Spyware007** [comment]
@scove-viber 
Make it look different and highlighted from others 
Assigned to you! 🚀

**Comment by Spyware007** [comment]
@scove-viber What's the update?

**Comment by Naina047** [comment]
Hey @Spyware007 
I would like to work on this. Please assign me this under GSSOC'23.

my proposed change:
![Screenshot 2023-06-26 163219](https://github.com/Spyware007/Animating-Buttons/assets/96466577/f1b1de13-7f18-4f8d-88b1-8eb84f6213fa)

**Comment by adity2911** [comment]
@Naina047 Someone has already been assigned to this issue. Kindly look for other ways to contribute.

**Comment by Naina047** [comment]
Didn't he removed his assignment?

**Comment by adity2911** [comment]
check #1594
