### ISSUE TITLE
Make Navbar Responsive 🌟

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#1558]
Navbar is not responsive.
We will be adding more things to the navbar and it will get cluttered for the mobile devices.
So you need to develop a Navbar that is fully responsive!

**Comment by scove-viber** [comment]
Setting position to relative can make navbar responsive. 
Can I work on it?

**Comment by ManishaSwain8** [comment]
I can also work on it !

**Comment by Spyware007** [comment]
@scove-viber 
No there should be a hamburger instead of navbar in mobile devices!

@ManishaSwain8 
What's your approach?
Are you able to add animation to the Navbar and hamburger using framer motion?

**Comment by scove-viber** [comment]
Adding a media query to the navbar that targets screens with a width of 768px or less.
After that we have hide the navbar and show hamburger icon in media query and after that adding event listener to the hamburger icon that toggles the visibility of the navbar we can make it happen.

**Comment by Spyware007** [comment]
@ManishaSwain8 Assigned to you!

**Comment by ManishaSwain8** [comment]
@Spyware007 I am working on About page you can assign to *scove-viber*  : )

**Comment by Souravvmishra** [comment]
@ManishaSwain8 Any Updates?

**Comment by ManishaSwain8** [comment]
@ManishaSwain8 actually I am already working on other part

**Comment by kartikjoshi267** [comment]
@Souravvmishra Can I work on this issue?

**Comment by Souravvmishra** [comment]
@kartikjoshi267 Someone is already working on the same

**Comment by kartikjoshi267** [comment]
> @kartikjoshi267 Someone is already working on the same

But there is no assignee!!

**Comment by crocmons** [comment]
Can I work on this?

**Comment by LaxmanSingh07** [comment]
Could you please consider assigning this issue to me under GSSOC'23
