### ISSUE TITLE
Redesign the Footer 💫

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#1560]
We have to add the nav links to the footer.
As well as dynamic copyright and all other necessary things!
Please share the Figma design file of your proposed design.
Screenshot also works!

**Comment by Abhinavcode13** [comment]
Assign this to me @Spyware007

**Comment by Spyware007** [comment]
@Abhinavcode13 
Assigned to you!
Please share the designs first before starting to work on this!

**Comment by Saloni581** [comment]
Hello @Spyware007 I can work on this issue, kindly assign it to me.
