### ISSUE TITLE
About Project page Redesign ❣️

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#1561]
The page contains information about the project, the project admin, some contributors who had made impactful contributions, and a timeline that I had already added.
Make sure to share the Figma file for your proposed design.

**Comment by Spyware007** [comment]
The above issue will require multiple PRs
So the points are based on a number of PRs and functionalities!

**Comment by ManishaSwain8** [comment]
https://www.figma.com/file/hMnpJLjZjDlPhS1afr6f0q/Untitled?type=design&node-id=0%3A1&mode=design&t=wOH9CM2AWfaia14d-1

Check out figma design !
(I am not a Figma guy just wanted to give it a try : )

**Comment by Spyware007** [comment]
@ManishaSwain8 This looks kinda awesome.
Please make it Responsive too.
Also, use the timeline I had created!

Assigned to you!
All the best! 🤩

**Comment by ManishaSwain8** [comment]
@Spyware007 I will open PR soon ..!

**Comment by ManishaSwain8** [comment]
@Spyware007 I need little help,
![Screenshot (96)](https://github.com/Spyware007/Animating-Buttons/assets/96622693/649665e1-e36c-43c3-9d2f-377c02ddb95c)
I am getting this error now ,

**Comment by Spyware007** [comment]
@ManishaSwain8 
Dm me on Discord!
We will figure it out tomorrow noon!
