### ISSUE TITLE
Explore Page 🚀

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#1562]
Some of the best buttons will be showcased on this page.
The page will also have a featured buttons section.
Share the Figma file and then we can start working accordingly.

**Comment by Spyware007** [comment]
The above issue will require multiple PRs
So the points are based on a number of PRs and functionalities!

**Comment by Sapna127** [comment]
Hey @Spyware007 
I would like to work on this issue.. 
Please assign it to me

**Comment by Saloni581** [comment]
Hello @Spyware007 I can work on this issue, kindly assign it to me.

**Comment by hansupadhyay007** [comment]
Hello, can you please assign me this task. I wanted to work on it

**Comment by TANYA-CHAN** [comment]
🎉 The GSSOC'23 program has reached its conclusion, prompting us to officially close all pull requests (PRs) and issues. We extend a heartfelt thank you for your amazing contributions! 🙌 Keep the coding spirit alive with the same enthusiasm, and may luck 🍀 favor you in all your future coding adventures!
