### ISSUE TITLE
Position of the like button on the card. 🤔

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#1563]
The like counter button on the card doesn't look great at the current positon.
Redesign the card UI

**Comment by AnkitAnandMastery17** [comment]
Can you assign this to me?

**Comment by Spyware007** [comment]
@AnkitAnandMastery17 
Assigned to you!
Please share your approach as well as design before starting to work on it!

**Comment by AnkitAnandMastery17** [comment]
I am currently working on it. I will share it in two days.

**Comment by Souravvmishra** [comment]
@AnkitAnandMastery17 Its been a while, any updates
