### ISSUE TITLE
Imporve the login page UI 🥶

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#1564]
Improve the login page UI design!
Also, add options to edit your profile!

**Comment by Spyware007** [comment]
The above issue will require multiple PRs
So the points are based on a number of PRs and functionalities!

**Comment by Pulkitxm** [comment]
Can I get assigned? lemme know how to start

**Comment by Spyware007** [comment]
@Pulkitxm 
Assigned to you 
Please share the designs first and then start working on it!

**Comment by Pulkitxm** [comment]
![image](https://github.com/Spyware007/Animating-Buttons/assets/65671483/31f76127-04fc-4c52-9f1f-efad11b08838)
how about this , It's from my otheer project ?

**Comment by Spyware007** [comment]
We are only having a GitHub sign in!

**Comment by Spyware007** [comment]
@Pulkitxm Are you working on this? ANy updates???

**Comment by Nishitbaria** [comment]
@Spyware007 please assign me to this issue I already created this type of GitHub login pages

**Comment by Spyware007** [comment]
@Nishitbaria Assigned to you!
All the best!

**Comment by Nishitbaria** [comment]
@Spyware007  What else you want apart from github login option?

**Comment by Spyware007** [comment]
@Nishitbaria Only GitHub login is required!

**Comment by Nishitbaria** [comment]
@Spyware007  ,can you specify which functionality do you need in login page and if you can give design
