### ISSUE TITLE
Make a new Readme.md  🤩

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#1565]
Contact me on Discord for discussing and creating a new Readme.md for the project!

**Comment by scove-viber** [comment]
I would like to work on this issue.

**Comment by arcVaishali** [comment]
I would love work on this issue. I have worked on documentations in the past, **@Spyware007** kindly assign me this issue. Thank you.

**Comment by Spyware007** [comment]
Hello @scove-viber 
You have already been assigned to an issue.
Finish those first and then I will assign you to more issues!

@arcVaishali Yup ping me on discord!
Assigning to you!
All the best 🍫
