### ISSUE TITLE
[BUG] Share Image not visible

### ISSUE THREAD

**Issue by Avinash905** [Spyware007/Animating-Buttons#1567]
### Details

- When you share this website on any social media then no image will be visible as it lacks image url in meta tags like open graph and twitter (verified by social share preview).
- Also some meta tags like language, keywords, robots, author and many more are missing.

Adding them to your website will increase your SEO

### Screenshots

![Screenshot (530)](https://github.com/Spyware007/Animating-Buttons/assets/56786344/d36632a7-1499-4126-84e3-58f701071c52)
![Screenshot (531)](https://github.com/Spyware007/Animating-Buttons/assets/56786344/77548a39-a6c8-45d4-8067-35d3fe36e8f2)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by Spyware007** [comment]
@Avinash905 Thank you for creating the issue!
Assigned to you!
All the best! 🚀
