### ISSUE TITLE
I want to add an animated button

### ISSUE THREAD

**Issue by ShakshiSingh07** [Spyware007/Animating-Buttons#1570]
### Details

I want to create new animated button for the website using html and css

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by PoorviShetty** [comment]
Hi, please check https://github.com/Spyware007/Animating-Buttons/discussions/1346
