### ISSUE TITLE
[Add] Adding hover effect to stars, forks, contributors tabs

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Spyware007/Animating-Buttons#1573]
### Details

I wil be adding hover effect for the above and also changing cursor when hover

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/85278243/1811022c-81bc-4aae-b58c-8b5adee868ee)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [x] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by adity2911** [comment]
Assigned.
