### ISSUE TITLE
[Animation] Adding animation to the landing page.

### ISSUE THREAD

**Issue by ManishaSwain8** [Spyware007/Animating-Buttons#1576]
### Details

As per the new website, it is looking bit static it will be cool if we add animations to the home  page itself,Cause animation is a good way to make a website attractive and alive. And as the website is in react ,so best choice will be to use Framer Motion as per my experience for animation or anything else can be used.
If this changes req. do assign me under GSSOC 2023. : |)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
@ManishaSwain8 
Assigned to you!
All the best! 🤩

**Comment by ManishaSwain8** [comment]
Will open PR soo  : |)
