### ISSUE TITLE
[Add] Animation Button

### ISSUE THREAD

**Issue by Harshu467** [Spyware007/Animating-Buttons#1577]
### Details

I am creating a new animated button with best user friendly design and also very attractive design

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by PoorviShetty** [comment]
Hi, please check https://github.com/Spyware007/Animating-Buttons/discussions/1346
