### ISSUE TITLE
[Add] Hover Effect on 'Sign in With GitHub' Button

### ISSUE THREAD

**Issue by Sriparno08** [Spyware007/Animating-Buttons#1580]
### Details

I want to add a hover effect on 'Sign in With GitHub' button which will make it more interactive.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/89148144/2053e995-8836-4869-84fd-b84a30ce0e69)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by adity2911** [comment]
Someone else is working on it. Kindly wait for their PR and then check if it can be improver more by you #1557
