### ISSUE TITLE
Adding Gradient in the background 

### ISSUE THREAD

**Issue by Rohitn-2312** [Spyware007/Animating-Buttons#1587]
### Details

 

**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

A Gradient is needed in the background to make the website look more attractive . And the links which are present at the starting needs a proper styling .
Please assign this issue to me under GSSoC'23.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by adity2911** [comment]
Share the design ScreenShot
