### ISSUE TITLE
Adding dependabot.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [Spyware007/Animating-Buttons#1590]
*We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.*

*I have previously created a PR for the same issue #1315 which was closed yesterday and I was instructed to raise a new issue for this*

@Spyware007 please assign me this issue under gssoc'23.

**Comment by Spyware007** [comment]
@Anshika-Jain02 Yes,
Sorry for the inconvenience.
You can create a PR for the same!
