### ISSUE TITLE
[Fix]  Create and Sign in with Github button

### ISSUE THREAD

**Issue by rishuraj1** [Spyware007/Animating-Buttons#1594]
### Details

The buttons on navbar (create, signin with github) are not appealing and styles are not relevant.

I want to improve it by adding modern styles and simple UI.

I really want to contribute to this wonderful project. Please assign this task to me under GSSoC '23. Thank You!

### Screenshots

<img width="960" alt="image" src="https://github.com/Spyware007/Animating-Buttons/assets/47839626/45441e97-cfe2-451a-acf5-c72c3e1d3852">

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [x] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
@rishuraj1 Any updates??

**Comment by rishuraj1** [comment]
@Spyware007  working on it

**Comment by adity2911** [comment]
You may make a PR of your work and keep on making commit if you want to. This way we will be able to review it too
