### ISSUE TITLE
[Add] Make home fully responsive

### ISSUE THREAD

**Issue by SubhamB2003** [Spyware007/Animating-Buttons#1608]
### Details

Hey, the current home page is not responsive can you see below
Can you please assign me this issue under GSSOC'23?

Current state
![image](https://github.com/Spyware007/Animating-Buttons/assets/94003231/6b712105-2630-445e-90f7-3161b9ea6c20)

After improvement
![image](https://github.com/Spyware007/Animating-Buttons/assets/94003231/afde920c-0631-4c45-a7e6-ae1f6144d4f5)
 

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [x] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by adity2911** [comment]
is that a mobile view?

**Comment by SubhamB2003** [comment]
> is that a mobile view?

Yes

**Comment by adity2911** [comment]
you may work on it.

**Comment by SubhamB2003** [comment]
> you may work on it.

Hey, can you tell me how can I fix this?

![image](https://github.com/Spyware007/Animating-Buttons/assets/94003231/605f83d7-1b49-4b5c-8cee-8dccf97b94c0)

**Comment by SubhamB2003** [comment]
> 

Hey, I made the changes but the navbar is not responsive you can check below
![image](https://github.com/Spyware007/Animating-Buttons/assets/94003231/564d92f1-8341-43a9-adb7-dff9fa4280f7)

**Comment by adity2911** [comment]
Also try to do something about the navbar too.

**Comment by SubhamB2003** [comment]
> Also try to do something about the navbar too.

Yeah I also change the navbar

**Comment by adity2911** [comment]
share screenshot please
