### ISSUE TITLE
[Fix]: Bug which loads the entire frame on the iframe. 

### ISSUE THREAD

**Issue by adity2911** [Spyware007/Animating-Buttons#1612]
### Details

There is a wired bug that loads the entire page inside the iframe once the button is clicked. 
According to my observation has something to do with buttons that does not have any Java Script code on them.

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/72987111/2b0ba1ff-041f-4dba-a088-50e8f48d6eb7

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue
- [ ] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
@adity2911 It might be the anchor tag!
they had used href ="/" in it!
This may be the reason for this issue!

**Comment by adity2911** [comment]
can you tell me where?

**Comment by adity2911** [comment]
Actually I think this has something to do with iframe logic since it is not there in every button.
This bug is available for some of the buttons only.

**Comment by adity2911** [comment]
Assigned
