### ISSUE TITLE
[Add] Want to add a Customized Search Bar in the Navbar section 

### ISSUE THREAD

**Issue by Aryan5464** [Spyware007/Animating-Buttons#1615]
## I want to  add a customized search bar in the navbar section
# I want to add a search bar because It helps users find what they are looking for quickly and easily. 
# This is especially important for websites with a lot of content, as it can be difficult to find what you are looking for by browsing through the menus.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/111825539/fe80cafa-10b1-4059-98b6-7230bcb65d6b)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by adity2911** [comment]
Can you briefly explain how you plan to implement the search feature?

**Comment by Nevish-302** [comment]
@adity2911 has the issue been resolved? if not, i'd like to be assigned to it
