### ISSUE TITLE
[Add] <add menu and hide buttons >

### ISSUE THREAD

**Issue by dheeraj1129** [Spyware007/Animating-Buttons#1619]
### Details

1. Add a menu and hide icons. to minimize the nav bar element and hide unnecessary details in a small device

2. ADD the create button inside the menu buttons bars for the small device 

### Screenshots

![Screenshot (29)](https://github.com/Spyware007/Animating-Buttons/assets/72201773/252bc244-a169-43b0-824a-dc7d38dfcfe6)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by adity2911** [comment]
Assigned. You may work on it.
