### ISSUE TITLE
[Add] Search Bar to find Buttons

### ISSUE THREAD

**Issue by harshit-tiwaari** [Spyware007/Animating-Buttons#1621]
### Details

Want to add a search bar in explore page to find the buttons in one go as the developer wants like below.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/104323483/e9e3f275-745d-4ca6-ae5c-c77a5d189fae)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Souravvmishra** [comment]
Can You Explain The Algorithm You'll Use To Search Button?

**Comment by Shubham1450** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23.

**Comment by Souravvmishra** [comment]
Sure, But Can You First Explain The Logic, How Would You Search The Button?

**Comment by harshit-tiwaari** [comment]
that i need to look upon but will do surely i you will assign me as i have worked on an ecommerce site that has search bar for products similarly i can do here.Will take time but can do that.

**Comment by Souravvmishra** [comment]
This is completely different from an e-commerce store. Look into the code base once & explain the logic you'll be using before getting assigned.
