### ISSUE TITLE
[Animation] Animation in cards

### ISSUE THREAD

**Issue by ojasaklechayt** [Spyware007/Animating-Buttons#1627]
### Details

I wants to add animation as we scroll them down.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by ojasaklechayt** [comment]
@Akanksha-202 can you please assign this to me ?

**Comment by Spyware007** [comment]
@ojasaklechayt What are you going to use for implementing animations?

**Comment by ojasaklechayt** [comment]
> @ojasaklechayt What are you going to use for implementing animations?

I will do it with framer motion mostly

**Comment by Spyware007** [comment]
@ojasaklechayt  Cool!
Assigned to you!
All the best!
