### ISSUE TITLE
[Add] Max width is needed in the website

### ISSUE THREAD

**Issue by HimanshuNarware** [Spyware007/Animating-Buttons#1629]
### Details

The width of the website is more than 100vw and its affecting the UI of the website. I want to work in this issue.

### Screenshots

![114](https://github.com/Spyware007/Animating-Buttons/assets/83147410/47cba26d-6575-4b1e-a253-9c1a978f6304)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by adity2911** [comment]
Assigned. You may work on it.
