### ISSUE TITLE
[Add] light background for cards in light mode

### ISSUE THREAD

**Issue by rishuraj1** [Spyware007/Animating-Buttons#1640]
### Details

We might want to change background color of the cards when in light mode.
Currently it is black which does not justifies the purpose of light theme.

Below is the screenshot of the proposed idea. Please assign this task to me under GSSoC '23. Thank you!

### Screenshots

current:

![image](https://github.com/Spyware007/Animating-Buttons/assets/47839626/a439a2e3-e2f0-48ff-b556-fdf9060f8dc7)

proposed idea : 

![image](https://github.com/Spyware007/Animating-Buttons/assets/47839626/8d09aa37-1de1-4472-87b0-f120e619aba3)

 PS: Please suggest me different colors if you do not like this one.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
@rishuraj1 

Can you change the like button color, show code and download button also for the light theme?

**Comment by rishuraj1** [comment]
@Spyware007  yes ofcourse I plan to change every component of the card according to the loght theme. 
This is just a proposed idea.

**Comment by Spyware007** [comment]
Okay sure!
Assigned to you!
