### ISSUE TITLE
[Add] Up Arrow button with animating effect

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Spyware007/Animating-Buttons#1642]
### Details

- This Up arrow button is continuously moving upward.
- Adding a moving effect with a pulse generation around it.
- Created just using CSS only.
- Beginner friendly project with best moving effect.

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/114330097/d3c5a767-2bfb-42fa-8444-c65b4052dad2

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Avdhesh-Varshney** [comment]
@Spyware007 @PoorviShetty @TANYA-CHAN please assign this issue to me to contribute under GSSoC'23 program

**Comment by Srishtikumari2002** [comment]
@Spyware007 @Avdhesh-Varshney if this issue is still open, then I would like to work on it.
