### ISSUE TITLE
[Add] Animating Button

### ISSUE THREAD

**Issue by DivyanshiNarang** [Spyware007/Animating-Buttons#1645]
### Details

Addition of the following animating button.

@Spyware007  Please assign this issue to me under GSSoC'23.

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/74779601/943da31a-2a55-4394-908f-0a3fe43a7d68

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Kajal2468** [comment]
I would like to add Animating button and make it more functional.
@Spyware007 please assign this issue to me under Gssoc23.


Thanks you!
