### ISSUE TITLE
[Fix]  Like Button Functionality Not Working

### ISSUE THREAD

**Issue by Nishitbaria** [Spyware007/Animating-Buttons#1650]
### Details

Currently, the like button functionality on the website is not working, preventing users from engaging with the platform and expressing their appreciation for posts or content. This issue needs to be addressed to ensure a seamless user experience and allow users to interact effectively with the platform. 

I will solve this issue in  5min   :) please assign to me 

### Screenshots

![WhatsApp Image 2023-06-28 at 16 36 39](https://github.com/Spyware007/Animating-Buttons/assets/85815172/16e94a24-d871-4071-85f5-813be6aa5400)

### Type of Contribution

- [X] Update to an existing Animated Button
- [X] Adding a new Button
- [X] Resolving a bug
- [X] Proposal to the Repository
- [X] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Nishitbaria** [comment]
please @Spyware007 assign me to this issue

**Comment by Spyware007** [comment]
@Nishitbaria Are you logged in?
It will work only if you are logged in!

**Comment by Nishitbaria** [comment]
@Spyware007  please check out this video  :  


https://github.com/Spyware007/Animating-Buttons/assets/85815172/14e76590-57ce-497d-932b-68f5a0ce4d94

**Comment by Spyware007** [comment]
@Nishitbaria Can you tell me the possible reason for not working of the liked button?

**Comment by adity2911** [comment]
I have take care of it

**Comment by Nishitbaria** [comment]
This is not appropriate,I was fixing this issue  actively and all of sudden you take this issue from me ,Can you please assign me this issue or  any other issue to work for?

**Comment by adity2911** [comment]
I am a collaborator and I was working on the issue beforehand.

**Comment by adity2911** [comment]
This was already been taken care of by us. You can check #1644. I was fixing these kind of issues from before.

**Comment by Nishitbaria** [comment]
> This was already been taken care of by us. You can check #1644. I was fixing these kind of issues from beforehand.

ok no problem :)   

Can you please assign me this issue  #1564

**Comment by adity2911** [comment]
you can see #1612 if you can

**Comment by adity2911** [comment]
> > This was already been taken care of by us. You can check #1644. I was fixing these kind of issues from beforehand.
> 
> ok no problem :)
> 
> Can you please assign me this issue #1564

@Spyware007 is taking care of that.
