### ISSUE TITLE
Update the About Us page of the website

### ISSUE THREAD

**Issue by hima-v** [Spyware007/Animating-Buttons#1651]
### Details

The about us is an important portion of the website as it explains about the website features and the project admin. 
I want to add the relevant static content. 

### Screenshots

Currently this is the content on About Us page: 

![image](https://github.com/Spyware007/Animating-Buttons/assets/79623293/e97cc411-6dc5-4226-a987-7fa519106ff5)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [X] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
@hima-v Do you have to replace the lorem epsum?

**Comment by Riyazul555** [comment]
Hey @Spyware007 I want to work on this issue .......please assign me this

**Comment by hima-v** [comment]
> @hima-v Do you have to replace the lorem epsum?

Yes

**Comment by Spyware007** [comment]
@hima-v 
I am assigning this to you!
Few more contributors are working on the About us page, so please avoid merge conflicts.

**Comment by sushmaJyoti2022** [comment]
I want to work on this issue . Please assign me this.
