### ISSUE TITLE
Fix the explore page bug

### ISSUE THREAD

**Issue by hima-v** [Spyware007/Animating-Buttons#1652]
### Details

The site is not redirecting to the explore page. I want to fix the bug

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/79623293/12735047-3645-4d7d-8d81-28850383efb4)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
@hima-v There is no explore page!
