### ISSUE TITLE
Want to add some hover effects on find your perfect button

### ISSUE THREAD

**Issue by Riyazul555** [Spyware007/Animating-Buttons#1657]
### Details

Adding some hover effects on this front button (Find your perfect button) will surely give more illustrations .

I want to work on this issue ......please assign me this @Spyware007 

### Screenshots

![Screenshot (327)](https://github.com/Spyware007/Animating-Buttons/assets/121575277/4a39e117-892d-4652-83cd-5ef49e6da65a)

### Type of Contribution

- [X] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
@Riyazul555 This is the old UI
Kindly update your branch!
