### ISSUE TITLE
Fixing empty button cards

### ISSUE THREAD

**Issue by shruuti321** [Spyware007/Animating-Buttons#1672]
### Details

I would like to fix these empty button cards as these are disturbing the uniformity of the website
.Kindly assign me this issue under gssoc'23.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/114770273/1201e961-b633-4743-bc49-776c6127842d)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
@shruuti321 What's your approach to solve this issue?

**Comment by shruuti321** [comment]
In the buttons folder there is no file named samriddhi15 but it is added in the data.js that is why it is showing empty on the website. They have been added in the form of samriddhi15_1.So the simple fix is to remove samridhhi15 from data.js and similarly for some other user names or otherwise we could add a new file with new code with the same name.
So I would like to try this issue and fix it.
![image](https://github.com/Spyware007/Animating-Buttons/assets/114770273/b4e0cd42-3fbd-4697-8c56-7f93bfb0aa91)

**Comment by shruuti321** [comment]
Can I take this issue? @Spyware007

**Comment by Spyware007** [comment]
You need backend access to fix this!

And the keys are only accessible to me!
