### ISSUE TITLE
[Add]: Smooth Scrolling feature in website

### ISSUE THREAD

**Issue by Killer2OP** [Spyware007/Animating-Buttons#1673]
### Details

 Hey, I want to make some improvements to the code and added a smooth scroll feature that provides users with a seamless navigation experience when clicking on links in the navigation bar. I believe this enhancement would greatly benefit our project. Therefore, I kindly request you to assign me this issue.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Killer2OP** [comment]
@TANYA-CHAN @PoorviShetty @Spyware007
Can you assign me this issue.

**Comment by Spyware007** [comment]
@Killer2OP what are you going to use it for adding this feature?

**Comment by Killer2OP** [comment]
> @Killer2OP what are you going to use it for adding this feature?

react-scroll package can be used to implement this feature.

**Comment by Souravvmishra** [comment]
@Killer2OP To Which Section You Want To Add This Feature?
