### ISSUE TITLE
[Add] Home Button with 3D Object

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1689]
### Details

I would like to propose the addition of an Home button in this project. This will be special kind of Button.When users hover over the Home button, a house shape object will animate and rotate in a 2D fashion, providing a visually appealing effect.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Nishusk** [comment]
Please assign this issues to me under GSSoC'23.

**Comment by adity2911** [comment]
This was not assigned to you!! Why are you making PR before the assignment?

**Comment by Nishusk** [comment]
> This was not assigned to you!! Why are you making PR before the assignment?

I apologize for the misunderstanding and any inconvenience caused. Thank you for bringing it to my attention. I understand that the pull request was submitted prematurely without proper assignment. I assure you that I will promptly close the pull request to rectify the situation. Again, I apologize for any confusion caused and appreciate your understanding.
