### ISSUE TITLE
[FEAT]:  ACCESSIBLE SOCIAL ANCHORS FOR FOOTER 💡

### ISSUE THREAD

**Issue by 0xabdulkhalid** [Spyware007/Animating-Buttons#1693]
### Details

- This issue is about adding `aria-label` for social anchors (links like Github) which are placed inside the `footer` element

- it is important to note that we want to add the `title` attribute also. This is because the `title` attribute is intended to provide additional information to screen reader users.

- The `aria-label` attribute is a way more important for providing accessibility information to screen reader users. The `aria-label` attribute is an Accessible Rich Internet Applications (ARIA) attribute that can be used to provide a label for an element. This label is then read aloud by screen readers, providing additional information about the element to the user.

- In general, the `aria-label` & `title` attributes are preferred for providing accessibility information to screen reader users.

- You can consider to assign this issue to me to make the site accessible for screen readers

### Screenshot (Going to make changes on these elements)

![Screenshot 2023-07-01 at 14-52-35 Animated Buttons](https://github.com/Spyware007/Animating-Buttons/assets/92252895/f2cb322a-8be2-432d-941d-3c60a97671e8)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by 0xabdulkhalid** [comment]
Hey there @Spyware007, @PoorviShetty, @Souravvmishra  👋🏻 

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by Souravvmishra** [comment]
Good Luck 👋
