### ISSUE TITLE
[FEAT]: ADD NAV BAR THEME FOR WEBSITE 💡

### ISSUE THREAD

**Issue by 0xabdulkhalid** [Spyware007/Animating-Buttons#1695]
### Details

- The new feature is about introducing a theme color for the navigational bars of devices (browser's theme are overriden)
- The usage of providing a theme color in the meta tag for HTML allows you to define the color that will be used as the browser's theme color when a user visits your website. The theme color is displayed in the browser's UI elements such as the address bar, tabs, and task switcher.
-  Branding: You can use your brand's primary color or a color that aligns with your website's design to reinforce your brand identity. This can create a consistent and recognizable experience for users across different platforms.
- User experience: By setting a theme color that matches your website's design, you can provide a cohesive and immersive user experience. The theme color can seamlessly integrate the browser UI with your website's color scheme, enhancing visual continuity.
- Visual appeal: A well-chosen theme color can make your website stand out and make a positive impression on users. It adds a touch of personalization and professionalism to the browsing experience.
- Accessibility: The theme color can also contribute to accessibility considerations. By selecting a color with sufficient contrast against the browser UI elements, you can improve readability and ensure that the UI remains legible for users with visual impairments.
- The primary theme color of this site is two colors
  - `#151515`
  - `#72ebeb`
- The colors can be switched on the nav-bar like the body when switching the mode to light and dark

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by 0xabdulkhalid** [comment]
Hey there @Spyware007, @PoorviShetty, @TANYA-CHAN, @Souravvmishra 👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by 0xabdulkhalid** [comment]
Hey there @Spyware007, @PoorviShetty, @TANYA-CHAN, @Souravvmishra 👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by Souravvmishra** [comment]
@0xabdulkhalid You Can work on this

**Comment by TANYA-CHAN** [comment]
🎉 The GSSOC'23 program has reached its conclusion, prompting us to officially close all pull requests (PRs) and issues. We extend a heartfelt thank you for your amazing contributions! 🙌 Keep the coding spirit alive with the same enthusiasm, and may luck 🍀 favor you in all your future coding adventures!
