### ISSUE TITLE
Title: Responsive Navbar

### ISSUE THREAD

**Issue by Neha5679** [Spyware007/Animating-Buttons#1697]
### Details

On scroll down Navbar is not showing, so i would like to work on it. Also i want to add hovering effect on navbar list items.

### Screenshots

![Screenshot (83)](https://github.com/Spyware007/Animating-Buttons/assets/129548970/e6bcdc85-5c30-4820-a207-d332723e434c)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [X] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Souravvmishra** [comment]
We're currently good with this one. You can work on other issue. Thank You
