### ISSUE TITLE
[FEAT] Show a clear message after successfully creating a button

### ISSUE THREAD

**Issue by Srishtikumari2002** [Spyware007/Animating-Buttons#1706]
### Details

Every time after creating a new button the page gets reloaded, but it does not clearly signify that the button is created or not. Hence it would be better if we show a message after each successful creation of a button. 

Otherwise, use didn't get either button created or not and they will click on Create button multiple times, which would lead to the creation of the same button multiple times.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
@Srishtikumari2002 What are you going to use for showing this?
https://react-hot-toast.com/
Please use this library!

**Comment by Srishtikumari2002** [comment]
Ok,sure I will try to make it reusable.

**Comment by Srishtikumari2002** [comment]
Can I have your discord user ID?

**Comment by Spyware007** [comment]
> Can I have your discord user ID?
@Srishtikumari2002 
683897337940410399
<img width="1440" alt="Screenshot 2023-07-04 at 12 05 00 AM" src="https://github.com/Spyware007/Animating-Buttons/assets/89961974/5997aafb-4577-4ed8-bd99-0d33b5cf9274">

**Comment by Spyware007** [comment]
Hello @Srishtikumari2002 Are you still willing to work on this?

**Comment by Srishtikumari2002** [comment]
Yes I am working on it, please give a bit more time.

**Comment by Souravvmishra** [comment]
@Srishtikumari2002 Its been so long. Do you have any update or should we close this issue

**Comment by Srishtikumari2002** [comment]
I have already open a pull request for this, waiting for your review.
