### ISSUE TITLE
Open links in a new tab

### ISSUE THREAD

**Issue by abansal15** [Spyware007/Animating-Buttons#1713]
### Details

links in the screenshot are not opening in the new tab which is not user friendly. i will make the links to open in a new tab

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/120590200/62ad6791-7f23-4e66-9f3e-038bfcee9272)

![image](https://github.com/Spyware007/Animating-Buttons/assets/120590200/357c1cc8-e316-4868-8125-cbd67ea5e7b7)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by abansal15** [comment]
hello i would like to work on the issue could you please assign it to me

**Comment by Souravvmishra** [comment]
We,re closing this issue as its been more than a month
