### ISSUE TITLE
[Add] Message for errors/success

### ISSUE THREAD

**Issue by adity2911** [Spyware007/Animating-Buttons#1726]
### Details

A message will appear when the user Updates bio or there is any kind of error on the page.

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/72987111/ac402827-e50c-45b4-adeb-b5fe603828ec

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Souravvmishra** [comment]
Bro Please Check #1706

**Comment by adity2911** [comment]
Yes I was made aware of this by spyware so I didn't comit
