### ISSUE TITLE
[Add] Redesign The Timline Component For Small Screen

### ISSUE THREAD

**Issue by Souravvmishra** [Spyware007/Animating-Buttons#1732]
### Details

Redesign The Timline Component For Small Screen. 

### Screenshots

![Screen Shot 2023-07-04 at 11 23 04](https://github.com/Spyware007/Animating-Buttons/assets/89072785/a62b4a9d-57b9-4e5f-ac22-0d6d8d6a1c4c)
![Screen Shot 2023-07-04 at 11 20 40](https://github.com/Spyware007/Animating-Buttons/assets/89072785/e52c525e-7297-41fe-80ad-9474f926804a)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Souravvmishra** [comment]
@Spyware007 @adity2911 Don't You Think The Older Ones Looks So tightly Packed? Please Review Once

**Comment by Spyware007** [comment]
Can you make the line on the left side and boxes on the right side!

**Comment by Souravvmishra** [comment]
Yup 💯

**Comment by adity2911** [comment]
> Can you make the line on the left side and boxes on the right side!
 design is fine on the either side.
