### ISSUE TITLE
[Add] Make the navbar sticky

### ISSUE THREAD

**Issue by karthiknadar1204** [Spyware007/Animating-Buttons#1738]
### Details

As the user scrolls , instead of keeping the navbar fixed to the top of the page, my proposition is to move the navbar down as the user scrolls down the page.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
We don't want a sticky navbar!
