### ISSUE TITLE
[Add] Responsiveness to the website

### ISSUE THREAD

**Issue by PiyushK79** [Spyware007/Animating-Buttons#1750]
### Details

As I was checking for the responsiveness, I saw that the cards displaying the buttons are overflowing from the container cards.
I would like to add responsiveness to the website and make it more functional.
@Spyware007 please assign this issue to me under Gssoc23.

### Screenshots

![cards](https://github.com/Spyware007/Animating-Buttons/assets/100259650/9c3229df-e52d-4d47-8d6a-6abce7719cb4)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Kajal2468** [comment]
I would like to add responsiveness to the website and make it more functional.
@Spyware007 please assign this issue to me under Gssoc23

Thank you!
