### ISSUE TITLE
[Add] <Search Bar>

### ISSUE THREAD

**Issue by Harshu467** [Spyware007/Animating-Buttons#1755]
### Details

We can add Search Bar to find buttons, I am Adding Sample Search Bar

### Screenshots

![Screenshot from 2023-07-06 22-28-18](https://github.com/Spyware007/Animating-Buttons/assets/89975347/64cbefd2-6204-4741-ab5d-368ef36ed7a0)
![image](https://github.com/Spyware007/Animating-Buttons/assets/89975347/8761f0bd-8eeb-4740-aa1d-87937f789404)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Souravvmishra** [comment]
We're not planning this
