### ISSUE TITLE
[Fix] Change About Us Text

### ISSUE THREAD

**Issue by Sriparno08** [Spyware007/Animating-Buttons#1760]
### Details

In the below section, the name 'Amazing Buttons Animation' can be changed to 'Animating Buttons' as this is the current name of the project.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/89148144/da788655-4585-40ce-b75f-4fc1db545770)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [X] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Souravvmishra** [comment]
Go Ahead
