### ISSUE TITLE
Add a new animated button 

### ISSUE THREAD

**Issue by ishaan203** [Spyware007/Animating-Buttons#1771]
### Details

Add a 3-D animated button with multi-color scheme .

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by shan0720-creator** [comment]
I would like to work on this project . Please assign this to me under Gssoc 23
