### ISSUE TITLE
[Add]  Engaging Upload Button with Interactive Elements

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1780]
### Details

I am proposing the addition of an upload button with a visually appealing design and interactive features. The button will be colored blue, creating a vibrant and attention-grabbing appearance. It will have an arrow pointing upwards, symbolizing the action of uploading files, accompanied by the text 'Upload' to provide clear functionality.

To enhance user engagement, upon hovering over the button, a dynamic animation will unfold. On the left side of the button, a rocket will come into view, representing the fast and efficient upload process. The rocket will fly with impressive speed for a brief moment, adding an element of excitement to the user experience. After a second, the rocket will gracefully fly away, creating a sense of completion.

Additionally, a message will be displayed on the button, replacing the 'Upload' text, which will read 'DONE!'. 

### Screenshots

![uploadbutton1 1](https://github.com/Spyware007/Animating-Buttons/assets/101655716/03ebafba-22c4-4182-9d6b-a0ffb1350c7b)
![upload5](https://github.com/Spyware007/Animating-Buttons/assets/101655716/09c22c50-5ffc-4d56-8e26-a4e7c10fd45b)
![uploadbutton1](https://github.com/Spyware007/Animating-Buttons/assets/101655716/9bb351cf-a70e-4228-a92d-8cf81d64771f)
![uploadbutton4](https://github.com/Spyware007/Animating-Buttons/assets/101655716/08d30647-1091-4b24-bf94-1e8643f52ffb)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Nishusk** [comment]
Please assign this issue to me under GSSoC'23.

**Comment by shan0720-creator** [comment]
Please assign this issue to me under GSSoC'23.
