### ISSUE TITLE
[Add] New Click Me Animated Button 

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1783]
### Details

The feature involves adding a "Click Me" button with interactive elements. When a user hovers over the button, a processing animation will start, featuring three dots that move sequentially. After approximately one second, a success message will appear, accompanied by a tick sign (✓), indicating a successful action.

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/101655716/89388860-5ddf-4fb8-98ec-c0524649444c

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by shan0720-creator** [comment]
I would like to work on this project . please assign it to me
