### ISSUE TITLE
[Add] Small section for displaying the buttons on hover.

### ISSUE THREAD

**Issue by PiyushK79** [Spyware007/Animating-Buttons#1785]
### Details

The download and show buttons cover up the whole image when hovered. 

Enhancement - I would allocate only a small space on hover to display for what the buttons are so that the whole image does not gets covered up.

@Spyware007 Please assign this issue to me under Gssoc23.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/100259650/7f605cdd-ce23-465b-b2c0-ccb53a180004)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Souravvmishra** [comment]
you can work on this @PiyushK79

**Comment by Souravvmishra** [comment]
If possibel, make it cover the full button.

**Comment by PiyushK79** [comment]
My idea was to make the hover state cover only a less part so that it is always possible for the user to see the button anytime, as covering it full will lead to hiding of the button on hover state.

**Comment by Spyware007** [comment]
@PiyushK79 Any updates on this issue?

**Comment by PiyushK79** [comment]
I have created the pull request.

**Comment by TANYA-CHAN** [comment]
🎉 The GSSOC'23 program has reached its conclusion, prompting us to officially close all pull requests (PRs) and issues. We extend a heartfelt thank you for your amazing contributions! 🙌 Keep the coding spirit alive with the same enthusiasm, and may luck 🍀 favor you in all your future coding adventures!
