### ISSUE TITLE
[Add] Facebook link in the footer

### ISSUE THREAD

**Issue by blindaks** [Spyware007/Animating-Buttons#1789]
### Details

I want to add Facebook with the other socials in the footer section.

### Screenshots

![Screenshot (47)](https://github.com/Spyware007/Animating-Buttons/assets/128223364/cd50894f-5ee0-4d11-a47d-fc4595ab5d51)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by blindaks** [comment]
@Spyware007 Please assign this issue to me under GSSOC'23.

**Comment by Souravvmishra** [comment]
Do You Know Our Facebook?
