### ISSUE TITLE
[Add] New order food button

### ISSUE THREAD

**Issue by Palakkgoyal** [Spyware007/Animating-Buttons#1793]
### Details

This button has a pink neon color and a shadow animation effect when clicked. It throws out food items whenever clicked like confetti.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Palakkgoyal** [comment]
Hey @Souravvmishra You haven't merged my PR?

**Comment by Souravvmishra** [comment]
Adding a new button doesn't require PR. You can do it using the website
