### ISSUE TITLE
[Docs] Adding a small Licenses section to the readme and a MIT Licenses badge

### ISSUE THREAD

**Issue by 1Shubham7** [Spyware007/Animating-Buttons#1794]
### Details

The readme file of the repo should have a Licenses section to make it more professional. I can add a licenses Section with a MIT License badge.

### Screenshots

![afters](https://github.com/Spyware007/Animating-Buttons/assets/116020663/9248a91e-0218-4439-be2f-6af31dd6e844)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [X] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by Ishita-Trivedi** [comment]
I want to work on this issue, please assign me this issue.

**Comment by Spyware007** [comment]
Readme.md is currently being updated by me.
So closing this as not planned.
