### ISSUE TITLE
[Add] Responsiveness for all Screens

### ISSUE THREAD

**Issue by 0rigin-c0de** [Spyware007/Animating-Buttons#1808]
### Details

This website is awesome but it is not responsive to mobile screens. I check this at 360px on a mobile device but it looks like the "screenshot I shared below"

### Screenshots

![Screenshot 2023-07-15 112547](https://github.com/Spyware007/Animating-Buttons/assets/106311923/3003c6e0-6e42-48cb-93c8-317cdd6e2cea)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by avinasdube** [comment]
Assign me. I can do it.

**Comment by 0rigin-c0de** [comment]
@avinasdube Actually I want to work on this bro
@Spyware007 can you assign it to me under GSSoc'23 i want to work on this

**Comment by avinasdube** [comment]
> @avinasdube Actually I want to work on this bro @Spyware007 can you assign it to me under GSSoc'23 i want to work on this

okay. i misunderstood you as maintainer/owner of this repo.
