### ISSUE TITLE
[Add] Social Share Button

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1811]
### Details

The proposed addition is to implement a new social share button that has a unique structure and displays all the social media icons for sharing when hovered upon.
On hover, a hidden panel containing various social media icons will be revealed, allowing users to easily share the content on their preferred social platforms.

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/101655716/aba96767-52ba-431e-ad67-2634244ccf75

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Nevish-302** [comment]
@Nishusk has this issue been assigned?
