### ISSUE TITLE
[Add] animated button for games purpose 

### ISSUE THREAD

**Issue by harshita-2003** [Spyware007/Animating-Buttons#1820]
### Details

a button can be used for any purpose but i did specifically adding in raw form for games 

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by harshita-2003** [comment]
@Souravvmishra the PR linked with this issue has not been merged . can you please do that .

**Comment by Souravvmishra** [comment]
We're no longer accepting PRs for Adding New Buttons.

**Comment by harshita-2003** [comment]
OH it was generated 2 weeks before  , but its Okay

**Comment by Souravvmishra** [comment]
Apologies For The Same. We were having a deep debate over this topic for a long time. But we can't just accept them because of obvious reasons.
