### ISSUE TITLE
[Add] Make card and hover effect

### ISSUE THREAD

**Issue by BhartiNagpure** [Spyware007/Animating-Buttons#1839]
### Details

I would like to make card for each of contributors and want to apply hover effect.
In card we can also add their commits below the name.

### Screenshots
![Screenshot 2023-07-19 134140](https://github.com/Spyware007/Animating-Buttons/assets/104631882/810673cc-d65f-4e9e-bd91-54c3749f9edd)

_No response_

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Souravvmishra** [comment]
Currently we're not planning this. THANK YOU for your kind efforts
