### ISSUE TITLE
[BUG]: About section of User is not visible on Light Mode 🪲 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [Spyware007/Animating-Buttons#1843]
## Description
- The bug is found on the profile section where we can explore a user's button components.
- The about text is just having an improper color for Light Mode.

## Screenshot

![Screenshot 2023-07-19 at 20-28-01 Animated Buttons](https://github.com/Spyware007/Animating-Buttons/assets/92252895/e3ac54ee-06ed-4865-8501-d74f076fb36a)

**Comment by 0xabdulkhalid** [comment]
Hey there @Spyware007, @Souravvmishra, @TANYA-CHAN, @PoorviShetty 👋🏻

Please make sure to assign this issue to me as soon possible so that i can make the work done!

Thank you.

**Comment by Souravvmishra** [comment]
it seems to be working fine buddy
