### ISSUE TITLE
[Add] Add search bar

### ISSUE THREAD

**Issue by sumitkr2000** [Spyware007/Animating-Buttons#1845]
### Details

Hey, @Spyware007 I want to add a research bar so that users can find buttons easily. Please assign me this issue. Thank you!

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Souravvmishra** [comment]
please share the algorithm for searching the button

**Comment by sumitkr2000** [comment]
same that you were using in the previous website @Souravvmishra

**Comment by Souravvmishra** [comment]
That was not very good in functioning. Can you please share the logic you'll be using.
