### ISSUE TITLE
Improving Loading and Working

### ISSUE THREAD

**Issue by parasss19** [Spyware007/Animating-Buttons#1867]
## Currently
- The images on the website are taking time to load as they are in png/jpeg format.
- I will convert it into webp format
### Smaller File Size :
- WebP images typically have a smaller file size compared to PNG images while maintaining similar image quality. This results in faster webpage loading times, reduced bandwidth usage, and improved overall user experience.
### Wide Browser Support:
- WebP is supported by major web browsers, including Google Chrome, Opera, and Microsoft Edge. Additionally, popular image editing software like Adobe Photoshop and GIMP provide WebP support, making it easy to work with these files.
### Faster Image Loading:
- With smaller file sizes, WebP images can be downloaded faster by website visitors. This leads to quicker rendering of images on the page, resulting in a better user experience.
### Bandwidth Savings:
- The reduced file size of WebP images means less data needs to be transferred between the server and the user's device. This can be particularly advantageous for websites with a large number of images or for users on limited bandwidth connections.

**Comment by parasss19** [comment]
Hey @TANYA-CHAN Please review it

**Comment by parasss19** [comment]
> Can You Show The Images, Youre Talking About Along With Their Sizes and reduced size (as in webp).

I am able to show the loading time after completing the issue only so please assigned me

**Comment by parasss19** [comment]
Hey @Souravvmishra 
- I can show you my previous PR result

## 1 Image Loading time difference
- Original
<img width="957" alt="Screenshot 2023-07-15 231933" src="https://github.com/Opentek-Org/opentek/assets/101205226/d7d54450-00d7-45c8-b449-e85fdd16e7fb">

- Updated
<img width="955" alt="Screenshot 2023-07-15 231953" src="https://github.com/Opentek-Org/opentek/assets/101205226/14251263-1d54-4c38-8ed7-ca65348e75eb">

**Comment by Souravvmishra** [comment]
Even Though It Doesn't Look Like a Great Difference. You Can Work On This. Also The Main Images In Our Site Sizes 2Mb. Make Sure To Fix That In Particular.

**Comment by Souravvmishra** [comment]
Any Update ?

**Comment by parasss19** [comment]
> Any Update ?

Yeah working actually i am busy in my college stuffs will submit PR today
