### ISSUE TITLE
Create Issue Template form Scratch

### ISSUE THREAD

**Issue by parasss19** [Spyware007/Animating-Buttons#1868]
## Currently
- There are no issue template right now.
- It will be difficult for contributor to create issue for bug ,feature and documentation
- It is also difficult for Project admin to separate the issues as there are no separate issue template for bugs, feature and documentation

## Changes
- I will create all the issue template  form scratch
- I will create all the issues template in .yml format file
- I will also add proper drop down menu and checkboxes

### 1
<img width="880" alt="Screenshot 2023-06-20 232906" src="https://github.com/Spyware007/Animating-Buttons/assets/101205226/a419738e-521c-4931-a84c-2d3b46bbe224">

### 2
<img width="719" alt="Screenshot 2023-07-23 232857" src="https://github.com/Spyware007/Animating-Buttons/assets/101205226/a31b684f-b6a2-4bf0-8e9a-6090e9dae7c9">

### 3
<img width="632" alt="Screenshot 2023-07-13 190743" src="https://github.com/Spyware007/Animating-Buttons/assets/101205226/f9c417ca-c1cc-4dc0-a57e-64366c6af5da">

**Comment by parasss19** [comment]
Hey @TANYA-CHAN Please review it

**Comment by Souravvmishra** [comment]
Not Planned For Now
