### ISSUE TITLE
[Add] Create a separate contributors page

### ISSUE THREAD

**Issue by karthiknadar1204** [Spyware007/Animating-Buttons#1880]
### Details

Currently, in the About page, it is displaying a few top contributors, I propose to create a separate contributors page using the github API routed on the navbar, the contributors would be distributed into cards, each card shall have the contributors card, the number of contributions to the project and a button to view their profile, the cards and the button shall have engaging hover effects and shall dynamically change between the light and the dark theme.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Souravvmishra** [comment]
we are not in planning this right now
