### ISSUE TITLE
[Add] improve the light and dark button on the navbar

### ISSUE THREAD

**Issue by karthiknadar1204** [Spyware007/Animating-Buttons#1881]
### Details

I propose replacing the current light and dark mode buttons with a toggle switch with the same signs, I think it would look more engaging.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by karthiknadar1204** [comment]
I owuld like to work on this issue under gssoc'23

**Comment by Souravvmishra** [comment]
any preview?

**Comment by karthiknadar1204** [comment]
<img width="152" alt="Screenshot 2023-07-28 at 5 16 46 AM" src="https://github.com/Spyware007/Animating-Buttons/assets/95973644/1a524347-3b3d-4f4d-bb71-794389285d91">
<img width="140" alt="Screenshot 2023-07-28 at 5 16 52 AM" src="https://github.com/Spyware007/Animating-Buttons/assets/95973644/8d506482-6449-42eb-a0d5-04531a803af5">




A switch like the above

**Comment by karthiknadar1204** [comment]
@Souravvmishra What do you think

**Comment by Souravvmishra** [comment]
We're good with the current one

**Comment by karthiknadar1204** [comment]
@Souravvmishra Is there anything else that can be worked upon, like you guys have stopped accepting any button contributions so like what can we do to contribute now because the three issues I though would be substantial to the project have been closed as unplanned so please suggest something I can do from side
