### ISSUE TITLE
[Add] Add improved procedure along with additional shell commands to the readme

### ISSUE THREAD

**Issue by karthiknadar1204** [Spyware007/Animating-Buttons#1882]
### Details

The contributing.md file looks terribly messy with all the commands piled up one on top of the other, I propose to make it more streamlined with better placement for the shell commands to make it easier for even the newcomers to read and understand the setup of the project.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [X] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by Souravvmishra** [comment]
This will take some time to get assigned
