### ISSUE TITLE
[Docs] - Adding a socials section and badges to that section in the readme  

### ISSUE THREAD

**Issue by 1Shubham7** [Spyware007/Animating-Buttons#1895]
### Details

We should have a socials section in the readme. Example -

![image](https://github.com/NageshMandal/Engineering-Notes-Website/assets/116020663/be1693e2-2172-4b6a-9237-810d7082600e)

This would help you improve your project react and your social media profile as well.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [X] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by Souravvmishra** [comment]
@Spyware007
