### ISSUE TITLE
[BUG]: IMPROPER ALIGNMENT OF ELEMENTS ON CONTRIBUTORS SECTION 🪲

### ISSUE THREAD

**Issue by 0xabdulkhalid** [Spyware007/Animating-Buttons#1905]
### Details

- The contributor's profile image and their names are improperly aligned.
- This creates a bad impression in terms of User Interface, We need to fix this as soon as possible.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/92252895/f5a581a7-8334-46fe-9331-b9fddcf3ce8d)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by 0xabdulkhalid** [comment]
Hey there @Souravvmishra 👋🏻 

Make sure to assign this issue to me to make the work done, Thank you!

**Comment by Souravvmishra** [comment]
Go Ahead Bro
