### ISSUE TITLE
[Add]: ISSUE TEMPLATE FOR BUG 🪲 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [Spyware007/Animating-Buttons#1908]
### Details

- As part of our efforts to streamline the bug reporting process and ensure clear and concise bug reports, we propose adding a standardized "Bug Report" template for GitHub issues. 
- Currently the Issue template of this repository is not clear to manage these types of details in it.
- This template will provide a structured format for users to report bugs they encounter while using our project.
- The bug report template will include sections such as "Bug Description," "Steps to Reproduce," "Expected Behavior," "Screenshots (if applicable)," "Environment (if applicable)," and "Additional Context."
- By using this template, we can gather consistent and comprehensive bug reports, enabling our team to identify and resolve issues more efficiently.
- The template will encourage users to provide essential details, making it easier to reproduce bugs and find appropriate solutions.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/92252895/fc3b9bec-e8bd-47d3-9a52-a5efed10e273)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by 0xabdulkhalid** [comment]
Hey there @Souravvmishra 👋🏻 

Please make sure to assign this issue to me to make the work done, Thank you!

**Comment by Souravvmishra** [comment]
@Spyware007
