### ISSUE TITLE
[Add]: ISSUE TEMPLATE FOR ADDING NEW FEATURE 💡✨ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [Spyware007/Animating-Buttons#1909]
### Details

- This issue template is designed to streamline the process of requesting new features for our project. 
- If you have an idea for an exciting new functionality or improvement, please use this template to provide the necessary details and context for the feature request.
- The current issue template has not designed to gather more details about new features, We want to add seperate issue templates So that the contributor can create a concise issue.

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/92252895/856d73fe-1015-48c9-a375-acdef10eab1f)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by 0xabdulkhalid** [comment]
Hey there @Souravvmishra 👋🏻 

Please make sure to assign this issue to me to make the work done, Thank you!

**Comment by TANYA-CHAN** [comment]
🎉 The GSSOC'23 program has reached its conclusion, prompting us to officially close all pull requests (PRs) and issues. We extend a heartfelt thank you for your amazing contributions! 🙌 Keep the coding spirit alive with the same enthusiasm, and may luck 🍀 favor you in all your future coding adventures!
