### ISSUE TITLE
[Add] <made a new button which has loding animation on clicking>

### ISSUE THREAD

**Issue by abansal15** [Spyware007/Animating-Buttons#1916]
### Details

![image](https://github.com/Spyware007/Animating-Buttons/assets/120590200/367ede39-6a90-446d-b587-140ab9931925)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by abansal15** [comment]
please assign it to me

**Comment by Souravvmishra** [comment]
We no longer accept PRs for new buttons
