### ISSUE TITLE
[Add] <made new download button >

### ISSUE THREAD

**Issue by abansal15** [Spyware007/Animating-Buttons#1917]
### Details

![image](https://github.com/Spyware007/Animating-Buttons/assets/120590200/a0ec3ee0-e39d-4313-ace2-e4bbeaf8e01a)
on clicking
![image](https://github.com/Spyware007/Animating-Buttons/assets/120590200/291048d4-d7ac-4de5-ab69-ca0027f6106a)
after downloaded
![image](https://github.com/Spyware007/Animating-Buttons/assets/120590200/7c7f5a51-37e6-416b-b3b4-4cf8133de73d)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by abansal15** [comment]
has full animation

**Comment by abansal15** [comment]
please assign it to me

**Comment by abansal15** [comment]
https://github.com/Spyware007/Animating-Buttons/assets/120590200/01ba1e43-f4c5-4c09-9c86-0bc2ae0d4acf

**Comment by Souravvmishra** [comment]
Bro It Hardly Take a sec to download the zip file. Will it dynamically adjust for it?

**Comment by abansal15** [comment]
> Bro It Hardly Take a sec to download the zip file. Will it dynamically adjust for it?

i will reduce the time for the animation

**Comment by abansal15** [comment]
i will reduce the time for the downloading part please assign it to me

**Comment by Souravvmishra** [comment]
Bro The Animation Is Taking more than 10 seconds. 

Sorry But We can't Accept It
