### ISSUE TITLE
[BUG]: Noticed Same Title Text -Tooltip existed on Social Icons🐞

### ISSUE THREAD

**Issue by NarendraKoya999** [Spyware007/Animating-Buttons#1919]
### Details

- `In Footer Section Area, This Text Instagram (External Link) Commonly existed on 4 Social Icons`

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Souravvmishra** [comment]
Can you elaborate it

**Comment by NarendraKoya999** [comment]
> Can you elaborate it 
> 

Sure @Souravvmishra . In footer section, 4 different social icons there.But, When hovering on 4 different social icons, Same Tooltip commonly appeared like Instagram (External Link).So, I want to rectify that Bug.That's it

**Comment by Souravvmishra** [comment]
Share SS @NarendraKoya999

**Comment by NarendraKoya999** [comment]
> Share SS @NarendraKoya999 

![IMG_20230801_224955.jpg](https://github.com/Spyware007/Animating-Buttons/assets/84512164/be27d1e8-8787-4a2f-8b0e-fb9c7c38e508)

Observe this Footer Screenshot. When hovering on any these 4 Icons, Similar Tooltip Text Appeared.The text name is Instagram (External Link).

**Comment by Souravvmishra** [comment]
You can Work on this
