### ISSUE TITLE
[Add]: Noticed styles.yml File needs for Enhancement Related Requests and Changes Separately in ISSUE TEMPLATES

### ISSUE THREAD

**Issue by NarendraKoya999** [Spyware007/Animating-Buttons#1930]
### Detailed Description:
**style.yml (Custom ISSUE_TEMPLATE):**
- The style.yml file, on the other hand, serves as a custom ISSUE_TEMPLATE for issues related to coding style, code formatting, and linting rules within your GitHub repository. This template helps contributors or users report code style-related concerns or seek guidance on adhering to the project's coding standards.
- The contents of style.yml might include specific questions or prompts related to coding style, requesting users to provide examples of code snippets that need formatting adjustments or explanation. Additionally, you might include instructions on how to check code against the project's style guidelines and best practices.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by NarendraKoya999** [comment]
Hi @Souravvmishra . Please review on this Issue.

**Comment by Spyware007** [comment]
@NarendraKoya999 
What are you going to add in the styles.yml file?

**Comment by NarendraKoya999** [comment]
> @NarendraKoya999 What are you going to add in the styles.yml file?
This styles.yml template is tailored to gather information about enhancement suggestions for code style and styling. Users and contributors can provide detailed descriptions of the changes they propose, code examples, and the reasoning behind their suggestions. The template encourages a well-structured and comprehensive approach to enhancement requests, making it easier for your team to review and consider these improvements effectively.

**Comment by TANYA-CHAN** [comment]
🎉 The GSSOC'23 program has reached its conclusion, prompting us to officially close all pull requests (PRs) and issues. We extend a heartfelt thank you for your amazing contributions! 🙌 Keep the coding spirit alive with the same enthusiasm, and may luck 🍀 favor you in all your future coding adventures!
