### ISSUE TITLE
[Feature]: Update dependabot.yml for Json file

### ISSUE THREAD

**Issue by aparna03dubey** [Spyware007/Animating-Buttons#1939]
### Details

The repo only contain dependabot.yml for npm. Since it also contains Json files, it also needs to be updated.

### Screenshots

![Screenshot_2](https://github.com/Spyware007/Animating-Buttons/assets/101944716/e0374501-bb51-49a5-9fb5-b4ec3b9617c1)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [X] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [ ] I am a GSSoC'23 contributor

**Comment by Souravvmishra** [comment]
What would that do ?

**Comment by aparna03dubey** [comment]
Updates the configurations for different package ecosystems, here JSON

**Comment by TANYA-CHAN** [comment]
🎉 The GSSOC'23 program has reached its conclusion, prompting us to officially close all pull requests (PRs) and issues. We extend a heartfelt thank you for your amazing contributions! 🙌 Keep the coding spirit alive with the same enthusiasm, and may luck 🍀 favor you in all your future coding adventures!
