### ISSUE TITLE
[Add] Replace old Twitter logo with new X logo

### ISSUE THREAD

**Issue by varunlmxd** [Spyware007/Animating-Buttons#1959]
### Details

Replacement of old Twitter logo with the new X logo

### Type of Contribution

- [X] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by motuncoded** [comment]
Assign me this issue
