### ISSUE TITLE
Improve Navbar

### ISSUE THREAD

**Issue by AnushkaKohli** [Spyware007/Animating-Buttons#1960]
### Details

**Describe the bug**
Currently, the navbar of the website is not as attractive to the eyes as the rest of the website. It is not separated from the home page and is not sticky.

**Expected behavior**
I would like to make changes in the UI of the navbar as well as work on the sticky nature of the navbar so it sticks even when you scroll down.

**Additional context (optional )**
Please assign me the issue.

### Screenshots

<img width="947" alt="image" src="https://github.com/Spyware007/Animating-Buttons/assets/102284552/f4f6bffd-bc15-4a87-9024-3d4a5e900b64">

<img width="947" alt="image" src="https://github.com/Spyware007/Animating-Buttons/assets/102284552/fc350275-73a2-4618-9855-491333a53ed9">

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by TANYA-CHAN** [comment]
🎉 The GSSOC'23 program has reached its conclusion, prompting us to officially close all pull requests (PRs) and issues. We extend a heartfelt thank you for your amazing contributions! 🙌 Keep the coding spirit alive with the same enthusiasm, and may luck 🍀 favor you in all your future coding adventures!
