### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by AnushkaKohli** [Spyware007/Animating-Buttons#1961]
### Details

I have gone through the entire website and the codebase to understand the work done in this repository. This needs to be documented.

The readme is empty right now. I would like to update the readme and document everything about the website.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [X] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
@AnushkaKohli Please dm me on discord to discuss further on Readme.md.

**Comment by AnushkaKohli** [comment]
@Spyware007 Sure! Could you please send me your discord username?

**Comment by Spyware007** [comment]
@AnushkaKohli 
![Screenshot_2023-08-07-01-31-55-05_572064f74bd5f9fa804b05334aa4f912.jpg](https://github.com/Spyware007/Animating-Buttons/assets/89961974/cf906638-b4ae-4d81-bbe2-11b8f5c63b8d)

**Comment by AnushkaKohli** [comment]
@Spyware007 hey, please check your dm on discord. i've pinged you there
