### ISSUE TITLE
[Add]: Convert svg, png Images File Format into webp Files Format 🌟🌟

### ISSUE THREAD

**Issue by NarendraKoya999** [Spyware007/Animating-Buttons#1967]
### Purpose
- **WebP is a modern image format that provides superior lossless and lossy compression for images on the web. Using WebP, webmasters and web developers can create smaller, richer images that make the web faster. WebP lossless images are 26% smaller in size compared to PNGs.**
- **I have Taken One of Image File in Your Project Directory. See What Happens and Observe in Screenshots.**
- **I want to work on those changes in Both Project Files Directory and Respective Files Directory Also.**

### Before Conversion

![animating-buttons-1](https://github.com/Spyware007/Animating-Buttons/assets/84512164/39b51c67-f395-49e7-b1ec-441d927ecf89)

### After Conversion
![animating-buttons-2](https://github.com/Spyware007/Animating-Buttons/assets/84512164/3abcffef-9517-4953-ab27-98e5addf7790)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Souravvmishra** [comment]
The Checkbox are not just for formalities

**Comment by NarendraKoya999** [comment]
> The Checkbox are not just for formalities 

Any reason for this is not accepted.Please

**Comment by NarendraKoya999** [comment]
> > The Checkbox are not just for formalities 
> 
> Any reason for this is not accepted.Please Tell me @Souravvmishra
