### ISSUE TITLE
[Add] Spelling mistake in UI of alert

### ISSUE THREAD

**Issue by soubhik-111** [Spyware007/Animating-Buttons#1968]
### Details

Here it is mention "loggin" but it must be "login"

### Screenshots

![image](https://github.com/Spyware007/Animating-Buttons/assets/90599826/78cd1f51-4d9a-4369-95cf-09ab57afa6d2)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
@soubhik-111 
We are fixing it and changing it to react hot-toast!

**Comment by soubhik-111** [comment]
@Spyware007 
Shall I do it ?

**Comment by Souravvmishra** [comment]
@soubhik-111 Check #1963
