### ISSUE TITLE
[Add] Change the alert.

### ISSUE THREAD

**Issue by soubhik-111** [Spyware007/Animating-Buttons#1969]
### Details

I want to change the UI of alert 
which is showing on failing log in.

### Screenshots

Current:
![image](https://github.com/Spyware007/Animating-Buttons/assets/90599826/e5af89cd-6095-4712-9cee-4a05d4917e30)

Expected:
![image](https://github.com/Spyware007/Animating-Buttons/assets/90599826/420c7645-650d-4199-9c38-2639abf9dac0)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
@soubhik-111 We are using a different library.
So as considering our UI we had decided to use that toast.
Closing this as not required
