### ISSUE TITLE
[Feature] Contributors

### ISSUE THREAD

**Issue by Bashamega** [Spyware007/Animating-Buttons#1970]
### Details

Hello:)
When you got to the contributors section in the [about page](https://lets-animate-btns.vercel.app/about). It is not up to date.

### Screenshots

Website:
![image](https://github.com/Spyware007/Animating-Buttons/assets/110662505/b550b8fa-5fc1-4e58-a206-e0c630885c41)
Real contributors
![image](https://github.com/Spyware007/Animating-Buttons/assets/110662505/71b7b325-2dd2-4755-929f-dd98088b16d6)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [X] Resolving a bug
- [x ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [ ] I am a GSSoC'23 contributor

**Comment by Bashamega** [comment]
I can create it by fetch ing it from the [github api](api.github.com)

**Comment by Spyware007** [comment]
@Bashamega That section and the contributors are selected by me.
Those are the person who had done a major change or something major in the project.
That's why those data were hardcoded.
I don't want to show all the contributors.
Closing this as not planned.
