### ISSUE TITLE
[Add] New Click Me Animated Button 

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#1973]
### Details

I would like to add a 'Click Me' button that offers an engaging and delightful user experience.
 When users hover over the button, a small, colorful celebration emerges, evoking a sense of joy and excitement. 
The celebration includes dynamic animated elements like confetti or other festive graphics that briefly fill the screen.
 Accompanied by a message of success and a green tick symbol, symbolizing achievement, this delightful animation provides positive feedback to users.
 After a short duration, the celebration effect gracefully fades away, leaving the button ready to delight users with the next joyful interaction."

### Screenshots

https://github.com/Spyware007/Animating-Buttons/assets/101655716/fa281da8-8ab9-4e78-b78f-f83bcd966087

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Nishusk** [comment]
Please assign this issue to me under GSSoC'23.

**Comment by TANYA-CHAN** [comment]
🎉 The GSSOC'23 program has reached its conclusion, prompting us to officially close all pull requests (PRs) and issues. We extend a heartfelt thank you for your amazing contributions! 🙌 Keep the coding spirit alive with the same enthusiasm, and may luck 🍀 favor you in all your future coding adventures!
