### ISSUE TITLE
[Add] Want to add our Contributor page in the website.

### ISSUE THREAD

**Issue by HimanshuNarware** [Spyware007/Animating-Buttons#1976]
### Details

Is your feature request related to a problem? Please describe.
Our Contributors page in the website
Describe the solution you'd like
We can add a Contributors page in the website. which is shows the name and the profile image of the contributor.and the number of commits is done by the contributor

### Type of Contribution

- [X] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [X] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by TANYA-CHAN** [comment]
🎉 The GSSOC'23 program has reached its conclusion, prompting us to officially close all pull requests (PRs) and issues. We extend a heartfelt thank you for your amazing contributions! 🙌 Keep the coding spirit alive with the same enthusiasm, and may luck 🍀 favor you in all your future coding adventures!
