### ISSUE TITLE
[Add] :  Custom CSS Variable Definition for Hover Effect in zul132_1(style.css file)

### ISSUE THREAD

**Issue by tamannaaaaa** [Spyware007/Animating-Buttons#1978]
### Details

In the provided CSS code, there is a missing custom CSS variable (--clr) definition, which results in an issue with the hover effect on anchor (<a>) elements. The a:hover rule uses var(--clr) for background and box-shadow properties, but the variable --clr is not defined anywhere in the code. As a result, the hover effect will not work correctly, and the background and box-shadow properties will not change as intended.

### Type of Contribution

- [X] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by TANYA-CHAN** [comment]
🎉 The GSSOC'23 program has reached its conclusion, prompting us to officially close all pull requests (PRs) and issues. We extend a heartfelt thank you for your amazing contributions! 🙌 Keep the coding spirit alive with the same enthusiasm, and may luck 🍀 favor you in all your future coding adventures!
