### ISSUE TITLE
[Add] Buy me a coffee button

### ISSUE THREAD

**Issue by Manishak798** [Spyware007/Animating-Buttons#1985]
### Details

I want to add a new button with animation that button will buy me a coffee button that can be used in readme or websites.
I am willing to add this button to this project kindly assign this to me under GSSOC23.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [x] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Manishak798** [comment]
Hey @Spyware007 I am planning to do this and I will also add animations to it.
![image](https://github.com/Spyware007/Animating-Buttons/assets/90680330/2268cac4-53e0-4fab-ad9e-5179f8791c34)

**Comment by Manishak798** [comment]
Hey, @Spyware007 Let me know your views on the same.

**Comment by TANYA-CHAN** [comment]
🎉 The GSSOC'23 program has reached its conclusion, prompting us to officially close all pull requests (PRs) and issues. We extend a heartfelt thank you for your amazing contributions! 🙌 Keep the coding spirit alive with the same enthusiasm, and may luck 🍀 favor you in all your future coding adventures!
