### ISSUE TITLE
I want to Add a New Button

### ISSUE THREAD

**Issue by Sudhanshu-Sharma-22** [Spyware007/Animating-Buttons#2019]
### Details

I Want To a New Button to Animating-Buttons.
It's my Personally Customised Button. :).

### Type of Contribution

- [ ] Update to an existing Animated Button
- [X] Adding a new Button
- [ ] Resolving a bug
- [ ] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
@Sudhanshu-Sharma-22 Hello you can add a new button from the website directly!
