### ISSUE TITLE
Functionality to download the html and css code directly of the respective buttons. 🤔

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#26]
Need some functionality to download the code directly into your local machine with ease.

**Comment by Nevish-302** [comment]
can I have a go at this?
please assign this to me...

**Comment by Spyware007** [comment]
Yes Sure.

**Comment by Spyware007** [comment]
Hey, @Nevish-302 What are the updates on this issue? 
I had assigned it to you.

**Comment by Nevish-302** [comment]
It's India so that was 3 o clock at night... I'm working on it not. Well get done shortly

**Comment by Nevish-302** [comment]
i have added this funtionality to one button tell me if i need to use another method or need to change the style.

**Comment by Spyware007** [comment]
@Nevish-302 It is amazing. 🚀
But can we download both files by clicking on just download button rather than downloading HTML and CSS files separately?
It will be a good user experience.

**Comment by Nevish-302** [comment]
I have modified it accordingly. Check it in my forked repository

**Comment by Spyware007** [comment]
I think there are some problems with the code I will strongly suggest you to recheck it. @Nevish-302

**Comment by Nevish-302** [comment]
I've fixed'em please recheck it

**Comment by Nevish-302** [comment]
@Spyware007 any updates?

**Comment by Spyware007** [comment]
@Nevish-302 Would you like to become a maintainer of this repository?
 Lets meet here. https://discord.gg/ZsMAyV6e

**Comment by Spyware007** [comment]
Merged.
