### ISSUE TITLE
add animation button using HTML & CSS

### ISSUE THREAD

**Issue by Pritam991** [Spyware007/Animating-Buttons#267]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

**Comment by Nishannaik** [comment]
I am interested to work on this issue.Can you assign it to me @Pritam991

**Comment by MSami625** [comment]
I want to also Contribute . Gssoc23..

**Comment by akshaykamath45** [comment]
I'm eager to contribute to the animated button issue in your project. I would like to know if there is a need for this task to be assigned, or if I can directly start working on it.

**Comment by divyanshiet** [comment]
Hello  @Pritam991 i would like to work on this issue. through Html CSS I would like to add new animating buttons with special effect in it. Kindly assign it to me

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by Spyware007** [comment]
@Nishannaik , @MSami625 , @akshaykamath45 , @divyanshiet , @UditSharma9999 you can start working on this by creating an issue mentioning this one.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/

**Comment by saiwali** [comment]
Hello, @Spyware007  can I start working on this issue too? I believe I can make a valuable contribution to this issue.

**Comment by sohil1234** [comment]
I am interested to work on this issue.Can you assign it to me @Spyware007

**Comment by Spyware007** [comment]
@pritma you can work on it! assigned to you!

As for others @sohil1234 , @saiwali  you can start working on this by creating an issue by proper mentioning.
