### ISSUE TITLE
Add a scroll to top button once the user has scrolled down after the socials link below the navbar GSSOC'23

### ISSUE THREAD

**Issue by karthiknadar1204** [Spyware007/Animating-Buttons#269]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [x] Documentation / README.md changes

**Details:**

Once the user has reached the bottom of the page,instead of manually scrolling back to the top of the page manually,we can add a small icon to the bottom right corner of the page which on getting clicked directs the user to the top of tha page

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by AishwaryVishwa** [comment]
Please assign this issue to me I can solve it under gssoc'23

**Comment by karthiknadar1204** [comment]
I am waiting for this issue to be assigned to me @AishwaryVishwa Could you please find other issues😃

**Comment by AishwaryVishwa** [comment]
@karthiknadar1204 Yeah let's left it to mentor whom he assign.

**Comment by prashant744** [comment]
I  can work on this issue under gssoc 23 contribution ?

**Comment by Spyware007** [comment]
@karthiknadar1204 I have assigned this to you.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/

**Comment by karthiknadar1204** [comment]
WIll submit pr for this issue by this weekend @Spyware007 
Thank you

**Comment by karthiknadar1204** [comment]
@Spyware007 Done with the issue, will raise a pr in a bit

**Comment by karthiknadar1204** [comment]
@Spyware007 Please add a level to the issue as well
Other issues had one so stated
