### ISSUE TITLE
Pagination Component [GSSoC-2023]

### ISSUE THREAD

**Issue by TusharUtane07** [Spyware007/Animating-Buttons#270]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ x] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I would like to add pagination component so that user can navigate easily. 
Please Assign me this issue under GSSoC 2023 I will fix this in future if there are 100's of buttons then it will not be good UX wise.

**Comment by Spyware007** [comment]
Hey, @TusharUtane07 that's an amazing issue.
I have assigned this to you!
Do your best!

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/

**Comment by vk20july** [comment]
I want to work on this issue under gssoc 23

**Comment by TusharUtane07** [comment]
@Spyware007 I have created a pull request for these Issue. Make sure to check that out and please let me know if I'm missing out on something.

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
