### ISSUE TITLE
Adding animation button 

### ISSUE THREAD

**Issue by harshsingh32** [Spyware007/Animating-Buttons#271]
**This is a(n):**

- [x ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I would like to add an animation button in the project.

**Comment by harshsingh32** [comment]
I would like to work on this issue, assign this issue to me under GSSoC'23.

**Comment by NehaShrama** [comment]
I would like to work on this issue. Please assign it to me under GSSoC'23.

**Comment by SONA-1111** [comment]
I want to add an animation button to the project.

**Comment by Spyware007** [comment]
@harshsingh32 It's assigned to you.

@NehaSharma101 and @SONA-1111 
you can create an issue similar to this and start working on the same, I will assigned that issue to respective ones.


Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/
