### ISSUE TITLE
Improving the readme file 

### ISSUE THREAD

**Issue by harshsingh32** [Spyware007/Animating-Buttons#272]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [x] Documentation / README.md changes

**Details:**

I would like to improve the readme file of this project and make it more expressive and engaging for the user.

**Comment by harshsingh32** [comment]
I would like to work on this issue, assign this issue to me under GSSoC'23.

**Comment by divyanshiet** [comment]
I would like to work on this issue. Kindly assign it to me...

**Comment by Spyware007** [comment]
@harshsingh32 You can work on this.
Just make separate PR for each of your contribution

@divyanshiet  Create another issue. I will assign it to you.
You can try making an animated button.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/

**Comment by GundaSudarrshan** [comment]
@harshsingh32  are you working on this right now , if not I request @Spyware007  to please assign  me this Issue 
as we are working in GSSOC event we need to change the readme file with relevant titles and links of GSSOC-23.
@Spyware007  can you look over it now ????

**Comment by harshsingh32** [comment]
I am working on this issue, would update.

**Comment by GundaSudarrshan** [comment]
what changes are you making @harshsingh32

**Comment by harshsingh32** [comment]
I would update and improve the readme and would provide you the update.

**Comment by harshsingh32** [comment]
I have made pr #351 under this issue.
