### ISSUE TITLE
Adding new button [GSSOC 2023 Contribution ]

### ISSUE THREAD

**Issue by ManishaSwain8** [Spyware007/Animating-Buttons#273]
Want to add new button to the collection , 
I would like to be assigned to this task under GSSOC 2023
Please do assign !

**This is a(n):**

- [x ] Update to an existing Animated Button
- [ x] Any Error
- [ x] Proposal to the Repository
- [ x] Documentation / README.md changes
-[ ] adding new button
**Details:**
Want to add new animated button the website to button collection

**Comment by iLakshya** [comment]
Please assign it to me

**Comment by Spyware007** [comment]
@ManishaSwain8 
Assigned to you. All the best.

@iLakshya You can create a similar issue and I will assign it to you.
Just make sure don't make similar buttons that are already present on the website.


Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/

**Comment by ManishaSwain8** [comment]
pushed the code .Do check it out.  :)
