### ISSUE TITLE
Adding a scroll to top button [GSSOC'23]

### ISSUE THREAD

**Issue by huzaifa9999** [Spyware007/Animating-Buttons#277]
A scroll to top button can be implemented in the website

**Comment by huzaifa9999** [comment]
Please assign me this issue under GSSOC'23

**Comment by karthiknadar1204** [comment]
@huzaifa9999 I have already opened a similar issue 6hours back issue #269

**Comment by Shaurya10101** [comment]
Please assign me this issue under GSSoC'23 . I'd give my best to fulfil your expectations

**Comment by iLakshya** [comment]
Please assign to me as a GSSoC '23 Contributor

**Comment by abcxyz31** [comment]
i can contribute to this pls assign me

**Comment by Spyware007** [comment]
A similar issue is already created and assigned to someone else.
@iLakshya @karthiknadar1204 @abcxyz31 @huzaifa9999 @Shaurya10101 

You can try creating another separate issue and start working.
