### ISSUE TITLE
Social Media Icons

### ISSUE THREAD

**Issue by 007xylogramori** [Spyware007/Animating-Buttons#279]
I would like to add social media icons , that would increase the look of the page
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
![image](https://github.com/Spyware007/Animating-Buttons/assets/119863801/cd041471-f062-47a8-a57b-4ce69a006aeb)

**Comment by Spyware007** [comment]
@007xylogramori Assigned to you.
Make sure it matches the UI.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/

**Comment by PoorviShetty** [comment]
@007xylogramori Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
