### ISSUE TITLE
Functionality to edit the button styles using react live. 😎

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#28]
Need a functionality to edit the styles of buttons.

**Comment by Nevish-302** [comment]
do you need to change all buttons on the webpage using the functionality? 
if yes, please assign this issue to me

**Comment by Nevish-302** [comment]
do you need to change all buttons on the webpage using the functionality? 
if yes, please assign this issue to me

**Comment by Spyware007** [comment]
Every button should have its unique page and then there should be some sort of functionality to change the button styles.
or
Implement a popup on every button that can be used to change styles.

@Nevish-302

**Comment by Manishgupta200** [comment]
I'm very interesting to solve this issue. Assign it to me.

**Comment by Spyware007** [comment]
@Manishgupta200  Assigned to you.

**Comment by Manishgupta200** [comment]
Can you please refer some docs or images. I would be better for understanding the issue clearly

**Comment by Spyware007** [comment]
Okay here is one example using Live Server. [Awesome Shapes](https://awesomeshapes.netlify.app/)  , [React-Live](https://react-live.netlify.app/) and 
DOCS -> [React Live](https://www.npmjs.com/package/react-live)

@Manishgupta200

**Comment by Spyware007** [comment]
@Manishgupta200  Any updates on this issue?

**Comment by Manishgupta200** [comment]
Ya i'm working on this.

**Comment by rbeaujon** [comment]
What kind of changes need to have the buttons? Can you give me more info to try to work on this ticket? Thank you

**Comment by vk20july** [comment]
sir @Spyware007 i want to work on this issue under gssoc 23

**Comment by Spyware007** [comment]
@vk20july Raise a PR for the issue I will assign and merge it to you.

**Comment by rafiya2003** [comment]
can you please assign me this issue under GSsoc'23

**Comment by vk20july** [comment]
> @vk20july Raise a PR for the issue I will assign and merge it to you.

ok sir
