### ISSUE TITLE
Homepage Design Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [Spyware007/Animating-Buttons#281]
The homepage interface is really nice but it can be improved by making some design adjustments. Working on the design of the homepage, I would like to make it even better.

**Comment by iamRabia-N** [comment]
Output will be this like:

![web_pic](https://github.com/Spyware007/Animating-Buttons/assets/115794049/354972e5-50af-4504-ade2-036b40d9b22d)

**Comment by iamRabia-N** [comment]
I would like to work on this issue as a part of GSSOC-23.

**Comment by SakshiShah29** [comment]
I would like to work on this issue. Please assign it to me under GSSoC'23.

**Comment by Spyware007** [comment]
@iamRabia-N and @SakshiShah29 
Please share the designs that you want to implement on the homepage.
A better design will get assigned to this issue.
All the best.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/

**Comment by ruchagosavi** [comment]
I would like to work on this issue under GSSOC 2023 please assign me @Spyware007

**Comment by iamRabia-N** [comment]
Hi @Spyware007 !
I am working on the design.
Hopefully, will be completed by tomorrow evening.

**Comment by iamRabia-N** [comment]
Hi @Spyware007 !

Here is the updated design sample work:
### Homepage
![work](https://github.com/Spyware007/Animating-Buttons/assets/115794049/823e2361-7960-4844-9ec7-e209b107b728)

### Buttons Hover Effect
![work (4)](https://github.com/Spyware007/Animating-Buttons/assets/115794049/a4c895ad-3058-4695-b94a-ebdff8dd8273)
![work (3)](https://github.com/Spyware007/Animating-Buttons/assets/115794049/1206f0ff-222e-4ad0-b556-ec5af469b90e)
![work (2)](https://github.com/Spyware007/Animating-Buttons/assets/115794049/5ecd33e3-d8c4-42e2-ae68-043b9ac0fa9e)
![work (1)](https://github.com/Spyware007/Animating-Buttons/assets/115794049/50bef5da-542c-4304-a077-c8661397a6ee)

**Comment by iamRabia-N** [comment]
@Spyware007 

> Hi @Spyware007 !
> 
> Here is the updated design sample work:
> 
> ### Homepage
> ![work](https://user-images.githubusercontent.com/115794049/240567129-823e2361-7960-4844-9ec7-e209b107b728.png)
> 
> ### Buttons Hover Effect
> ![work (4)](https://user-images.githubusercontent.com/115794049/240567373-a4c895ad-3058-4695-b94a-ebdff8dd8273.png) ![work (3)](https://user-images.githubusercontent.com/115794049/240567397-1206f0ff-222e-4ad0-b556-ec5af469b90e.png) ![work (2)](https://user-images.githubusercontent.com/115794049/240567419-5ecd33e3-d8c4-42e2-ae68-043b9ac0fa9e.png) ![work (1)](https://user-images.githubusercontent.com/115794049/240567459-50bef5da-542c-4304-a077-c8661397a6ee.png)
