### ISSUE TITLE
Adding a new Button

### ISSUE THREAD

**Issue by An525ish** [Spyware007/Animating-Buttons#282]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

**Comment by trisharaj06** [comment]
Please assign this issue to me as gssoc contributor

**Comment by bibhanshu01** [comment]
I would like to work on this project as a GSSoC Contributor, kindly assign this to me.

**Comment by Spyware007** [comment]
@trisharaj06 Assigned to you.
You can start working on it.

@bibhanshu01 Create another issue, I will assign it to you.
Don't add similar buttons.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/
