### ISSUE TITLE
Add a new Download Button with Circular Progress Bar

### ISSUE THREAD

**Issue by Uma-95** [Spyware007/Animating-Buttons#284]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I would like to add a button similar to the below attached screenshot
![image](https://github.com/Spyware007/Animating-Buttons/assets/99042417/21412823-8bc8-4c12-9d6e-f96eaeb483e7)
![image](https://github.com/Spyware007/Animating-Buttons/assets/99042417/95b4be18-f10c-4931-b445-c2103fb0444f)
![image](https://github.com/Spyware007/Animating-Buttons/assets/99042417/287debf1-1e1e-4ba1-aa4e-bc666240f3b2)

**Comment by Uma-95** [comment]
I would to work on this issue as part of GSSOC'23 contribution.

**Comment by iLakshya** [comment]
Please assign to me as GSSoC'23 Contributor

**Comment by Spyware007** [comment]
@Uma-95 Assigned to you.
All the best.
@iLakshya You can work on another issue or create one.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/
