### ISSUE TITLE
Adding new button to the collection

### ISSUE THREAD

**Issue by Harshithardd** [Spyware007/Animating-Buttons#285]
I would like to add new button to the collection ,
Please do assign  to this task to me under GSSOC 2023 .

This is a(n):

[x ] Update to an existing Animated Button
[ x] Any Error
[ x] Proposal to the Repository
[ x] Documentation / README.md changes
-[ ] adding new button
Details:
Want to add new animated button to website button collection

**Comment by Spyware007** [comment]
@Harshithardd Assigned to you.
Start working on this.
All the best.

**Comment by PoorviShetty** [comment]
@Harshithardd Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
