### ISSUE TITLE
To add animated button using HTML and CSS

### ISSUE THREAD

**Issue by Candy505** [Spyware007/Animating-Buttons#286]
I'll also make sure to  fix broken buttons if I encounter any broken buttons. Kindly assign me this issue under GGSOC 2023.

**Comment by Spyware007** [comment]
Assigned to you @Candy505 
All the best.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/

**Comment by masked-wolf18** [comment]
Hello @Spyware007 I would like to add some buttons please assign me under GSSoC '23.

**Comment by PoorviShetty** [comment]
@Candy505 Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
