### ISSUE TITLE
Add new social button 

### ISSUE THREAD

**Issue by PriyankaTamhankar01** [Spyware007/Animating-Buttons#287]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

**social media links like Github ,LinkedIn,twitter**

**Comment by Spyware007** [comment]
@PriyankaTamhankar01 It is already assigned to someone else.
A similar issue is already created.
You can create another issue.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/
