### ISSUE TITLE
UI change for the footer section.

### ISSUE THREAD

**Issue by abhayy143** [Spyware007/Animating-Buttons#289]
## Issue
I am a **GSSoC'23** participant and I wanted to make certain changes to the UI of the **footer section**. I feel like the **social media icon section** would seem more appealing and eye-catching if we align them to center and add the credit section below them.

![15](https://github.com/Spyware007/Animating-Buttons/assets/53009878/28122044-64d7-45d2-b601-8c4577d7fdfb)

**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

**Comment by Spyware007** [comment]
Hello @abhayy143 
Please share the design that you want to implement.
Assigned to you but please verify the design with me first.
All the best.

**Comment by suryanshsoni120** [comment]
Can I work on this issue under GSSOC'23?
