### ISSUE TITLE
Add a New WebPage Navigation System to copy code instead of downloading it

### ISSUE THREAD

**Issue by adity2911** [Spyware007/Animating-Buttons#290]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
I propose a redesign of the website such that instead of downloading the button directly, a different web page is loaded where all the styling files are shown so that the user can copy the code instead.
Motivation: codepen.io

**Comment by adity2911** [comment]
I can do this. Can anyone assign me this under GSSoc'23 tag

**Comment by Spyware007** [comment]
Hey @adity2911 you can work on this.

**Comment by adity2911** [comment]
I have made the PR. Please check it.
There is a minor issue with the code.
I was not able to extract the code of .html, .css or .js file and display it on the area.

**Comment by Souravvmishra** [comment]
Heyy @adity2911, Would you mind if I create a new issue in order to complete your proposal

**Comment by adity2911** [comment]
Yes please do the needful.

**Comment by Spyware007** [comment]
@adity2911 @Souravvmishra 
Great collaboration!
@adity2911 Please mention the PR number!

**Comment by adity2911** [comment]
@Spyware007 @PoorviShetty can you please give level label to this?

**Comment by adity2911** [comment]
@Spyware007 @PoorviShetty can you give rating level to this?
