### ISSUE TITLE
Glitch Effect Button

### ISSUE THREAD

**Issue by Atharva-3000** [Spyware007/Animating-Buttons#291]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

I wanna add a button with a cool glitch effect when clicked, made purely in Html and CSS, which is easy to replicate.

![b1](https://github.com/Spyware007/Animating-Buttons/assets/72994819/fab6f469-82f1-471a-998f-bd62852416ae)

**Comment by Spyware007** [comment]
@Atharva-3000 Assigned to you
All the best.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/

**Comment by PayalPadmalyaPrusty** [comment]
@Spyware007 I want to contribute.Please assign me

**Comment by Spyware007** [comment]
@PayalPadmalyaPrusty You can create another issue and I will assign it to you!
