### ISSUE TITLE
Adding new buttons to the Repository

### ISSUE THREAD

**Issue by MrCuber** [Spyware007/Animating-Buttons#292]
**This is a(n):**
- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
I would like to contribute to the repository under GSSOC'23 by adding new animated buttons. I have already created a set of animated buttons that I would like to propose for inclusion in the repository.

Hello!
I am a proud contributor at GSSoC '23. I would like to the contribute to this project.

@Spyware007  if you think it is useful then do assign me the issue under GSSoC '23 with the level of the PR as well

**Comment by Spyware007** [comment]
@MrCuber  Assigned to you
All the best.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/

**Comment by MrCuber** [comment]
> @MrCuber Assigned to you All the best.
> 
> Make sure to ⭐ the repo and follow me. I would love to connect with you all. ❤️ https://www.linkedin.com/in/om-gawande/

@Spyware007  Thank you for assigning the issue to me! I'll do my best to address it promptly. I appreciate your support and I will contribute more animated buttons to this repository! I believe they will add value and enhance the user experience.
