### ISSUE TITLE
To add a CSS 3d skewed button

### ISSUE THREAD

**Issue by Yashika-Agrawal** [Spyware007/Animating-Buttons#293]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

It's a 3d skewed button which looks like a matchbox/eraser from side.
Something like this:
![image](https://github.com/Spyware007/Animating-Buttons/assets/97408966/9ba2c67b-c7bc-4807-9f4d-0989b149f89b)
i can make more changes to it.

**Comment by Yashika-Agrawal** [comment]
Hey @Spyware007 , I am GSsoc'23 contributor , please assign this task to me.

**Comment by Spyware007** [comment]
@Yashika-Agrawal Assigned to you
All the best.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/

**Comment by PayalPadmalyaPrusty** [comment]
@Spyware007 I want to contribute.Please assign me

**Comment by Spyware007** [comment]
@PayalPadmalyaPrusty Its' already done!
