### ISSUE TITLE
To add a new animated button

### ISSUE THREAD

**Issue by Yashika-Agrawal** [Spyware007/Animating-Buttons#294]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
I want to add a new button which can have layers circulating around it and the button shrinks , basically it's an energy button!

**Comment by Yashika-Agrawal** [comment]
Hey @Spyware007 , I am GSsoc'23 contributor i want to add this button as it aligns with my skills . Please assign it to me!

**Comment by ayushnighoskar** [comment]
Hi,I have experience with the project's tech stack.I will try to make it as better as possible.Please assign this issue to me.It would be grateful for me to work on it.

**Comment by KhushiKhandelwal610** [comment]
I want to add a button animation to the website. Please assign it to me under GSSOC'23

**Comment by Spyware007** [comment]
@Yashika-Agrawal Assigned to you
All the best.

@ayushnighoskar and @KhushiKhandelwal610 you can create a similar issue I will assign it to you.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/
