### ISSUE TITLE
Design The "Created By [xyz]" In a Better Way To make it look more appealing. 

### ISSUE THREAD

**Issue by Souravvmishra** [Spyware007/Animating-Buttons#295]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

The "Created By [XYZ]" tag seems to be so simple. we can add a little more design or attraction to it. This will make site more appealing. I would like to work on this add on as a contributor of GSSOC2023

**Comment by Spyware007** [comment]
@Souravvmishra  Nice idea.
Assigned to you
All the best.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
