### ISSUE TITLE
Change In UI in Socials Section

### ISSUE THREAD

**Issue by adity2911** [Spyware007/Animating-Buttons#296]
**This is a:**

- [x] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I want to change the link buttons on socials section more eye-comforting. Can you assign me the task under "GSSoC'23" ?

**Comment by Spyware007** [comment]
@adity2911 The similar issue is created and assigned.
You can start working on something else.
