### ISSUE TITLE
A new button animation for the website

### ISSUE THREAD

**Issue by sabhisharma-ise** [Spyware007/Animating-Buttons#297]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
The button which I'll be adding to the website looks as below:-

![image](https://github.com/Spyware007/Animating-Buttons/assets/100849696/529b1aa6-44ec-4026-a889-3b0726e41f61)

Contributor: Sabhi Sharma (GSSOC'23)

**Comment by Spyware007** [comment]
@sabhisharma-ise Assigned to you
All the best.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/
