### ISSUE TITLE
Chat box not fitting

### ISSUE THREAD

**Issue by Krishi1211** [Spyware007/Animating-Buttons#298]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [x] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

The chat box is not visible even when it is scrolled up or down

**Comment by Spyware007** [comment]
Can you please be more specific related to this issue? @Krishi1211

**Comment by Krishi1211** [comment]
> Can you please be more specific related to this issue? @Krishi1211

![image](https://github.com/Spyware007/Animating-Buttons/assets/97182407/db5bd2b1-b561-4b6c-a287-0c30539cdbf5)
I cant see the top portion of the support portion.

**Comment by Spyware007** [comment]
@Krishi1211 You can work on it! Assigned to you!

But I am afraid that this is an issue of buymeacoffee!
You can work on It and update me!

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by Krishi1211** [comment]
> Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

Heyy i am still working on this but my exams are going on so there is a delay

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by adity2911** [comment]
@Krishi1211 Can you give updates on your work?
