### ISSUE TITLE
Update social link buttons to use new, more modern icons

### ISSUE THREAD

**Issue by sabhisharma-ise** [Spyware007/Animating-Buttons#299]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

Issue: The current social link buttons on our website are outdated and do not match the overall design of the site. They are also not very visually appealing and do not encourage users to click on them.

![image](https://github.com/Spyware007/Animating-Buttons/assets/100849696/618eee48-847e-4da3-a253-c0f1b2977ca1)

Solution: We propose to update the social link buttons to use new, more modern icons that are consistent with the overall design of the website. We will also make the icons larger and more visually appealing, so that they are more likely to catch users' attention.

Benefits: Updating the social link buttons will make our website look more professional and up-to-date. It will also make it easier for users to find and click on the social media links, which will help us to increase our social media following.

Contributor - Sabhi Sharma (GSSOC'23)

**Comment by Spyware007** [comment]
@sabhisharma-ise The same issue is already created and Assigned
You can start working on something else.
