### ISSUE TITLE
To add a new button to the webiste

### ISSUE THREAD

**Issue by Dhruv-Srivastava** [Spyware007/Animating-Buttons#302]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I would like to add a button which would look like in the image below. So, please assign this issue to me under the GSSOC'23. Thank you!
![image](https://github.com/Spyware007/Animating-Buttons/assets/69876724/7231711e-a97d-4593-adc9-e1c0e10cc248)

**Comment by Spyware007** [comment]
@Dhruv-Srivastava Assigned to you
All the best.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by Dhruv-Srivastava** [comment]
Hi @PoorviShetty , I have raised a PR last night with the issue number linked to it.
