### ISSUE TITLE
Issue : Add animated upload button

### ISSUE THREAD

**Issue by Gurnav224** [Spyware007/Animating-Buttons#303]
I would like to add an upload button animation 

**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [✅] Proposal to the Repository
- [ ] Documentation / README.md changes

![preve1](https://github.com/Spyware007/Animating-Buttons/assets/72142482/66bc5529-9962-437e-85ba-4484001a5c48)

![clickstate](https://github.com/Spyware007/Animating-Buttons/assets/72142482/755a11ee-8235-495e-9e07-6ae9905b39a9)

**Details:**

**Comment by Spyware007** [comment]
@Gurnav224 Assigned to you
All the best.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/
