### ISSUE TITLE
New button to website

### ISSUE THREAD

**Issue by lmalkam** [Spyware007/Animating-Buttons#305]
I want to add a new button 

**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [x] Documentation / README.md changes

**Details:**
when we hover over the button it will expand from below creating a semicircle

**Comment by Spyware007** [comment]
@lmalkam Assigned to you
All the best.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/
