### ISSUE TITLE
Add a new animated button

### ISSUE THREAD

**Issue by KhushiKhandelwal610** [Spyware007/Animating-Buttons#306]
I want to work on this issue. Please assign it to me under GSSOC'23

**Comment by Spyware007** [comment]
@KhushiKhandelwal610 Assigned to you
All the best.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/

**Comment by KhushiKhandelwal610** [comment]
![Screenshot 2023-05-21 121338](https://github.com/Spyware007/Animating-Buttons/assets/114277727/177e98d7-8ed8-4563-9962-d2a08f01fcea)
What to do in this situation??

**Comment by Mayank1170** [comment]
Hey @Spyware007 ! 
can you please assign this issue to me.
I wanna work on this under GSSoC.
