### ISSUE TITLE
Counter to tell How many buttons are added! 2️⃣5️⃣ 🚀

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#307]
Add a counter somewhere in the UI.
The counter should be able to tell how many buttons are present on the website.

**Comment by Krishi1211** [comment]
> Add a counter somewhere in the UI. The counter should be able to tell how many buttons are present on the website.

I can work on this

**Comment by Spyware007** [comment]
@Krishi1211 Assigned to you.
All the best.

Leave a 🌟 if you like.

I would love to connect with you all ❤️
https://www.linkedin.com/in/om-gawande/
