### ISSUE TITLE
Interactive Button 

### ISSUE THREAD

**Issue by Durgesh4993** [Spyware007/Animating-Buttons#309]
https://github.com/Spyware007/Animating-Buttons/assets/98798977/f20d0921-d433-4fce-b861-820231b2c3bf

**Comment by Durgesh4993** [comment]
Hope you like the design of button 
Technologies used: HTML, CSS, JavaScript

**Comment by Spyware007** [comment]
@Durgesh4993 Assigned to you.
All the best.

Make sure to ⭐️ and follow me.

I would love to connect with you all ❤️
https://www.linkedin.com/in/om-gawande/

**Comment by Durgesh4993** [comment]
@Spyware007 Please check out #315 I have raised a PR and also edit the Data.js file
