### ISSUE TITLE
Add a button interaction animation

### ISSUE THREAD

**Issue by KhushiKhandelwal610** [Spyware007/Animating-Buttons#327]
I want to add a new button interaction animation. Please assign it to me under GSSOC'23

**Comment by shaileshthakur1** [comment]
I want to add below few buttons followed: 
1. Scroll triggered Effects : This includes elements sliding in, fading in, or expanding into view; when an user scrolls to a certain point on the page.

2. Notifications Button: This includes badges, counters, or small animations indicating new messages, alerts, or updates.

3. Toggle Buttons: When clicked, they animate to reflect the new selection, such as changing color or displaying an icon. These buttons can switch between different states or options. 

4. microinteraction: Button with subtle animation that provides feedback for small actions. For example, when hovering over a button, it may slightly elevate or display a tooltip.

All these may take a bit but will make sure I do ti neatly and efficiently. 

@Spyware007 can u  be kind enough to assign me this under gssoc please?

**Comment by Spyware007** [comment]
@shaileshthakur1  It's amazing!
You can create a separate issue for each one!
Good luck!

**Comment by shaileshthakur1** [comment]
Okay 🙌

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
