### ISSUE TITLE
giltch in flip button

### ISSUE THREAD

**Issue by anshikkay** [Spyware007/Animating-Buttons#329]
![Screenshot (106)](https://github.com/Spyware007/Animating-Buttons/assets/129502224/ea0f6e1e-ce0d-4e3e-9662-6cec25966d5e)
there is not a proper functioning of flip button that is not fliping properly,
i can change it to work in an proper way

**Comment by Spyware007** [comment]
@anshikkay You can work on fixing it.
Assigned to you!

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
