### ISSUE TITLE
adding functionality to button created by arjun-Ingole

### ISSUE THREAD

**Issue by anshikkay** [Spyware007/Animating-Buttons#330]
![Screenshot (107)](https://github.com/Spyware007/Animating-Buttons/assets/129502224/6e2f2448-a1fb-47e8-8165-21c8d023cfde)
this a simple button,i want to add animation or transition to this button

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
