### ISSUE TITLE
wanted to make heart red in the button created by Arjun-Ingole_2

### ISSUE THREAD

**Issue by anshikkay** [Spyware007/Animating-Buttons#331]
![Screenshot (108)](https://github.com/Spyware007/Animating-Buttons/assets/129502224/0da03528-b167-4ed3-8861-8d596e897130)
as it can be seen,there is no effect on button while moving a cursor on to it,i want to add hover effect to small heart present on the button

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
