### ISSUE TITLE
want to add new animated button

### ISSUE THREAD

**Issue by divyanshiet** [Spyware007/Animating-Buttons#332]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

**Comment by divyanshiet** [comment]
@Spyware007  kindly assign this to me

**Comment by Pujyalakshmi** [comment]
I want to add a new Animated button. Please assign this issue to me and let me show my skills in GSSOC'23.

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
