### ISSUE TITLE
Readme updation

### ISSUE THREAD

**Issue by shraddha761** [Spyware007/Animating-Buttons#334]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ x] Documentation / README.md changes

**Details:**

![Screenshot 2023-05-21 160801](https://github.com/Spyware007/Animating-Buttons/assets/106100728/c5796cdc-ce94-4d10-9953-60124b18c2fc)

adding this image in readme makes it more attractive please assign me this issue under GSSOC'23

**Comment by PoorviShetty** [comment]
@shraddha761 Would you like to work on this issue?

**Comment by shraddha761** [comment]
@PoorviShetty  yahhh I like to work on this
