### ISSUE TITLE
Gradient In Background

### ISSUE THREAD

**Issue by Rohitn-2312** [Spyware007/Animating-Buttons#336]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

A Gradient is needed in the background to make the website look more attractive . And the links which are present at the starting needs a proper styling .

**Comment by arunavabasu-03** [comment]
I would like to work on this!

**Comment by shreyal0007** [comment]
I would love to contribute and show my skills .Kindly assign this task to me under Gssoc 2023

**Comment by PoorviShetty** [comment]
@arunavabasu-03 Assigned!

**Comment by Rohitn-2312** [comment]
I want to work on this

**Comment by PoorviShetty** [comment]
@Rohitn-2312 Please create an identical issue, I will assign it to you

**Comment by Rohitn-2312** [comment]
@PoorviShetty I am new to open source i want to ask that the issue was created by me  shouldn't the task be assigned to me?

**Comment by PoorviShetty** [comment]
Hi @Rohitn-2312, it's better to indicate that you want to work on the issue as well. In some cases, the issue creator just wants to raise an issue to the contributors's attention.

**Comment by Rohitn-2312** [comment]
@PoorviShetty Ok , will keep in mind from next time

**Comment by PoorviShetty** [comment]
@arunavabasu-03 Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by arunavauni-03** [comment]
Hey , my exams are going on , so I am bit busy but when it ends  i am going  wrap up everything.  I hope you understand.

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by arunavauni-03** [comment]
Alright,  I tried my best to do that !

**Comment by arunavauni-03** [comment]
What type of gradient you guys want ?

**Comment by arunavabasu-03** [comment]
pls give more context about the gradient so that i can proceed ?? like what colors you want !!

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
