### ISSUE TITLE
Enable lazy loading to improve website performance

### ISSUE THREAD

**Issue by M-A-N-I-K** [Spyware007/Animating-Buttons#339]
Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of images and other resources until they are needed. This can help to reduce the initial load time of a page, which can improve the user experience and make the website more responsive.

The benefits of lazy loading include:

-     Reduced initial load time
-     Improved user experience
-     More responsive website
-     Increased SEO ranking

**Comment by PoorviShetty** [comment]
@M-A-N-I-K Would you like to work on this issue?

**Comment by M-A-N-I-K** [comment]
Yeah , i would like to work on this issue!
