### ISSUE TITLE
Update The Logic To Download Files

### ISSUE THREAD

**Issue by Souravvmishra** [Spyware007/Animating-Buttons#341]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

After a close review of the code, I found out that the current alogorithm to download the files is a little tricky and outdated. Instead of downloading the three different files, we can create a zip file consisting of the three files and download them at once. 

One of the major reason behind this would be clarity. I myself when tried to download the file, i saw one file which confused me but after a little while I understood whats happening. 

As a common practice, we all have this stuck in mind that this type of things are generally provided as a zip file. And by providing the individual file, we are going against the psychology which disrupt the user experience. 

I would like to work on this issue and Change the algorithm to convert the files into zip before downloading as well as optimizing the code along with.
Thank You 
#gssoc2023

**Comment by Spyware007** [comment]
@Souravvmishra Amazing work on understanding the repository! 🤩
Assigned to you for 45 points!

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by Spyware007** [comment]
# Please check #1346
