### ISSUE TITLE
I want to change the theme of social media buttons

### ISSUE THREAD

**Issue by ombhojane** [Spyware007/Animating-Buttons#345]
Current Social media Icons color theme is :

![image](https://github.com/Spyware007/Animating-Buttons/assets/82753658/f585bdf1-262d-40d6-93ac-8fff400f4cb5)

**Details:**
I want to change color scheme similar to their existing colour scheme. In the process, I'll respect the Google colour theme and make changes accordingly.
e.g. Instagram : pink & white, twitter : blue & white

This will be more real and hope the social media gain more followers.

**This is a(n):**

- [x] Update to an existing Animated Button

Can you please assign this issue to me..
GSSOC 2023 :)

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by PoorviShetty** [comment]
@ombhojane Assigned!

**Comment by ombhojane** [comment]
thankyou!! @PoorviShetty 
I'll try my best to improve this
