### ISSUE TITLE
Add a new button

### ISSUE THREAD

**Issue by adjascently** [Spyware007/Animating-Buttons#346]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
I want to work on this issue. Please assign it to me under GSSOC'23

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.
