### ISSUE TITLE
Added an Interactive Hover button of 4 different types that one can use

### ISSUE THREAD

**Issue by Aryan5464** [Spyware007/Animating-Buttons#349]
After hovering to the button the background will change 
All the four buttons are similar with little-little different effects

These buttons are gonna look great on a website 

#wonderfullButtonForWonderfullWebsites

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
