### ISSUE TITLE
I want to add new animated button.

### ISSUE THREAD

**Issue by Gaurav12477** [Spyware007/Animating-Buttons#353]
Hi, i would like to contribute to the issue under GSSoC'23. I am interested in building an animated button.

**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

**Comment by rafiya2003** [comment]
can you please assign me this issue under GSsoc'23

**Comment by PoorviShetty** [comment]
@Gaurav12477 Assigned!
@rafiya2003 Please create an issue for yourself!

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
