### ISSUE TITLE
Add several animation button by experimenting #GSSoc'23

### ISSUE THREAD

**Issue by demonigod** [Spyware007/Animating-Buttons#354]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

Want to add new animation buttons by experimenting with Html, CSS and Javascript.

**Comment by shreyal0007** [comment]
i would like to work on this issue. 
Kindly assign it to me

**Comment by PoorviShetty** [comment]
@demonigod I apologise, if I understand correctly, you want to work on the issue as well. Please create an identical issue, I will assign it to you

**Comment by shreyal0007** [comment]
@Poorvi i have raised the PR  and  created the  animated button under
public>Buttons THE name of my folder is (shreyal0007). Kindly see it.

**Comment by demonigod** [comment]
@PoorviShetty I am not able to understand please help, i issue i have created but you assigned this to someone else?!! Do i have to make a issue now ?

**Comment by demonigod** [comment]
> Yeah sorry, just create a similar issue, I will assign it to you @demonigod

sure, i have created the issue.

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them. @shreyal0007
