### ISSUE TITLE
Adding another animated button using html and css #gssoc23

### ISSUE THREAD

**Issue by JatinBisht2308** [Spyware007/Animating-Buttons#358]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

**Comment by Jacinth-Mahanta** [comment]
New buttons made and PR sent!

**Comment by JatinBisht2308** [comment]
sir please assign this issue to me.

**Comment by JatinBisht2308** [comment]
@PoorviShetty mam please add label of gssoc23 and level into it I have made a pr.
