### ISSUE TITLE
Adding Animated Buttons - GSSoC'23

### ISSUE THREAD

**Issue by iLakshya** [Spyware007/Animating-Buttons#360]
**This is a(n):**

- [x] Update to an existing Animated Button
- [x] Any Error
- [x] Proposal to the Repository
- [x] Documentation / README.md changes

**Details:**

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by Jacinth-Mahanta** [comment]
I have made a new animated button and sent the PR. Kindly check and do the needful.

**Comment by iLakshya** [comment]
I have made the desired changes. Please accept my PR

**Comment by iLakshya** [comment]
Have made the button. Please have a look to merge the branch
