### ISSUE TITLE
Adding a see code button for each button that takes user to the codes of the respective buttons and helps in adding the code in their projects (GSSoC'23)

### ISSUE THREAD

**Issue by P10swati** [Spyware007/Animating-Buttons#366]
If you are okay with the idea . Please assign me this i would like to work on it .

**Comment by PoorviShetty** [comment]
Sure, I'll assign it to you! Please create a PR and link it to the issue.

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by P10swati** [comment]
My semester exams are  going on..I will work on  it as soon as my semester exams are over ( please wait till 12th June) Sent from Mail for Windows From: PoorviSent: 04 June 2023 20:19To: Spyware007/Animating-ButtonsCc: P10swati; AssignSubject: Re: [Spyware007/Animating-Buttons] Adding a see code button for each button that takes user to the codes of the respective buttons and helps in adding the code in their projects (GSSoC'23) (Issue #366) Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

**Comment by PoorviShetty** [comment]
Closing it as this feature has already been implemented
