### ISSUE TITLE
Add scroll to top button

### ISSUE THREAD

**Issue by Laxmankohar** [Spyware007/Animating-Buttons#371]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

Adding a scroll-to-top button to a website is a common practice to enhance user experience, allowing visitors to easily navigate back to the top of a webpage without manually scrolling. This feature is especially useful for long or content-heavy pages. 

I would like to work on this issue under GSSoc23. Can you assign it to me?

**Comment by PoorviShetty** [comment]
Hi, I believe a similar issue is being addressed in #269 already
