### ISSUE TITLE
Pagination number is not visible

### ISSUE THREAD

**Issue by Laxmankohar** [Spyware007/Animating-Buttons#372]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [x] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

![image](https://github.com/Spyware007/Animating-Buttons/assets/73365025/69c7e2ea-e54a-4840-a1c0-3459fa7b96e8)

in dark mode the number in pagination is not visible clearly. I would like to work on this issue under GSSoc23. Can you assign it to me?

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by Laxmankohar** [comment]
@PoorviShetty Someone has already solved this issue before i start.
