### ISSUE TITLE
want to make button created by Ashutosh raj Gupta full flipped 

### ISSUE THREAD

**Issue by anshikkay** [Spyware007/Animating-Buttons#376]
![git4](https://github.com/Spyware007/Animating-Buttons/assets/129502224/6ba4094e-900b-4960-9112-43801c6b53aa)

**Comment by Spyware007** [comment]
Assigned to you @anshikkay 
All the best!

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
