### ISSUE TITLE
mouse always point to button

### ISSUE THREAD

**Issue by hashfx** [Spyware007/Animating-Buttons#378]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

The mouse pointer always points towards the button

**Comment by avinasdube** [comment]
Can you please clarify more ? What file or component has this issue ?

**Comment by hashfx** [comment]
> Can you please clarify more ? What file or component has this issue ?

I can add a button whose cursor always points towards button, that's why I've opened this issue so that I can add that button 😅
