### ISSUE TITLE
Add GitHub readme badges

### ISSUE THREAD

**Issue by singh-anushka** [Spyware007/Animating-Buttons#384]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [x] Documentation / README.md changes

**Details:**

Adding GitHub-readme badges. 

Kindly assign me this issue, and add gssoc23 label to it. So that I can update the readme of this repository.

**Comment by PoorviShetty** [comment]
Hi, I think #334 already addresses this
