### ISSUE TITLE
Favicon and logo issue

### ISSUE THREAD

**Issue by suryanshsoni120** [Spyware007/Animating-Buttons#388]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [x] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

The favicon and the logo of the website do not match. Both should be same as part of the same website. Instead of the website logo, there is the user's logo and the GDSC logo which is not a good practice. Can you please assign me this issue under GSSOC'23?

**Comment by Spyware007** [comment]
The project is under GDSC DYPCOE. So suggest something more appealing than that in the form of design, and then I will assign it to you!
