### ISSUE TITLE
Add a new button

### ISSUE THREAD

**Issue by Arnabhit** [Spyware007/Animating-Buttons#392]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ✅] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
I want to add a new button

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
