### ISSUE TITLE
buymecoffee button(yellow button) on right bottom is not responsive

### ISSUE THREAD

**Issue by abansal15** [Spyware007/Animating-Buttons#394]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

**Comment by abansal15** [comment]
please assign this issue to me

**Comment by Spyware007** [comment]
@abansal15 You can work on it and create a PR but it's a iframe tag popup by default of buymeacoffee.
All the best!

**Comment by abansal15** [comment]
sir i am not able to locate the code of that iframe  in vs code but i have located in the browser inspect sir can you pls help

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
