### ISSUE TITLE
New Button with slide animation and Info

### ISSUE THREAD

**Issue by harshalwasnik22** [Spyware007/Animating-Buttons#403]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes
- [x] New feature button

**Details:**

![image](https://github.com/Spyware007/Animating-Buttons/assets/111900209/735ee223-1f55-407f-9ab1-137b6c0e8da0)

Add a new feature button with slide animation and info. The animation should be something that is visually appealing and attention-grabbing. The info should be a short description of what the button does.

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
