### ISSUE TITLE
New Button

### ISSUE THREAD

**Issue by Krishi1211** [Spyware007/Animating-Buttons#406]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

**Comment by Krishi1211** [comment]
Should i create a fork or directly pr my code?

**Comment by Spyware007** [comment]
@Krishi1211  Hello Krishi You need to fork the repository, and then raise a PR.

**Comment by Krishi1211** [comment]
> @Krishi1211 Hello Krishi You need to fork the repository, and then raise a PR.

Hii i have raised a pr please check it out!!😍😍
