### ISSUE TITLE
To add a new animated button to the list!

### ISSUE THREAD

**Issue by P766-spec** [Spyware007/Animating-Buttons#409]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [x] Any Error
- [x] Proposal to the Repository
- [x] Documentation / README.md changes

**Details:**

**Comment by P766-spec** [comment]
@PoorviShetty  would like to work on it!

**Comment by P766-spec** [comment]
Thank you!

**Comment by P766-spec** [comment]
Hello @PoorviShetty  i have already done with adding a button , Please do me a favour and look into it

**Comment by P766-spec** [comment]
@PoorviShetty  when you will review it??

**Comment by PoorviShetty** [comment]
Please mention your PR number here

**Comment by P766-spec** [comment]
Okay, its #409

**Comment by PoorviShetty** [comment]
That's the issue number, please mention your PR number

**Comment by P766-spec** [comment]
Sorry, PR no is 905 @PoorviShetty

**Comment by PoorviShetty** [comment]
Please make sure to fill the PR template correctly and fix all merge conflicts

**Comment by P766-spec** [comment]
Okay

**Comment by P766-spec** [comment]
> Please make sure to fill the PR template correctly and fix all merge conflicts

Done with template

**Comment by P766-spec** [comment]
> > Please make sure to fill the PR template correctly and fix all merge conflicts
> 
> Done with template @PoorviShetty

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
