### ISSUE TITLE
New Animated buttton

### ISSUE THREAD

**Issue by Naishadha-satya** [Spyware007/Animating-Buttons#429]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [** ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

https://github.com/Spyware007/Animating-Buttons/assets/124195686/2cbf7897-2744-42e0-938b-45ad6661362f

**Comment by Naishadha-satya** [comment]
would like to work on this

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
