### ISSUE TITLE
A new Day to Night button 

### ISSUE THREAD

**Issue by Samriddhi15** [Spyware007/Animating-Buttons#436]
I want to create a new day to night button . Please assign me this issue, it will be a great opportunity for me.

**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
Here is the demo video

https://github.com/Spyware007/Animating-Buttons/assets/106501626/de21434f-7898-461c-9889-70042a2c572b

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by Samriddhi15** [comment]
Yes, I am still working on it. I will soon make PR for it. Sent from Mail for Windows From: PoorviSent: Sunday, June 4, 2023 8:25 PMTo: Spyware007/Animating-ButtonsCc: Samriddhi meena; AssignSubject: Re: [Spyware007/Animating-Buttons] A new Day to Night button (Issue #436) Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>
