### ISSUE TITLE
Creative button hover effect

### ISSUE THREAD

**Issue by Samriddhi15** [Spyware007/Animating-Buttons#437]
I want to create a hover button. Please assign me this issue. 

**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

https://github.com/Spyware007/Animating-Buttons/assets/106501626/5670a892-40a6-43e4-a76e-22bfd956482f

Here is the demo video

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by Samriddhi15** [comment]
Yes, I am still working on it. I will soon make PR for it.  Sent from Mail for Windows From: PoorviSent: Sunday, June 4, 2023 8:25 PMTo: Spyware007/Animating-ButtonsCc: Samriddhi meena; AssignSubject: Re: [Spyware007/Animating-Buttons] Creative button hover effect (Issue #437) Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
