### ISSUE TITLE
Custom emoji radio buttons

### ISSUE THREAD

**Issue by Samriddhi15** [Spyware007/Animating-Buttons#438]
I want to create a button having  different emojis on it using CSS. Please assign me this issue.

**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

https://github.com/Spyware007/Animating-Buttons/assets/106501626/4c0bf2cd-6192-4ab9-82ba-d41e31592fae

here is the demo video

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by Samriddhi15** [comment]
Yes, I am still working on it. I will soon make PR for it.  Sent from Mail for Windows From: PoorviSent: Sunday, June 4, 2023 8:24 PMTo: Spyware007/Animating-ButtonsCc: Samriddhi meena; AssignSubject: Re: [Spyware007/Animating-Buttons] Custom emoji radio buttons (Issue #438) Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>
