### ISSUE TITLE
Enhance User Experience By Keeping Track Of Page Where The User Left 

### ISSUE THREAD

**Issue by Souravvmishra** [Spyware007/Animating-Buttons#440]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

While I was playing around with the code to look for issues, I found it really irritating that on every refresh I am again on page 1. And I have to scroll down whole page to go to the desired page. It would be so good if we can make sure that user don't have to face this issue by keeping a track of the page where user left last time. It will enhance the user experience.

I am a GSSOC2023 contributor and would like to work on this add on.

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
The labels will be added to the PR

**Comment by Souravvmishra** [comment]
It has been merged
