### ISSUE TITLE
Cursor Pointing

### ISSUE THREAD

**Issue by BALASARVAN12** [Spyware007/Animating-Buttons#442]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I will change the mouse pointer
can you please assign me this task under Gssoc'23

**Comment by BALASARVAN12** [comment]
@PoorviShetty To change the mouse pointer, I should be able to add a file in the src folder with your permission. Shall I do it?

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
