### ISSUE TITLE
Add new animation button 

### ISSUE THREAD

**Issue by demonigod** [Spyware007/Animating-Buttons#457]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

Details:

Hey @PoorviShetty, I gone through the project and want to add a new button in the bucket of buttons.

Assign me this Issue to add a additional button in your project

**Comment by PoorviShetty** [comment]
@demonigod Please go ahead :)

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
