### ISSUE TITLE
Show the number of stars, forks and contributors on the homepage! 🌟🚀

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#460]
Make some cool tags for showing the number of stars 🌟, forks 📌, and contributors 🧑‍💻 on the homepage.
Don't mess up with the current UI. 😇
The tags should match the design of the website. 🎨

All the best! 🥳

**Comment by Elleriyc** [comment]
Hello, i'm a student in computer science and i looking for my first contribution for a class can I take this one ?

**Comment by Souravvmishra** [comment]
### I Would **Love** To Do This

**Comment by amratansh12** [comment]
Hey, I have already solved this issue. Just wanted to clarify one thing that since there are no collaborators so what are we supposed to show? Should we display contributors instead?

**Comment by Spyware007** [comment]
@Elleriyc, @Souravvmishra , @yaswika0311 
Please share the designs you want to implement.

@amratansh12 The navbar looks a bit odd if you add those tags there.
Also, I was expecting some animated tags which match the UI. You can change the design and ping here!


I will assign to the best design and will try to give you more points.

**Comment by amratansh12** [comment]
Hey, I have changed the position of the tags and added some hover effect over them. 
 
Samples: 
1.
<img width="935" alt="1" src="https://github.com/Spyware007/Animating-Buttons/assets/98476196/484e04a5-27ff-4a24-8571-2cec8f7fb3a2">
2.
<img width="937" alt="2" src="https://github.com/Spyware007/Animating-Buttons/assets/98476196/30d92ea6-1601-43eb-95a0-ba59d829d23d">
3.
<img width="170" alt="3" src="https://github.com/Spyware007/Animating-Buttons/assets/98476196/1248e06e-d74a-4e85-b671-125260bdfa8c">

**Comment by Spyware007** [comment]
@amratansh12 Assigned to you.
Can you please add some animated symbols of stars for the star tag and similar for other tags too also add the collaborator tag?

@Elleriyc @Souravvmishra @yaswika0311 You can create other issues and work on them.
Thank you so much!

**Comment by amratansh12** [comment]
Hey, I am done with the symbols as well. Just wanted to clarify one thing, we do not have any collaborators so what are we supposed to do with that?

**Comment by Spyware007** [comment]
@amratansh12 
Sorry, I misspelled it.
I want to say, contributors.

**Comment by amratansh12** [comment]
All added. Everything is animated and responsive according to the UI. Can I raise the PR now?

<img width="500" alt="4" src="https://github.com/Spyware007/Animating-Buttons/assets/98476196/74329d54-4c97-4eac-818d-bd8a486aea07">

**Comment by Spyware007** [comment]
Yeah sure you can raise the PR @amratansh12 
Just make sure the Contributors number is more than 100 and in your UI its showing only 30!

**Comment by amratansh12** [comment]
Yeah, I will be raising the PR. A little clarification, I have not manually entered the contributors count. This particular repo has 30 contributors and this data is coming through the github api.

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
