### ISSUE TITLE
proposing a new style of button

### ISSUE THREAD

**Issue by ShubhiG30** [Spyware007/Animating-Buttons#464]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
A button would be translucent crystal-like appearance having a hover effect or other animation.

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by ShubhiG30** [comment]
#1002 PR
