### ISSUE TITLE
improvement in ui/ux

### ISSUE THREAD

**Issue by khushi767** [Spyware007/Animating-Buttons#468]
i would like to work upon ui/ux of website to make its landing page look more attractive.
please assign me this task under gssoc'23

**Comment by Cadit21** [comment]
I would like to work on the designing part of the website I have some creative ideas.
pls assign this to me.

**Comment by Spyware007** [comment]
@khushi767 @Cadit21 
Can you tell me what are you planning to do?

**Comment by khushi767** [comment]
> @khushi767 @Cadit21 Can you tell me what are you planning to do?

i want to make changes in font style for landing page and will try to add some animation effect cause the site looks good in dark mode but seems to be boring in light mode.

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by adity2911** [comment]
Closing as delayed.
