### ISSUE TITLE
[Gssoc'23]: Adding new annimated button

### ISSUE THREAD

**Issue by Ks103** [Spyware007/Animating-Buttons#479]

**Comment by Ks103** [comment]
Please Assign me this issue so that i can work on this task.

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by Ks103** [comment]
I have made the changes you can merged this ussue
