### ISSUE TITLE
Proposal for a new animated button

### ISSUE THREAD

**Issue by kushagra-goyal-14** [Spyware007/Animating-Buttons#481]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I am here to propose a button with an aqua color and on hover the button flips. So, it would be great if you assign this issue.

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
