### ISSUE TITLE
Button By abhinav-m22 Is Not Alligned.

### ISSUE THREAD

**Issue by Souravvmishra** [Spyware007/Animating-Buttons#482]
**This is a(n):**

- [x] Update to an existing Animated Button
- [ ] Any Error
![Comparing Spyware007_main Souravvmishra_ButtonFixedByLakhan06 · Spyware007_Animating-Buttons - Brave 23-05-2023 22_38_39](https://github.com/Spyware007/Animating-Buttons/assets/89072785/ecd545b6-d081-436a-a1a1-c73b2ca697f2)

- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

Button By **_abhinav-m22_** Is Not Alligned.

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
