### ISSUE TITLE
Buttons showing 2 3 4 5 6 7 are not visible clearly in Dark mode

### ISSUE THREAD

**Issue by Shreyans2004** [Spyware007/Animating-Buttons#483]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [x] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

The buttons at the end showing 1 2 3 4 5 6 7  are not visible properly in the dark mode. It is difficult for user to see numbers especially 2 3 4 5 6 7.I can change the styling so that the buttons can be visible in dark mode also.

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
