### ISSUE TITLE
Glitch effect button new

### ISSUE THREAD

**Issue by PayalPadmalyaPrusty** [Spyware007/Animating-Buttons#492]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

**Comment by PayalPadmalyaPrusty** [comment]
@Spyware007 Can you please assign me

**Comment by Spyware007** [comment]
@PayalPadmalyaPrusty  Make separate PR for each button.
And don't make any duplications.
All the best! 🌟

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by PayalPadmalyaPrusty** [comment]
> Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

Yes i have solved the issue

**Comment by PayalPadmalyaPrusty** [comment]
@PoorviShetty The PR hasn't merged yet.Kndly please check it

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
