### ISSUE TITLE
Fun Change: Change the buttons on the socials such that on every refresh of the page, they change.

### ISSUE THREAD

**Issue by adity2911** [Spyware007/Animating-Buttons#493]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I propose to change the code so that, on every refresh of the page, the socials button change their appearance, taking a random button from the database of the website itself.

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
