### ISSUE TITLE
Loading Button Animation

### ISSUE THREAD

**Issue by Saurabh-kumar09** [Spyware007/Animating-Buttons#503]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
I want to build a button loading animation using HTML & CSS.

**Comment by Saurabh-kumar09** [comment]
@Spyware007 Please assign me this usse

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by Saurabh-kumar09** [comment]
Yes PR is already merged. Okay, I'll close the issue.
