### ISSUE TITLE
[FEATURE]: Readme Files Update

### ISSUE THREAD

**Issue by tuhinaww** [Spyware007/Animating-Buttons#504]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [x] Documentation / README.md changes

**Details:**

Hey, @Spyware007 

I can help with making the readme file for this project. Please assign it to me.

PS: If you would like an updated template as well please raise an issue for that and assign it to me :)

**Comment by Spyware007** [comment]
@tuhinaww  Assigned to you!
