### ISSUE TITLE
Scrollbar changes

### ISSUE THREAD

**Issue by TusharUtane07** [Spyware007/Animating-Buttons#505]
I would like to add color full scroll bar according to the theme for better User Experience.
Please assign me this issue under GSSoC-2023

**Comment by Spyware007** [comment]
@TusharUtane07 Assigned to you!

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
