### ISSUE TITLE
Multiple Buttons on Last Page

### ISSUE THREAD

**Issue by TusharUtane07** [Spyware007/Animating-Buttons#506]
There's a bug on last page single button is showing multiple times, I would like to fix this issue.
@Spyware007 Assign me this issue.

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
