### ISSUE TITLE
Cursor Pointer on the "Created by <github-username>" is not proper

### ISSUE THREAD

**Issue by sabhisharma-ise** [Spyware007/Animating-Buttons#523]
The mouse cursor when hovered over the "Created by <github_user>" Box, the cursor is giving a question mark with it which doesn't looks good. 

**This is a(n):**

- [ ] Update to an existing Animated Button
- [X] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

Please see the video below 

https://github.com/Spyware007/Animating-Buttons/assets/100849696/f7db9664-2383-4d36-a47a-377d6eaea4cd

**Comment by PoorviShetty** [comment]
@sabhisharma-ise Would you like to work on this issue?

**Comment by sabhisharma-ise** [comment]
@PoorviShetty Yes please
