### ISSUE TITLE
Page doesn't scroll to top when changing from one to another

### ISSUE THREAD

**Issue by avinasdube** [Spyware007/Animating-Buttons#527]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [X] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

When moving from one page to another, the next page starts from bottom. I want to fix that issue and make the page scroll to top whenever you go to new page. Assign me to fix this issue or bug.

**Comment by Spyware007** [comment]
@avinasdube It's fixed!
You can try working on other issues.

**Comment by avinasdube** [comment]
i don't see it fixed. even though i updated the changes in my local machine nothing shows up changed.
