### ISSUE TITLE
Navabar issue

### ISSUE THREAD

**Issue by Shreyans2004** [Spyware007/Animating-Buttons#534]
Upon scrolling down one cannot have access to the the  NAVIGATION BAR.One has to go back to the top in order to access the navbar .Especially to on the dark  mode it disturbes user's experience to again and again scroll up and down for switching on/off the dark mode. 

**This is a(n):**

- [ ] Update to an existing Animated Button
- [x] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I can resolve this issue by fixing the position of Navbar so that user don't have to scroll up to see the navbar.Can you assign this task to me?

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
