### ISSUE TITLE
Update the alignment of button made by annakimdev

### ISSUE THREAD

**Issue by yaswika0311** [Spyware007/Animating-Buttons#535]
This is a(n):

 Update to an existing Animated Button
 Any Error
 Proposal to the Repository
 Documentation / README.md changes

Details:

The button made by annakimdev is not aligned to the center of the page and the text is not in the middle of the button.
I have made the changes accordingly and now it is looking like this.
Before ---->
![button_before](https://github.com/Spyware007/Animating-Buttons/assets/120516365/d0990501-c76f-4f20-871d-4689e8662d9d)
After ---->
![button_after](https://github.com/Spyware007/Animating-Buttons/assets/120516365/eba67a9c-ab0d-4d2c-85fd-c7bb941ba381)

please assign me this issue @Spyware007 under GSSOC'23, so that I can raise the PR.

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
