### ISSUE TITLE
ADD FEATURES TO SCROLL BAR

### ISSUE THREAD

**Issue by Shreyans2004** [Spyware007/Animating-Buttons#536]
The  current scroll bar is very common .Not much styling is done on it.

**This is a(n):**

- [x] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I can add some styling to the scroll bar so that it looks attractive .Can you assign this task to me?

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
