### ISSUE TITLE
Share on Twitter/LinkedIn url or card image! 🤩 🚀

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#538]
1. Make a share button after clicking on the show code to share the button to LinkedIn or Twitter. 🕊️
2. Share button should be able to redirect the user to their Twitter account along with some text like
     Here's a cool animated button from https://lets-animate-btns.vercel.app/ 🌟
     with an image of the button. 🏞️

**Comment by vaibhav-xt** [comment]
I am interested in solving this problem. Please can elaborate more.

**Comment by Spyware007** [comment]
@vaibhav-xt 
There should be a share button after opening any button.
The share button should allow to share the button page as a tweet on twitter.

Can you work on this?

**Comment by Souravvmishra** [comment]
Do You Mean The Link Of The Page As A Tweet?

**Comment by Mayank1170** [comment]
Ok, I think we need a share button which on click, page redirected to twitter or linkedIn with some template for the post !
if yes, then can you please assign it to me i wanna work on this under GSSoC.

**Comment by manoranjanonline** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by PriyankaTamhankar01** [comment]
Hi,I would like to contribute to this issue under th GSSoC'23.

**Comment by Spyware007** [comment]
@Souravvmishra Yes, I mean the link along with an image of the button or a small preview!
@Mayank1170 Yes, it's true but we need an image or preview too...
@manoranjanonline and @PriyankaTamhankar01 

Please tell me your approach first!

I know it's a extremely hard to make a preview an image may also works!

**Comment by vaibhav-xt** [comment]
Sorry for the very late response but I can solve this issue. html2canvas help to create preview of image. Hey, assign it to me I will work.

**Comment by Spyware007** [comment]
Assigned to you @vaibhav-xt !

**Comment by vaibhav-xt** [comment]
@Spyware007 

### I tried and the preview of the image is working but It is not capturing the CSS only raw HTML is capturing for a few of them are working correctly. 

*paste the below URL on the browser and see the image*

# As this one has only  has HTML: 
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAVQAAAD6CAYAAAD+87+fAAAAAXNSR0IArs4c6QAAC/hJREFUeF7t3b9uXHUCBeBrbciSRVvRJE/gMg/gNiJdJGgNNUggFB7AForpKJDoEHQkhUtK10CbKpFoQp7AUgqI+bteXSOPnKw3OPYd+5yZzw0C23fO/c6Po5mxo6zs7+/vDz4IECBA4MwCKwb1zIYuQIAAgQMBg+ogECBAYCIBgzoRpMsQIEDAoDoDBAgQmEjAoE4E6TIECBAwqM4AAQIEJhIwqBNBugwBAgQMqjNAgACBiQQM6kSQLkOAAAGD6gwQIEBgIgGDOhGkyxAgQMCgOgMECBCYSMCgTgTpMgQIEDCozgABAgQmEjCoE0G6DAECBAyqM0CAAIGJBAzqRJAuQ4AAAYPqDBAgQGAiAYM6EaTLECBAwKA6AwQIEJhIwKBOBOkyBAgQMKjOAAECBCYSMKgTQboMAQIEDKozQIAAgYkEogd1d3d3WF9fH3Z2doY7d+4MGxsbE922yxAgQGB6gehB3draGjY3Nw/u+vr168P29vawurr6QoUnT54Mt2/fHh48eHAmrfFxb926daZr+GYCBJZLYCEH9eHDh8Pa2tqpm3z8+PHw6NGj4caNG6e+hm8kQGD5BKIH9ehL/rt37x68/P+7j/EZqkH9OyWfJ0BgHgLRg3qaGzaop1HzPQQITCFgUI9R9JJ/iqPlGgSWT8CgGtTlO/XumMCcBAyqQZ3T0XJZAssnYFAN6vKdendMYE4CBtWgzulouSyB5RMwqAZ1+U69OyYwJwGDalDndLRclsDyCRjUOQ3q3t7+8NFHe8MXX/w6e4R33/3n8NlnV4YrV1b+51G///6PYWvrl+HevdeG119fGe7d+234+uvfZv++fEfTHRPoEzCocxrUw8uOQ/n++0+H7e3XhtXVf5zohIxj+vbbPw83b75iUE8k5osIZAgY1HMY1KPPPE9au2eoJ5XydQRyBAyqQc05jZIQKBcwqCGDOj4j/fbbP2bvsR59hjpGXF//edjZ+f2ZtwEO3xoYP/+i92fLz6j4BGoEDGrAoB4O49FRPDqoP/zw58EPqI7+QGv8/F9De/ngn+PbCuPHxsarNYdPUAKLJmBQAwZ1jPD/nqHevHlp+OmnZ4dyd3d/9oz1aHw/xFq0/z3dT5uAQQ0e1PEn/ePH80M5DuoHHzwdPv741RP/5kDbwZSXQKOAQb3AQf3yy1+Ht966PPu90+PeQ/3qq38Nn3zy18v5w5f8h89Qx5f3a2uXGs+dzAQWUsCgnsOgHvd7qONL/B9//M/sPc/nf03quB9KvfPO5dl7puPnP/30l2d+v/Wbb34f3njj0rF/cGAhT6+bIhAmsJCDmvCX9B33J6We7/677/598Azz6E/rx5f3b775yvDee09nL/c///zK8OGHewc/5R8/Dr9v/EHU5ube7LKH/z3sjIlDYGkEFm5Ql6Y5N0qAQJyAQY2rRCACBFoFDGprc3ITIBAnYFDjKhGIAIFWAYPa2pzcBAjECRjUuEoEIkCgVcCgtjYnNwECcQIGNa4SgQgQaBUwqK3NyU2AQJyAQY2rRCACBFoFDGprc3ITIBAnYFDjKhGIAIFWAYPa2pzcBAjECRjUuEoEIkCgVcCgtjYnNwECcQIGNa4SgQgQaBUwqK3NyU2AQJyAQY2rRCACBFoFDGprc3ITIBAnYFDjKhGIAIFWAYPa2pzcBAjECRjUuEoEIkCgVcCgtjYnNwECcQIGNa4SgQgQaBUwqK3NyU2AQJyAQY2rRCACBFoFDGprc3ITIBAnYFDjKhGIAIFWAYPa2pzcBAjECRjUuEoEIkCgVcCgtjYnNwECcQIGNa4SgQgQaBVYuX///n5reLkJnLfAtWvXhqtXr573w3q8EgGDWlKUmBcvYEwvvoP0BAY1vSH5IgSMaUQN8SEManxFAl60gDG96AZ6Ht+g9nQl6QUIGNMLQC9+SINaXJ7o8xUwpvP1XcSrG9RFbNU9nVnAmJ6ZcCkvYFCXsnY3/SIBY+p8nFbAoJ5WzvctpIAxXchaz+2mDOq5UXugdAFjmt5Qfj6Dmt+RhOcgYEzPAXkJHsKgLkHJbvHFAsbUCZlKwKBOJek6lQLGtLK22NAGNbYaweYtYEznLbx81zeoy9e5Ox6GwZg6BvMQMKjzUHXNaAFjGl1PdTiDWl2f8C8rYExfVszXv4yAQX0ZLV9bLWBMq+urCG9QK2oS8qwCxvSsgr7/JAIG9SRKvqZawJhW11cV3l/SV1WXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBAxqVV3CEiCQLGBQk9uRjQCBKgGDWlWXsAQIJAsY1OR2ZCNAoErAoFbVJSwBAskCBjW5HdkIEKgSMKhVdQlLgECygEFNbkc2AgSqBP4Lp5wPbedfB8kAAAAASUVORK5CYII=`

# But this is working fine: 
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAVQAAAD6CAYAAAD+87+fAAAAAXNSR0IArs4c6QAADfVJREFUeF7t3T+PVeUWwOFlQ2PE2pBrKKzARGqjDVpZ2GsuJgYSC0JCR4XFkJjYmZtYCckNaGL8DMJn0AIqkttc4wcgNjbe7JGNh+MZhjuzznvWXjxTMsz751mbX87805ci4o/wRoAAAQLHFnhJUI9taAECBAjsCwiqB4EAAQJJAoKaBGkZAgQICKpngAABAkkCgpoEaRkCBAgIqmeAAAECSQKCmgRpGQIECAiqZ4AAAQJJAoKaBGkZAgQICKpngAABAkkCgpoEaRkCBAgIqmeAAAECSQKCmgRpGQIECAiqZ4AAAQJJAoKaBGkZAgQICKpngAABAkkCgpoEaRkCBAgIqmeAAAECSQKCmgRpGQIECAiqZ4AAAQJJAoKaBGkZAgQICKpngAABAkkCgpoEaRkCBAgIqmeAAAECSQKCmgRpGQIECAiqZ4AAAQJJAoKaBGkZAgQICKpngAABAkkCgpoEaRkCBAgIqmeAAAECSQKCmgRpGQIECAiqZ4AAAQJJAoKaBGkZAgQICKpngAABAkkCgpoEaRkCBAgIqmeAAAECSQKCmgRpGQIECAiqZ4AAAQJJAoKaBGkZAgQICKpngAABAkkCgpoEaRkCBAgIqmeAAAECSQKCmgRpGQIECAiqZ4AAAQJJAoKaBGkZAgQICKpngAABAkkCgpoEaRkCBAgIqmeAAAECSQKCmgRpGQIECAiqZ4AAAQJJAoKaBGkZAgQICKpngAABAkkCgpoEaRkCBAgIqmeAAAECSQKCmgRpGQIECAiqZ4AAAQJJAoKaBGkZAgQICKpngAABAkkCgpoEaRkCBAgIqmeAAAECSQKCmgRpGQIECAiqZ4AAAQJJAoKaBGkZAgQICKpngAABAkkCgpoEaRkCBAgIqmeAAAECSQKCmgRpGQIECAiqZ4AAAQJJAoKaBGkZAgQICKpngAABAkkCgpoEaRkCBAgIqmeAAAECSQKCmgRpGQIECAiqZ4AAAQJJAoKaBGkZAgQICKpngAABAkkCgpoEaRkCBAgIqmeAAAECSQKCmgRpGQIECAiqZ4AAAQJJAoKaBGkZAgQICKpngAABAkkCgpoEaRkCBAgIqmeAAAECSQKCmgRpGQIECAiqZ4AAAQJJAoKaBGkZAgQICKpngAABAkkCgpoEaRkCBAgIqmeAAAECSQKCmgRpGQIECAiqZ4AAAQJJAoKaBGkZAgQICKpngAABAkkCgpoEaRkCBAgIqmeAAAECSQKCmgRpGQIECAiqZ4AAAQJJAoKaBHnsZX6KiDci4uVjr2SBF0ngt4h4GBHnXqRL172roFaZzR8R8bOoVhnHIs4xx/StiJj+JXvbuYCg7nwEjw8wBXV6uxAR31Y5lHOUFvhnRNx5fEJBLTEqQS0xhogQ1CqTWM45BLXcrAS1ykimVxrTPxCvUKtMpP455qBOn9FMz423nQsI6s5H8PgAglplEss5h6CWm5WgVhmJoFaZxHLOIajlZiWoVUYiqFUmsZxzCGq5WQlqlZEIapVJLOccglpuVoJaZSSCWmUSyzmHoJablaBWGYmgVpnEcs4hqOVmJahVRiKoVSaxnHMIarlZCWqVkQhqlUks5xyCWm5WglplJIJaZRLLOYeglpuVoFYZiaBWmcRyziGo5WYlqFVGIqhVJrGccwhquVkJapWRCGqVSSznHIJablaCuo2RzHHcxtpLXfMfEfHfHR3+dET8Z0d7V9323xHxadXDLfdcgrqN2Qnq31UFdRtP2tHXFNSj2z3jIwV1K6xHWNSn/EdAe8E/xKf85R4AQa0yEkGtMonlnENQy81KUKuMZMdB3dvbi2vXrsWJEyc2ijx48CDOnj371Pvu378fZ86ceerPfvnll/jkk0/i448/josXLz55361bt+LSpUtx4cKF+Prrr+OVV155pvzqfoedbV7o7t278f777/9t3R9//DHee++9p/58032mv7B+p/nc0/tu3ry58U47e4QEdWf0B20sqFVGsuOgzgxzUObgrMZsU4RW378an2m98+fPx40bN+L69etx7969/S3moP7www/7gZ1j9/vvv8eXX34Zn3/++f6fvfbaa08CPu1x9erV+Oqrr/bfP5/x0aNHcfny5bhz587+n/36669PBXU13qtnn8O4uufqY7B6p/W/s+lOO3uEBHVn9IJajn7tQEWDuvqqbTVg8+mPEtTPPvss3nnnnf0lNgV1CuHq35n2OHfuXHz44Yf7H7MpqOt/Zwrf7du349SpUzG/ap6j/jx3evvtt+Pdd9/df8W+em9Brf4Pabfn8wp1t/5/7b6AoG4K0/8b1HXuTUE9bCSbgrr+Mavn2vSlgNVP39dfWU8fe/LkyXjzzTeffKlgfoUrqIdN58V+v6Aed/7NfkTqftyPM3EmHsSDOBtn42bcjIvx59dCb8WtuBSXnhLbi724FtfiRJz46/2Pf0TqeeKzraCuft10PZjTBfb+tRfXrvx57vmuT151x16cjJNxNa7G7DG9727cjS/ii7gRN+J6XI978eeXMdq8+VGqY49SUI9L2DSoqyyP4lFcjstx58n/BP6v93YP6vk4H7fjdpyKU/uX/j6+j9fjdUE97r+bph8vqFUGW/RT/sO+FnnYp/zTN5Pmr31uot7ZK9SVn2pY/2bb/Cn/dPbpbfWbW9M3qR4+fBhXrlx58o22nT1Cvim1M/qDNhbUKiMpGtSJ57CvN84/brXpu/y7CmrG11DnoK4bbPpa8k4eI0HdCfuzNhXUKiNZaFBXX72tf/Nnet8HH3wQH3300YHK23qFOm04f/PqWd/lP+gbbdM3pVaDOq03n1VQq/yjqXcOQa0yk6JBXQ3mph+bWg3X+o8XffPNN/Hdd9/t/+zoQW/bDOrqlytWYz+/4j7oPtP7T58+vfGXBKZIv/rqq/u/vLD6Y1g7eYy8Qt0Ju1eo5dg3HGjHQT3st5EOe1W2/ttIB/3Q/Hzzg35j6qDfYJo+7qAzHvQbUvNeR/1NqU13fp6fXBj2uAnqMOrn3cgr1OeV2vbf23FQt309629BQFC3gHq8JQX1eH6bP7rZj1KlEPnP96Uwpi3iZ07TKFcXEtRtsArq31UFdRtP2tHXFNSj2z3jIwV1K6xHWNSn/EdAe8E/xKf85R4AQa0yEkGtMonlnENQy81KUKuMRFCrTGI55xDUcrMS1CojEdQqk1jOOQS13KwEtcpIBLXKJJZzDkEtNytBrTISQa0yieWcQ1DLzUpQq4xEUKtMYjnnENRysxLUKiMR1CqTWM45BLXcrAS1ykgEtcoklnMOQS03K0GtMhJBrTKJ5ZxDUMvNSlCrjERQq0xiOecQ1HKzEtQqIxHUKpNYzjkEtdysBLXKSAS1yiSWcw5BLTcrQa0ykj8eH+RCRHxb5VDOUVpgDup0yOlfsredCwjqzkfw+ACCWmUSyzmHoJablaBWGckU1J8j4o2IeLnKoZyjtMBvEfEwIt7yCrXKnAS1yiR+EtMqo1jUOeaonlvUqdseVlDbjtbFCBAYLSCoo8XtR4BAWwFBbTtaFyNAYLSAoI4Wtx8BAm0FBLXtaF2MAIHRAoI6Wtx+BAi0FRDUtqN1MQIERgsI6mhx+xEg0FZAUNuO1sUIEBgtIKijxe1HgEBbAUFtO1oXI0BgtICgjha3HwECbQUEte1oXYwAgdECgjpa3H4ECLQVENS2o3UxAgRGCwjqaHH7ESDQVkBQ247WxQgQGC0gqKPF7UeAQFsBQW07WhcjQGC0gKCOFrcfAQJtBQS17WhdjACB0QKCOlrcfgQItBUQ1LajdTECBEYLCOpocfsRINBWQFDbjtbFCBAYLSCoo8XtR4BAWwFBbTtaFyNAYLSAoI4Wtx8BAm0FBLXtaF2MAIHRAoI6Wtx+BAi0FRDUtqN1MQIERgsI6mhx+xEg0FZAUNuO1sUIEBgtIKijxe1HgEBbAUFtO1oXI0BgtICgjha3HwECbQUEte1oXYwAgdECgjpa3H4ECLQVENS2o3UxAgRGCwjqaHH7ESDQVkBQ247WxQgQGC0gqKPF7UeAQFsBQW07WhcjQGC0gKCOFrcfAQJtBQS17WhdjACB0QKCOlrcfgQItBUQ1LajdTECBEYLCOpocfsRINBWQFDbjtbFCBAYLSCoo8XtR4BAWwFBbTtaFyNAYLSAoI4Wtx8BAm0FBLXtaF2MAIHRAoI6Wtx+BAi0FRDUtqN1MQIERgsI6mhx+xEg0FZAUNuO1sUIEBgtIKijxe1HgEBbAUFtO1oXI0BgtICgjha3HwECbQUEte1oXYwAgdECgjpa3H4ECLQVENS2o3UxAgRGCwjqaHH7ESDQVkBQ247WxQgQGC0gqKPF7UeAQFsBQW07WhcjQGC0gKCOFrcfAQJtBQS17WhdjACB0QKCOlrcfgQItBUQ1LajdTECBEYLCOpocfsRINBWQFDbjtbFCBAYLSCoo8XtR4BAWwFBbTtaFyNAYLSAoI4Wtx8BAm0FBLXtaF2MAIHRAoI6Wtx+BAi0FRDUtqN1MQIERgsI6mhx+xEg0FZAUNuO1sUIEBgtIKijxe1HgEBbAUFtO1oXI0BgtICgjha3HwECbQUEte1oXYwAgdECgjpa3H4ECLQVENS2o3UxAgRGCwjqaHH7ESDQVkBQ247WxQgQGC0gqKPF7UeAQFsBQW07WhcjQGC0gKCOFrcfAQJtBQS17WhdjACB0QKCOlrcfgQItBUQ1LajdTECBEYLCOpocfsRINBWQFDbjtbFCBAYLSCoo8XtR4BAWwFBbTtaFyNAYLTA/wCR3aA98bGZpwAAAABJRU5ErkJggg==`

# You can see my past project for reference: [click](https://darling-gnome-b183e7.netlify.app/)

# Reason: (my opinion)
I think this is under the iframe tag and the main reason is that it is a separate file.

**Comment by Spyware007** [comment]
@vaibhav-xt It's fine no worries!

**Comment by Spyware007** [comment]
@Souravvmishra , @Mayank1170 , @manoranjanonline , @PriyankaTamhankar01 
Would you like to work on this?

**Comment by Souravvmishra** [comment]
Sure,

**Comment by Mayank1170** [comment]
Yeah ! 
I would like to :)

**Comment by Spyware007** [comment]
@Souravvmishra @Mayank1170 Please collaborate on this one!

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
