### ISSUE TITLE
Add animated buttons using Javascript. 😍

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#54]
Currently, there are no buttons that are implemented using JavaScript.  🚀
Try to implement buttons using javascript. 🌟

**Comment by atiqueakhtar** [comment]
Hi @Spyware007 I will raise a PR to implement a button using javascript.

**Comment by Spyware007** [comment]
Hii @atiqueakhtar Please raise a PR, and I will review and merge it. 🤩
Make sure the Javascript file should be named app.js

**Comment by Sathasivamthirumoorthi** [comment]
please assign this to me

**Comment by Spyware007** [comment]
@Sathasivamthirumoorthi You can make a PR, I will merge it.

**Comment by OneAutumLeaf** [comment]
hi @Spyware007 
i have added both buttons with/out javascript . Can u Merge the PR

**Comment by riddhitech** [comment]
Please assign me this issue.

**Comment by Shivam-Katare** [comment]
Hi @Spyware007, can I work on this issue?

**Comment by Spyware007** [comment]
@riddhitech @Shivam-Katare You can make a PR.

**Comment by amrit2611** [comment]
#### Was this issue resolved? If not, I would love to contribute

**Comment by Spyware007** [comment]
@amrit2611 You can contribute.

**Comment by amrit2611** [comment]
> @amrit2611 You can contribute.

Hey! I just created a PR where I implemented a hover animation using JavaScript. 
Kindly check it out.

**Comment by sagnik3788** [comment]
Please assign me this issue. I want to contribute under GSSoC.

**Comment by NehaShrama** [comment]
I would like to work on this issue. Please assign it to me under GSSoC'23.

**Comment by dassoumen98** [comment]
I would like to work on this issue. Please assign it to me under GSSoC'23.

**Comment by Spyware007** [comment]
@sagnik3788  and @NehaSharma101 
You can work on this create an issue and mention this issue in that and start working.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️ 
https://www.linkedin.com/in/om-gawande/

**Comment by sagnik3788** [comment]
ok @Spyware007

**Comment by iLakshya** [comment]
Please assign this task to me

**Comment by Spyware007** [comment]
@iLakshya 
You can work on this create an issue and mention this issue in that and start working,  I will assign it to you!.

Make sure to ⭐ the repo and follow me.
I would love to connect with you all. ❤️
https://www.linkedin.com/in/om-gawande/

**Comment by Siddharth961** [comment]
I made a pull request for a button which makes wave on hover using javascript. Please checkmit out. I am currently contributing under GSSOC'23.

**Comment by Siddharth961** [comment]
@Spyware007 
Hey just made a pull request for a button, made using javascript. Kindly, check it out

**Comment by Siddharth961** [comment]
@Spyware007 made a new button, kindly check it.
