### ISSUE TITLE
Dividing the buttons into different category boxes for easily finding the right button.  {Gssoc'23}

### ISSUE THREAD

**Issue by SrishtiSonam** [Spyware007/Animating-Buttons#542]
Dividing these button in different category boxes for easy differentiation.
The categories can be type1, type2, ...
Some general types on buttons present in your website:-
1 . neon buttons, social media icons buttons, glow on hover buttons, color change on hover buttons, size-change on hover buttons, changing effect on hover buttons 
2. Most used buttons, Simple buttons, Complex buttons , hover buttons, click buttons, etc.

Assign me this issue under gssoc'23.

**Comment by VishalVinayRam** [comment]
can u assign this to me

**Comment by Souravvmishra** [comment]
I am also curious about the approach that would be used here. 
Make sure you first understand the approach currently used.
Best Of Luck

**Comment by Spyware007** [comment]
@SrishtiSonam Are you working on this?

**Comment by SrishtiSonam** [comment]
Yes, I will be generating the pull request by this evening.
As some changes are still to be made.

**Comment by SrishtiSonam** [comment]
Yes, I will share the final layout (progress) with you by this evening.
I have started working on this from yesterday because before that was working on another issue assigned me before this one. As a fresher I raised multiple issues at same time, apologizes for the delay but will complete this task in next three to four days.

**Comment by Souravvmishra** [comment]
Can you explain for now, what logic you would be using for dividing the buttons & how would you fetch the desired buttons from the list belonging to a certain type.

**Comment by SrishtiSonam** [comment]
My idea can be implemented by deciding some sub-divisions' name, then using them as class name for button's div. Then **_sort divs based on their class using React.js._**
import DivSorter from './DivSorter'; { On the basis of class name }

Idea:-
Basically the idea is to dividing these buttons into different categories so that it is easier to find the required button design.
These division can be done on two basis :-
=> Firstly the buttons can be divided on the basis of use. Like different sub-types could be share button, like button, submit/upload button, login/signup button, social media buttons, Purchase/Buy button, Warning buttons, etc.
=> Secondly the possible division could be done on the basis of styling of button. Different sub-divisivion could be live buttons, moving on hover, colour change on hover, neon effect on hover, special effect on hover, buttons styled in object forms.

**Comment by SrishtiSonam** [comment]
@Souravvmishra please confirm my idea. 
So that I can proceed  forward on the coding work.

**Comment by Souravvmishra** [comment]
@SrishtiSonam The idea is great but I'm still not getting the logic behind dividing them. Sorting on the basis of class requires us to add the corresponding class to all the already made buttons. 

Whatever your  idea, You should work on it. So that we can understand that in a better way.

**Comment by SrishtiSonam** [comment]
@Souravvmishra Yes we have to add the corresponding class to all the already made buttons.

**Comment by SrishtiSonam** [comment]
Dear @Souravvmishra ,

I want to sincerely apologize for not being able to resolve the issue I raised #542. I understand the frustration and inconvenience this may have caused you. 

After thoroughly investigating the problem and considering various approaches other than mine, I regret to inform you that I was unable to find a suitable solution within the given constraints. I genuinely appreciate your effort of giving attention to my idea and I'm sorry that I couldn't meet the expectations in this case.

Please know that I value your feedback and the opportunity to learn from this experience. I will make sure to keep this issue in mind for future improvements and enhancements. If there are any other ways I can be of assistance, please do let me know.

Thank you for your understanding and patience. Once again, I apologize for any inconvenience caused.
