### ISSUE TITLE
bug: wrong GitHub username displayed by JS alert dialog box

### ISSUE THREAD

**Issue by hashfx** [Spyware007/Animating-Buttons#546]
![image](https://github.com/Spyware007/Animating-Buttons/assets/69109482/d6f8ad85-c988-4385-9be2-384c61ec2d9a)

**This is a(n):**

- [ ] Update to an existing Animated Button
- [x] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

**Problem:** I have solved 3 issues and created 3 branches and files for each issue by the name ```hashfx_1```, ```hashfx_2```, ```hashfx_3```. When these files are deployed and clicked, it shows my GitHub as ```https://github.com/hashfx_3``` instead of ```https://github.com/hashfx```.

**Suggestion:** Data.js could ask for an optional parameter viz. GitHub user-name. Last data to the items of ```Data.js``` object should be GitHub user-name in case of multiple commits at once.

**Comment by Spyware007** [comment]
@hashfx  Are you going to work on this??

**Comment by hashfx** [comment]
> @hashfx Are you going to work on this??

Alright, I'll see for a solution and then communicate back!

**Comment by hashfx** [comment]
Done ✅
