### ISSUE TITLE
Header and footer of the site is not structured

### ISSUE THREAD

**Issue by chetankhandait** [Spyware007/Animating-Buttons#547]
![image](https://github.com/Spyware007/Animating-Buttons/assets/121539090/1ff5bf5e-c210-4459-8b32-c8aeaf3a3ec4)
please assign me this work under GSSOC23

**Comment by avinasdube** [comment]
bro, i'm unable to get the updated version of this repo on my local machine. can you help ?

**Comment by Spyware007** [comment]
@chetankhandait Assigned to you!

**Comment by Spyware007** [comment]
@avinasdube On your forked repository just sync fork and then pull it in your local machine!

**Comment by avinasdube** [comment]
> @avinasdube On your forked repository just sync fork and then pull it in your local machine!

Okay

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
