### ISSUE TITLE
Remove extra space for the footer

### ISSUE THREAD

**Issue by VSatwika** [Spyware007/Animating-Buttons#561]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

- The footer has extra space below the content which can be eliminated.
- I could also change the color of pagination buttons to yellow so it matches the 'buymeacoffee' button, improving the overall look 
   of the page.

     ![bspace](https://github.com/Spyware007/Animating-Buttons/assets/112561024/675307b0-2448-48a5-9bd6-c0028f30586f)

**Comment by Grace229** [comment]
Please assign this issue to me

**Comment by shivang-16** [comment]
I can fix this issure please assign me to fix this!

**Comment by Spyware007** [comment]
@VSatwika Assigned to you!

**Comment by VSatwika** [comment]
@Spyware007 Hello. I'm unable to make the desired changes. Please assign this to other contributors. Sorry for the inconvenience. Thank you

**Comment by Spyware007** [comment]
@Grace229 @shivang-16 
Would you like to work on this issue??

**Comment by Grace229** [comment]
Yes I’ll love too, please assign it to me

**Comment by shivang-16** [comment]
yes I want to fix this issue

**Comment by UditSharma9999** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by PUJAmangale1221** [comment]
Hello Maintainers, I want to work on this issue can you please assign it to me

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by Grace229** [comment]
Yes I am, I'll send a PR soon

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
