### ISSUE TITLE
Changes in Show Code page

### ISSUE THREAD

**Issue by VSatwika** [Spyware007/Animating-Buttons#564]
- Increasing space between navbar and the button section will give a cleaner look.

**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
![bspace2](https://github.com/Spyware007/Animating-Buttons/assets/112561024/cb1471e1-5fe6-402a-a16b-292d561265cc)

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
