### ISSUE TITLE
want to improve the ui of footer and add a contact form in the footer and also add logo of website 

### ISSUE THREAD

**Issue by lakhan06** [Spyware007/Animating-Buttons#568]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

**Comment by Spyware007** [comment]
@lakhan06 You can work on this
But you have to check other issues too that are similar to this to avoid any merge conflicts.

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
