### ISSUE TITLE
Add a favicon.

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#57]
Create a logo for this website and add this logo as a favicon. 🤩
Save all the logo-related files in an [src/assets](https://github.com/Spyware007/Animating-Buttons/tree/main/src/assets) in a separate folder as a logo.😇

**Comment by srigundeti10** [comment]
@Spyware007  please assign me this task

**Comment by fallen-ecstasy** [comment]
@Spyware007 Please assign this task to me...... will Do this asap!

**Comment by Spyware007** [comment]
@srigundeti10 @fallen-ecstasy I assigned to both of you. The best logo will get merged.

**Comment by fallen-ecstasy** [comment]
@Spyware007 Done! but please merge my Pending PR, so that I can create another

**Comment by Spyware007** [comment]
@srigundeti10  You still can create a logo I will put the one which suits the theme. 😎
@fallen-ecstasy Thanks for Your Contribution. 🌟

**Comment by srigundeti10** [comment]
sorry for delaying it 
I am still working on making this project 
I will submit it within the next 24 hours
so sorry and thanks for waiting till now :)
