### ISSUE TITLE
Redesign the Created By, show code and download button. 🎨 🖌️

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#580]
<img width="406" alt="Screenshot 2023-05-25 at 12 18 08 AM" src="https://github.com/Spyware007/Animating-Buttons/assets/89961974/3c80f772-040c-4ca6-9a44-720de83036f4">

### The above design of the arrangement of created by, show code, and download buttons looks a bit odd.

# NOTE
## - And show code in a similar way.

# [IMP]
## Don't break the logic of any of the buttons!

**Comment by harmeetsingh11** [comment]
I'm in GSSOC'23. Can I work on this issue?

**Comment by Souravvmishra** [comment]
@Spyware007

**Comment by dellarocca99** [comment]
Hi, can I work on this issue?
Thanks in advance :)

**Comment by Spyware007** [comment]
@harmeetsingh11 and @dellarocca99 
Please join the discord channel!

It was already assigned to @Souravvmishra in discord.

You can create other issues!
Keep coding 🚀

**Comment by dellarocca99** [comment]
I did it already and sent you a pull request.

**Comment by Souravvmishra** [comment]
@dellarocca99 Great Job Brother
But Things don't work this way.
There are a set of rules which one has to follow in order to make any contribution.

**Comment by dellarocca99** [comment]
In the description of the issue didn't say that it could be assigned to someone by Discord. 
In GitHub it wasn't assigned to anyone until 20 minutes ago.

**Comment by manoranjanonline** [comment]
Please assign me this issue so that I can resolve it under GSSOC-23

**Comment by Nishusk** [comment]
interesting!
can i work on thi issue?

**Comment by Nishusk** [comment]
interesting!
Can i work on this issue??

**Comment by Nishusk** [comment]
Subject: Help Needed: Resolving Merge Conflicts in Animating-Buttons

Dear Community/Team/Developer,

I hope this message finds you well. I am writing to seek assistance with
resolving merge conflicts in the Animating-Buttons open-source project. I
am facing challenges in resolving the conflicts and would greatly
appreciate any guidance or support you can provide.

Description:
I am currently working on a feature branch called "conflict-resolution,"
which is based on the latest development branch of the project. While
attempting to merge my changes into the main branch, I encountered several
conflicts that I am having difficulty resolving.

I have followed the standard Git conflict resolution process, running
commands such as `git status` and `git diff` to identify the conflicting
files. However, upon reviewing the files, I find it challenging to
determine the conflicting sections and resolve them effectively.

I have also reviewed the project documentation and searched online
resources for guidance, but I haven't been able to find a solution specific
to the conflicts I'm experiencing.

I kindly request your expertise in helping me understand the conflicts more
clearly and guiding me on the appropriate steps to resolve them. It would
be immensely valuable if you could provide insights, techniques, or
specific commands that can assist in identifying and resolving the
conflicts in a smooth and efficient manner.

Additional Information:
- Operating System: Windows
- Git Version: 2.40.1.windows.1
- Development Environment: Visual Studio Code Editor
- Repository Link: [
https://github.com/Nishusk/Animating-Buttons](https://github.com/Nishusk/Animating-Buttons)

I am eager to learn and contribute to the Animating-Buttons project, and
resolving these conflicts will enable me to move forward with my work. Your
assistance will not only help me personally but also benefit the entire
project and its community.

Thank you very much for your time and consideration. I genuinely appreciate
your support in helping me overcome these merge conflicts. Please let me
know if there are any further details or clarifications you require.

Looking forward to your guidance and suggestions.

Best regards,

Nishu Kumari GSSoC '23
GitHub: [Nishusk](https://github.com/Nishusk)
