### ISSUE TITLE
Wrong Github Profile Link 

### ISSUE THREAD

**Issue by Souravvmishra** [Spyware007/Animating-Buttons#584]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [x] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

So Everything goes fine until the user has only one button but if the user has multiple buttons then the link to the github profile of the user breaks because of the extra "_n" at the end as per the naming conventions. 

Would Like To Work On This Issue as for #gssoc2023

**Comment by Spyware007** [comment]
Duplicate #604 , If its not working I will assign this to you!
