### ISSUE TITLE
Add a new button to the list. {GSSoC '23}

### ISSUE THREAD

**Issue by youraj-08** [Spyware007/Animating-Buttons#593]
**This is a(n):**

- [x] Update to an existing Animated Button
- [ ] Any Error
- [] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I want to add a new button to the list or provide an update to the existing ones.

**Comment by rks-031** [comment]
I want to work on this project and add a new button to the list.

**Comment by Spyware007** [comment]
@youraj-08 You can create a PR to make a new button!
I will be assigned it to you in the PR.

@rks-031 You can create a new issue and then a PR.

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them. @youraj-08
