### ISSUE TITLE
Adding a new 2D to 3D transition button using HTML and CSS

### ISSUE THREAD

**Issue by kartikjoshi267** [Spyware007/Animating-Buttons#596]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I wish to add a new animated button that tranforms from 2D to 3D when hovered upon. Sample screenshots are given below:

| Before Hovering | After Hovering |
| --------------------- | ----------------- |
| ![image](https://github.com/Spyware007/Animating-Buttons/assets/96565730/5f392be8-0096-4114-a0a2-764ccb3b063e) | ![image](https://github.com/Spyware007/Animating-Buttons/assets/96565730/7423987d-c715-4087-ba0b-c90f05f56622) |

Please assign this to me as a part of GSSOC'23

**Comment by Spyware007** [comment]
@kartikjoshi267 Assigned to you!
