### ISSUE TITLE
Creating new animation button using HTML and CSS

### ISSUE THREAD

**Issue by saiwali** [Spyware007/Animating-Buttons#598]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

**Comment by Spyware007** [comment]
@saiwali Assigned to you.

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
