### ISSUE TITLE
Adding a section for user to add a new button and attaching it to firebase backend.

### ISSUE THREAD

**Issue by Akanksha-202** [Spyware007/Animating-Buttons#599]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I wanted to add a section for users to add a new button on the website itself. The HTML, CSS, and js code will be taken as input and stored in the backend and then will be retrieved dynamically from there in the already existing card format.
Firebase will be used as the database.

Please assign this issue to me under the GSSoC'23 label:)

**Comment by Spyware007** [comment]
@Akanksha-202 It's a great idea. Assigned to you.
I want to know your approach!
Can we connect on discord for this?
Ping me asap.
