### ISSUE TITLE
 Button not working

### ISSUE THREAD

**Issue by PriyankaTamhankar01** [Spyware007/Animating-Buttons#601]
**This is a(n):**

- [x ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
![image](https://github.com/Spyware007/Animating-Buttons/assets/90240653/1734bbe3-12ef-42f5-aed6-f813921494d9)

**Comment by Spyware007** [comment]
@PriyankaTamhankar01 Assigned to you!
