### ISSUE TITLE
add error page

### ISSUE THREAD

**Issue by PatilHarshh** [Spyware007/Animating-Buttons#617]
404 error page is not added @Spyware007

**Comment by PatilHarshh** [comment]
please assign it to me @Spyware007 i will complete with good ui

**Comment by Spyware007** [comment]
@PatilHarshh Assigned to you!

**Comment by PatilHarshh** [comment]
sure

**Comment by PrernaSingh01** [comment]
I want to collaborate with @PatilHarshh. please assign me as well @Spyware007.

**Comment by PatilHarshh** [comment]
sure @PrernaSingh01 . please assign @Spyware007

**Comment by Spyware007** [comment]
@PrernaSingh01 @PatilHarshh 
Ping me on Discord in dm!

**Comment by PatilHarshh** [comment]
@Spyware007 can you please provide discord id

**Comment by PoorviShetty** [comment]
@PrernaSingh01 Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
