### ISSUE TITLE
created by button not looking attractive

### ISSUE THREAD

**Issue by Shreyans2004** [Spyware007/Animating-Buttons#620]
The Created-by button is not looking attractive and not matching with the orange color .It is translated on hovering which is not looking catchy.

**This is a(n):**

- [ ] Update to an existing Animated Button
- [x] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I can change the styling of the button so that it may look better .Can you assign this task to me?

**Comment by Spyware007** [comment]
@Shreyans2004 Assigned to you.
