### ISSUE TITLE
To Add a new Hover button to the website

### ISSUE THREAD

**Issue by Explorer003** [Spyware007/Animating-Buttons#623]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I would like to add a button which would look like in the image below.
I am eager to contribute to the implementation of this project and collaborate with the development team to ensure its successful integration.
Your feedback and thoughts on this proposal are highly appreciated
![Screenshot (148)-COLLAGE](https://github.com/Spyware007/Animating-Buttons/assets/107935613/58a1fcc2-5357-4406-8b26-2b874f62be29)

**Comment by Spyware007** [comment]
@Explorer003 Assigned to you!

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
