### ISSUE TITLE
New Animated Button

### ISSUE THREAD

**Issue by shraddha761** [Spyware007/Animating-Buttons#625]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

![Screenshot 2023-05-25 105837](https://github.com/Spyware007/Animating-Buttons/assets/106100728/6aaab2df-34b7-49b6-98f6-d04dc361ff5c)

![Screenshot 2023-05-25 105842](https://github.com/Spyware007/Animating-Buttons/assets/106100728/aabdac8c-f67e-4b98-abb2-ca47802e523d)

As this is fully animated button assign this issue to me under GSSOC'23

**Comment by Spyware007** [comment]
@shraddha761 Assigned to you!
