### ISSUE TITLE
Add a new animated button

### ISSUE THREAD

**Issue by Rhythm408** [Spyware007/Animating-Buttons#629]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ *] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

Add a animated moving button-

**Comment by Spyware007** [comment]
@Rhythm408 Assigned to you!

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
