### ISSUE TITLE
Add a new button

### ISSUE THREAD

**Issue by DivyanshiNarang** [Spyware007/Animating-Buttons#630]
**This is a:**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

Adding a new button with the following Hover effect.

Before Hover:
<img width="343" alt="Screenshot 2023-05-26 022346" src="https://github.com/Spyware007/Animating-Buttons/assets/74779601/85c3eecc-953f-437f-9315-25c522358c46">

After Hover:

https://github.com/Spyware007/Animating-Buttons/assets/74779601/e1d6d4c8-c1f9-4556-8d9d-50b97a172276

Please assign this issue to me under Gssoc'23. @Spyware007

**Comment by Azbar-coder** [comment]
Please Assign me this project issues under gssoc 2023 so that I can add some amazing animated buttons

**Comment by Spyware007** [comment]
@DivyanshiNarang Assigned to you!
Hello, @Azbar-coder You can create a new issue along with a new button I will assign to you.

**Comment by Azbar-coder** [comment]
> create a new issue along with a new button I will assign to you.

Means I have to handle one more issue with this new button issue?then u will assigned it to me.Can u helpme replying this

**Comment by Azbar-coder** [comment]
This is a simple button to  with name submit 

Before Adding Animation It looks like

Issues in simple button
> -No animation

> No transition

> No shadow effect

> No Hover effect 

https://github.com/Spyware007/Animating-Buttons/assets/70653674/e9326081-d61a-4073-a0af-940947ba7012

After Adding animation with proper transition and shadow effect it looks like


https://github.com/Spyware007/Animating-Buttons/assets/70653674/80d88401-7b8f-4646-851b-dd685bce2a3f



Please assign me this issue under gssoc 2023 @Spyware007 😊
