### ISSUE TITLE
adding a new button with animation and ui/ux 

### ISSUE THREAD

**Issue by VishalVinayRam** [Spyware007/Animating-Buttons#640]
**This is a(n):**

- [x] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [x] Documentation / README.md changes

**Details:**

**Comment by Spyware007** [comment]
@VishalVinayRam Assigned to you!

**Comment by VishalVinayRam** [comment]
I have sent a pull request please check and accept it
