### ISSUE TITLE
Update Contributed Button with Glass Effect and Color

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#641]
## Update Contributed Button with Glass Effect and Color
I would like to update the existing contributed button to enhance its visual appeal by adding a glass effect and incorporating color. Currently, the button has a simple design, and I believe applying a glassmorphism style will make it more modern and attractive.

### Proposed Changes:
1. Glass Effect: The button will be transformed with a glassmorphism style, which gives it a sleek and transparent appearance. This effect will create a sense of depth and add a touch of elegance to the button.

2. Color Enhancement: To make the button visually appealing and distinguishable, I will introduce colors that align with the overall design scheme. The choice of colors will complement the glass effect and provide a pleasing contrast.

### The updated button will have the following characteristics:
- Glassmorphism style: The button will exhibit transparency and a frosted glass-like appearance.
- Depth and Dimension: The glass effect will give the button a sense of depth, making it visually engaging.
- Attractive Colors: Carefully selected colors will be incorporated to make the button visually appealing and harmonize with the overall design.

This update aims to enhance the user experience and make the button more captivating, ultimately improving its aesthetic value within the interface. I believe these changes will positively impact the overall look and feel of the application.

Any feedback, suggestions, or collaboration regarding these updates are welcome. 
![Screenshot (788)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/0a778996-941f-4234-9a06-16282e7f364b)

**Comment by Spyware007** [comment]
@Nishusk You can keep this button as it is and create a new button with the effect you are suggesting here!

**Comment by Nishusk** [comment]
Sure sir Thank you I'm working on it .
