### ISSUE TITLE
[Navbar] - Fix Alignment of Dark mode & Github Icon

### ISSUE THREAD

**Issue by Ayush9951** [Spyware007/Animating-Buttons#642]
Hi, I am contributor in GSSOC'23.
Dark mode and github Icons are not centered aligned.
I want to work on fixing this small issue.
please assign me this task under label gssoc'23

![Screenshot 2023-05-26 120828](https://github.com/Spyware007/Animating-Buttons/assets/60573378/fe4bde59-be4f-4ca9-973e-7aa066d0a275)

**Comment by adity2911** [comment]
Hey there I have completed the task and am waiting for the PR to be merged. look into #667 and close this issue if you want to.

**Comment by Spyware007** [comment]
@adity2911 Hello please dm me on Discord!
