### ISSUE TITLE
Pagination breaking responsiveness in mobile view! 😰😕

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#643]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

When viewing on mobile view because of the pagination buttons the responsiveness of the website is getting distorted.
If more buttons are added then we are able to scroll horizontally too.
We don't want this behavior.

> # The pagination should be like

< 1 2 3 .... 9 10 11 >
where < Previous Page
          , > Next Page
1,2,3,9, 10, 11 are the respective page number.

**Comment by Spyware007** [comment]
Assigned to you @Ayush9951

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by Ayush9951** [comment]
Yes @PoorviShetty , need some more time to fix this issue. 
Once I manage to add this feature I'll raise a Pull request and close this issue.

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
