### ISSUE TITLE
Add a unique new animated button

### ISSUE THREAD

**Issue by Archit-Kohli** [Spyware007/Animating-Buttons#645]
## This is a

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

## Details
Adding a new animated button with awesome styling and a creative animation 😉

#
*Please assign this issue to me*

**Comment by Spyware007** [comment]
@Archit-Kohli Assigned to you!
