### ISSUE TITLE
Adding Buttons [GSSOC '23]

### ISSUE THREAD

**Issue by Kalivarapubindusree** [Spyware007/Animating-Buttons#647]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

**Comment by Spyware007** [comment]
@Kalivarapubindusree Assigned to you!

**Comment by Kalivarapubindusree** [comment]
Completed task
