### ISSUE TITLE
Increment-Decrement Button 

### ISSUE THREAD

**Issue by Saurabh-kumar09** [Spyware007/Animating-Buttons#654]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
I want to build an increment - decrementing number button using Javascript.

**Comment by Spyware007** [comment]
@Saurabh-kumar09 Assigned to you!

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by Saurabh-kumar09** [comment]
Yes, I'm working on this issue. Will merge the PR tomorrow.

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
