### ISSUE TITLE
Adding New Button[ Gssoc ]

### ISSUE THREAD

**Issue by Vanshika-Malik2004** [Spyware007/Animating-Buttons#655]
This is a(n) :

- [ ] Update to an existing Animated Button
- [ ]  Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes
Details : 
I wish to add a new button which would look like in the image below. 
This is how the button will look :
![Screenshot (378)](https://github.com/Spyware007/Animating-Buttons/assets/119661171/c716d4a1-385d-4de7-a49e-a21ed3e87d05)
When hovered it will change into this :
![Screenshot (377)](https://github.com/Spyware007/Animating-Buttons/assets/119661171/d5a7df6f-9797-49e9-8803-e00e43752472)

**Comment by Spyware007** [comment]
@Vanshika-Malik2004  Assigned to you!

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
