### ISSUE TITLE
feat: add a new Button

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Spyware007/Animating-Buttons#656]
**This is a(n):**
- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I would like to add a new animated button, but the above checklist doesn't really serve the purpose for someone adding a new button.

It will be similar to this, and I have checked for similar buttons, but I didn't find one (until half the pagination).
![image](https://github.com/Spyware007/Animating-Buttons/assets/74038190/74217a63-6dcc-4c40-8233-e46f7a90df8c)

I would like to contribute to GSSoC'23 by working on this issue. Please assign it to me, and I will start working on it.

**Comment by Spyware007** [comment]
@Anmol-Baranwal  Assigned to you!
