### ISSUE TITLE
New Animated Button

### ISSUE THREAD

**Issue by Rishi-11-2** [Spyware007/Animating-Buttons#657]
I want to contribute to creating a new Animated Button using CSS, HTML and Javascript

**Comment by Spyware007** [comment]
@Rishi-11-2 Assigned to you!

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
