### ISSUE TITLE
{GSSOC'23}Add a new feature 

### ISSUE THREAD

**Issue by thekirti02** [Spyware007/Animating-Buttons#659]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
There is no button to take us to the top of the website. I want to add a feature button on the website to take us to the top of the website.

**Comment by Spyware007** [comment]
@thekirti02 Assigned to you!

**Comment by thekirti02** [comment]
Thanks for assigning me.

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by thekirti02** [comment]
I have not made PR. I will complete it in 2-3 days.
