### ISSUE TITLE
{GSSOC'23} Add logo to social media  

### ISSUE THREAD

**Issue by thekirti02** [Spyware007/Animating-Buttons#660]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

There is a need to add a logo to the social media. I want to improve the UI of this feature. 
Please assign this issue to me. 
<img width="959" alt="issue 7 animating buttons" src="https://github.com/Spyware007/Animating-Buttons/assets/105008820/e7c4d012-78f4-4fa0-bfba-2618a876cb28">

**Comment by Spyware007** [comment]
@thekirti02 I guess there is no need of the UI as we will be changing the landing page!
