### ISSUE TITLE
Added New Button `Dynamic Button`

### ISSUE THREAD

**Issue by Somesh-Mallewar** [Spyware007/Animating-Buttons#661]
Hello @Spyware007 ,

- [x] Adding New Dynamic Button

**Comment by Spyware007** [comment]
@Somesh-Mallewar Assigned to you!

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
