### ISSUE TITLE
Update Style 

### ISSUE THREAD

**Issue by coder-chahal** [Spyware007/Animating-Buttons#666]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
- I want to change the background color of **created by button**.
- I want to change the background color of other button on hover. 
Like this:
![style](https://github.com/Spyware007/Animating-Buttons/assets/110322061/1a3feb59-99a3-4397-b579-a1cdd230fe70)
I would like to work on this issue. Please assign this task to me under GSSoC'23.

**Comment by adity2911** [comment]
Hey there I have completed the task and am waiting for the PR to be merged. look into #667 and close this issue if you want to.

**Comment by Spyware007** [comment]
@coder-chahal Closing this as completed!
You can work on other issues!
