### ISSUE TITLE
Proposal to give design changes of the entire website Along with some other bug fixes.

### ISSUE THREAD

**Issue by adity2911** [Spyware007/Animating-Buttons#668]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [x] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

Changes:
- [x] Redesign of web Pages.
- [x] The alignment of footer to the bottom of the page is now correct.
- [x] Alignment of the top navbar icons are also corrected.
- [x] Updated code base so that the box containing JavaScript code now works properly
- [x] The above change makes sure that the two buy me coffee buttons do not appear.

Please check the PR for the design changes that I made.

**Comment by adity2911** [comment]
Kindly label the level and GSSoC labels in this issue also.

**Comment by Spyware007** [comment]
@adity2911 Amazing suggestions!
Assigned to you!

**Comment by adity2911** [comment]
the pr is open
please review and merge it
