### ISSUE TITLE
Footer 

### ISSUE THREAD

**Issue by Soumyajit2825** [Spyware007/Animating-Buttons#669]
**This is a:**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
I want to upgrade the footer component and make it align in the bottom and give it a colour which will make it more catchy
Please assign me to this issue if you want these changes in the footer

**Comment by adity2911** [comment]
Hey there. This issue has been taken care of by me. You may  look at #667 and close this issue if you want to.

**Comment by Soumyajit2825** [comment]
I was thinking to change the footer text align to center and to give a background to the footer also

**Comment by adity2911** [comment]
i’ll suggest that you start it after the pr has been merged and you sync the repo with your code base

**Comment by Soumyajit2825** [comment]
Ok sure @adity2911

**Comment by Spyware007** [comment]
Closing this as not planned.
@Soumyajit2825 You can work on something else.
