### ISSUE TITLE
Two buy me coffee buttons

### ISSUE THREAD

**Issue by Guli93** [Spyware007/Animating-Buttons#671]
Hey!! There is a bug when you click on show code button you'll get to see 2 buy me coffee button ...one needs to be removed.

please assign me this issue under Gssoc'23 program.

![Screenshot (135)](https://github.com/Spyware007/Animating-Buttons/assets/102940836/d7069663-94da-427b-a558-ebbc759833d1)

**Comment by adity2911** [comment]
hey @Guli93 I was working on this issue and I has been solved. It will be implemented as soon @Spyware007 merge my PR #667 
You can close this Issue.

**Comment by Spyware007** [comment]
@Guli93 you can work on something else.
Closing this as completed.
