### ISSUE TITLE
Adding a animating delete button

### ISSUE THREAD

**Issue by rohanmittal1163** [Spyware007/Animating-Buttons#681]
hey @Spyware007 i want to add a new button in the universe of your website.

**This is a(n):**

- [x] Proposal to the Repository

**Details:**
The button is like a delete button with animation on hover of it. as a GSSOC'23 contributor pls assign me with this update

![image](https://github.com/Spyware007/Animating-Buttons/assets/97821844/7d1d3575-e727-4f72-a01d-a97f8b8720ec)
![image](https://github.com/Spyware007/Animating-Buttons/assets/97821844/e402f33c-b47d-4840-a247-09cd2243d406)

**Comment by Spyware007** [comment]
@rohanmittal1163 Assigned to you!
