### ISSUE TITLE
[NEW] Dark theme and light theme button 

### ISSUE THREAD

**Issue by rohanmittal1163** [Spyware007/Animating-Buttons#682]
hey @Spyware007 I want to add a toggle theme button in your list. this will include two switches ine for dark theme and one for light theme

**This is a(n):**

- [x] Update to an existing Animated Button

![image](https://github.com/Spyware007/Animating-Buttons/assets/97821844/2090eef7-6af3-4231-b757-39c7ca7ef9dc)
![image](https://github.com/Spyware007/Animating-Buttons/assets/97821844/c113fd5b-f27d-4e5c-80ce-85571b21f45d)

**Comment by Spyware007** [comment]
@rohanmittal1163 Assigned to you!

**Comment by rohanmittal1163** [comment]
Added button is the list #797

**Comment by rohanmittal1163** [comment]
@Spyware007 @PoorviShetty 
![image](https://github.com/Spyware007/Animating-Buttons/assets/97821844/3fc884cf-8828-4259-b48b-f4b2b92f4ed4)
what do i do now pls guide me through this

**Comment by rohanmittal1163** [comment]
Hi @PoorviShetty
It seems you have not merged the request pls merge this
