### ISSUE TITLE
Paper Plane Button [GSSOC' 23]

### ISSUE THREAD

**Issue by varunshankar07** [Spyware007/Animating-Buttons#683]
**This is Awesome Paper Plane Button ✈️🔲 That Is Very Clean And Attritive That Can Be Used For Creating Amazing Projects**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

"Introducing the Paper Plane Button! Elevate your Website/Project experience with this sleek and innovative button that allows you to effortlessly catch the attention of the users. 😊🥰✈️

![1](https://github.com/Spyware007/Animating-Buttons/assets/82266277/10e685fd-c7a5-461c-aca7-327b992a02d6)
![2](https://github.com/Spyware007/Animating-Buttons/assets/82266277/860c4abc-46ce-4dd8-8551-797188ac1a10)
![3](https://github.com/Spyware007/Animating-Buttons/assets/82266277/12954dbc-56e2-477c-9d4b-9a894f0447a7)

**Comment by varunshankar07** [comment]
@Spyware007 Really Excited To Work On This.

**Comment by Spyware007** [comment]
@varunshankar07 Assigned to you!
