### ISSUE TITLE
Trash Button With Paper Shredder Animation [GSSOC' 23] 

### ISSUE THREAD

**Issue by varunshankar07** [Spyware007/Animating-Buttons#684]
**This is Cool Trash Button With A Paper Shredder Animation:**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

"Introducing the Trash Button!" Elevate your Website/Project experience with this sleek and innovative button that allows you to effortlessly catch the attention of the users. 😊🥰✈️

![1](https://github.com/Spyware007/Animating-Buttons/assets/82266277/53de4f24-0d47-474a-8119-884730d307a3)
![2](https://github.com/Spyware007/Animating-Buttons/assets/82266277/1e6ea8c4-1a5f-4c36-8ef9-ac9bdcdea81e)
![3](https://github.com/Spyware007/Animating-Buttons/assets/82266277/06637b6a-f94b-4a88-8d37-6990a9d60bbe)

**Comment by Spyware007** [comment]
@varunshankar07 Assigned to you.
