### ISSUE TITLE
Creating a Search Bar

### ISSUE THREAD

**Issue by abhi03ruchi** [Spyware007/Animating-Buttons#688]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I want to add a search bar on the main page via which users can search the button based on its creator's name. 
This would help the user navigate through the project and increase user experience and engagement.

Please assign this task to me under gssoc'23.

**Comment by Spyware007** [comment]
@abhi03ruchi That's an amazing feature.
Assigned to you.

**Comment by abhi03ruchi** [comment]
@Spyware007, I have created a Like Button with a cool animated effect on hover. Issue #692 ; Please review and merge it too.
