### ISSUE TITLE
Order Placed Animation [GSSOC' 23]

### ISSUE THREAD

**Issue by varunshankar07** [Spyware007/Animating-Buttons#689]
**This is An Cool Order Placed Animation:**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

"Introducing the Order Placed Button!" Elevate your Website/Project experience with this sleek and innovative button that allows you to effortlessly catch the attention of the users. 😊🥰🛒

![1](https://github.com/Spyware007/Animating-Buttons/assets/82266277/ede63e66-0643-4d7d-9e96-c6dde0735aff)
![2](https://github.com/Spyware007/Animating-Buttons/assets/82266277/48805fff-801a-4d17-be92-aedb5e8a08dd)
![3](https://github.com/Spyware007/Animating-Buttons/assets/82266277/e938b2c5-e0d7-49c6-ac5c-e474e09fb0bb)
![4](https://github.com/Spyware007/Animating-Buttons/assets/82266277/9aff4c97-48f3-4e68-b7af-160a75de2ab6)
![5](https://github.com/Spyware007/Animating-Buttons/assets/82266277/4842e380-3324-4f8d-acd4-9c4bad8b8955)

**Comment by Spyware007** [comment]
@varunshankar07 Assigned to you!
