### ISSUE TITLE
Confirm Button With Confetti Animation In Three Colours [Dark, White, Grey] [GSSOC' 23]

### ISSUE THREAD

**Issue by varunshankar07** [Spyware007/Animating-Buttons#690]
**This is A Cool And Attractive Confirm Button With A Confetti Animation Which Is Available In Three Colours [Dark, White, Grey]:**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

"Introducing the Confirm Button!" Elevate your Website/Project experience with this sleek and innovative button that allows you to effortlessly catch the attention of the users. 😊🥰🎊

![1](https://github.com/Spyware007/Animating-Buttons/assets/82266277/9637d058-534d-40e2-8bb3-420c0695d3db)
![2](https://github.com/Spyware007/Animating-Buttons/assets/82266277/0cf7d29d-0b22-4e6b-a7dd-add26aacda57)
![3](https://github.com/Spyware007/Animating-Buttons/assets/82266277/6be868f7-9d4e-4c0e-a45c-669669d76743)
![4](https://github.com/Spyware007/Animating-Buttons/assets/82266277/b57bee51-25c7-4e6b-8a72-ba8ddb80ef3d)

**Comment by Spyware007** [comment]
@varunshankar07  Assigned to you!
Just don't add three different buttons, as we have functionality to change colors in the show code page!
