### ISSUE TITLE
Activate Button With Loading Animation [GSSOC' 23]

### ISSUE THREAD

**Issue by varunshankar07** [Spyware007/Animating-Buttons#691]
**This is A Clean And Sleek Activate Button With A Small Waiting Animation:**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

"Introducing the Activate Button!" Elevate your Website/Project experience with this sleek and innovative button that allows you to effortlessly catch the attention of the users. 😊🥰🔃

![5](https://github.com/Spyware007/Animating-Buttons/assets/82266277/6dc116be-3873-4c22-b88f-a8300690d016)
![6](https://github.com/Spyware007/Animating-Buttons/assets/82266277/332129da-a51a-417e-b76a-3d0d608a1af8)
![7](https://github.com/Spyware007/Animating-Buttons/assets/82266277/931d9846-bf80-4cd9-ab73-1c7e8e2fb614)
![8](https://github.com/Spyware007/Animating-Buttons/assets/82266277/0069b010-83dd-4f09-8b7f-f18d46d04d8b)

**Comment by Spyware007** [comment]
@varunshankar07 Assigned to you!
