### ISSUE TITLE
npm WARN deprecated stable@0.1.8

### ISSUE THREAD

**Issue by rks-031** [Spyware007/Animating-Buttons#694]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [x ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / READ
- [x ] ME.md changes

**Details:**
Upon initializing **npm run start**, the following message is shown in the terminal.
**'react-scripts' is not recognized as an internal or external command, operable program or batch file.**
To eliminate that: I used **npm install** to acquire the missing dependencies.

But during **npm install**, the following error occured.
**npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility**

**Following the screenshots of the issues that occured**
![err-1](https://github.com/Spyware007/Animating-Buttons/assets/103258259/31b0cc38-1f89-412a-9099-67e28d954bec)
![err-2](https://github.com/Spyware007/Animating-Buttons/assets/103258259/8f0fedfb-cacd-4206-a021-9ac0257331f0)

The warning message received shown in the above file indicates that the package 'stable' you have installed is deprecated. The 'stable' package was previously used to provide a stable sorting algorithm for older versions of JavaScript that did not guarantee the stability of the Array#sort() method. However, modern versions of JavaScript now ensure that Array#sort() is a stable sort, making the 'stable' package unnecessary.

The warning message suggests referring to the compatibility table on MDN (Mozilla Developer Network) to understand the browser compatibility of the Array#sort() method. The table provides information about which browser versions support stable sorting using Array#sort().

To address this issue:
we can simply use the command: **npm update stable**

After this when we again run the command: **npm run start**, the website is working just fine.
**Here's the screenshot of the same.**
![err-corr](https://github.com/Spyware007/Animating-Buttons/assets/103258259/c2fa0b65-f6ff-44bc-9355-0e282ee42c50)

So I would request you to kindly assign the task of updating the Readme file of the project so that I can mention how to work on the terminal if similar error occurs for an user so that the project can be used efficiently and smoothly.

**A demo of how I can clearly illustrate the measures to taken if the above mentioned error arises is shown below:**
![readme_update](https://github.com/Spyware007/Animating-Buttons/assets/103258259/66936fe9-3d3c-4f6e-a9e3-79aa3b47c93b)

**Comment by Spyware007** [comment]
@rks-031  Is this warning giving any error?

**Comment by rks-031** [comment]
@Spyware007 Yes, due to this, I was not able to view the webpage. There is no error shown in the terminal, just a lot of warnings but if the **scripts** are  deprecated it can give users a real hard time to get to know what is going wrong.

So it would be better to either make ammendments in the script dependencies or give correct illustrations in the **README file** to users regarding how to move ahead if such warnings are encountered.

**Comment by Spyware007** [comment]
@rks-031 Ok Assigned to you!

**Comment by rks-031** [comment]
@Spyware007 What ammendments do I have to make...other than the README file ??

**Comment by Spyware007** [comment]
@rks-031 Apart from Readme.md nothing else!
I will look into it and fix this!

**Comment by rks-031** [comment]
@Spyware007  for ammendment of README.md file I've already done the PR

**Comment by Spyware007** [comment]
@rks-031 I will merge it asap.

**Comment by rks-031** [comment]
@Spyware007  thanks a lot for giving me the opportunity to do my first contribution for GSSoc'23:-)
