### ISSUE TITLE
docs: fix incorrect navigational link [GSSoC'23]

### ISSUE THREAD

**Issue by 0xabdulkhalid** [Spyware007/Animating-Buttons#696]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [x] Documentation / README.md changes

**Details:**
- The navigational link of `public/Buttons` is pointing towards `https://github.com/Spyware007/Animating-Buttons/blob/main/src/components/Main/Main.jsx`
- Actually it want to point to `https://github.com/Spyware007/Animating-Buttons/tree/main/public/Buttons`
- Screenshot from the code
![Screenshot 2023-05-28 at 09-53-39 Spyware007_Animating-Buttons Explore Amazing Buttons animation for your next project  🤩An initiative by GDSC-DYPCOE for Hactoberfest  🚀](https://github.com/Spyware007/Animating-Buttons/assets/92252895/ca5ee870-d79e-4f46-970c-d5870340888a)
- Assign this is issue under GGSoC'23 for me!

**Comment by Spyware007** [comment]
@0xabdulkhalid Assigned to you!
