### ISSUE TITLE
Enhance the footer appearance

### ISSUE THREAD

**Issue by priyam212001** [Spyware007/Animating-Buttons#700]
Hey, @Spyware007  I want to change the footer and place everything in systematic order.
![Screenshot 2023-05-28 103526](https://github.com/Spyware007/Animating-Buttons/assets/97357814/bada3da5-4675-4fc3-8345-c162dfa5730a)

**Comment by Spyware007** [comment]
@priyam212001  We have only one route the landing page.
So how are you going to change the design on the basis of only one route!

**Comment by priyam212001** [comment]
I will only work in the footer section and for the footer you have a separate file. So, that will not be a problem.

**Comment by Spyware007** [comment]
@priyam212001 I am saying that the design you had shown in the above image, doesn't matches the requirements of this project!

As we don't have any ABout, Experience, Service and Contact pages!

**Comment by priyam212001** [comment]
I think you mean the things in image like home or services and all. Am I
right?

**Comment by priyam212001** [comment]
What are the requirements it doesn't match can you give example?

**Comment by priyam212001** [comment]
Ok, no issues I will add on the rest of the things properly except that because the footer just looks simple I can add on some designs.

**Comment by Spyware007** [comment]
@priyam212001 You can send designs here!

**Comment by priyam212001** [comment]
Here is the design. In this image ignore the floating nav if you don't want it in your project rest will be the design.
And I can also add this floating nav to your project and I will add features like the home button and contact us in the nav. Otherwise, just ignore the floating nav and see the rest of the design.


![Screenshot 2023-05-29 101644](https://github.com/Spyware007/Animating-Buttons/assets/97357814/8cd1edaf-d62f-4f20-ba54-0f6fdee46e1c)
![Screenshot 2023-05-29 101716](https://github.com/Spyware007/Animating-Buttons/assets/97357814/bc05ef45-2ffc-44f4-b568-0d85628c898d)

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
