### ISSUE TITLE
LOG OUT BUTTON

### ISSUE THREAD

**Issue by Killer2OP** [Spyware007/Animating-Buttons#703]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
Log out button with a man falling down animation.
Assign me this under GSSoC'23

https://github.com/Spyware007/Animating-Buttons/assets/111378171/64f61852-cb9c-4e90-9c7a-92c62b7fadc9

**Comment by Spyware007** [comment]
@Killer2OP Assigned to you!
