### ISSUE TITLE
SEND BUTTON

### ISSUE THREAD

**Issue by Killer2OP** [Spyware007/Animating-Buttons#704]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
Send Button with Paper plane flying animation.
Assign me this under GSSoC'23

https://github.com/Spyware007/Animating-Buttons/assets/111378171/7c8b1b31-2c5d-4a7d-9dab-0e4e38f92c5e

**Comment by Spyware007** [comment]
@Killer2OP Assigned to you!
