### ISSUE TITLE
ADD BUTTON

### ISSUE THREAD

**Issue by Killer2OP** [Spyware007/Animating-Buttons#705]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
Add Button with a animation to add various type of files.
Assign me this under GSSoC'23

https://github.com/Spyware007/Animating-Buttons/assets/111378171/ddfcf1f8-c0a3-4af9-b24f-7f6db489a613

**Comment by Spyware007** [comment]
@Killer2OP Assigned to you!
