### ISSUE TITLE
Slanting YES/No button under GSSOC23

### ISSUE THREAD

**Issue by midhun-developer** [Spyware007/Animating-Buttons#707]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I would like to add a new button animation which upon hovering gives animation to the selected button

YES/NO Slanted Button with hover effects

Tech Stack : Html, CSS.

ScreenShots:
<img width="824" alt="yes-no-button" src="https://github.com/Spyware007/Animating-Buttons/assets/82802499/b258c77e-c84b-48bf-981e-d6ab72bd1a8b">

@Spyware007  Please assign this issue on GSSOC23 to me!

**Comment by Spyware007** [comment]
@midhun-developer Assigned to you!
