### ISSUE TITLE
Adding new hover button

### ISSUE THREAD

**Issue by riyaVerma1726** [Spyware007/Animating-Buttons#712]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
Hello @PoorviShetty  and @Spyware007 . I went through all the issues and would like to add a new button besides these amazing ones. Here's what I made.

Before hovering
![Screenshot 2023-05-28 153543](https://github.com/Spyware007/Animating-Buttons/assets/114503561/9df0cce8-e273-4986-b920-8dd08f26b837)

After hovering
![Screenshot 2023-05-28 153552](https://github.com/Spyware007/Animating-Buttons/assets/114503561/f926f2d2-8102-4ec8-be4d-b5eb742b6910)

Kindly assign me this issue.
Thankyou.

**Comment by Spyware007** [comment]
@riyaVerma1726 Assigned to you!

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.

**Comment by riyaVerma1726** [comment]
My PR has already been merged.
Thankyou for reminding me. I will just  close this issue.
