### ISSUE TITLE
Adding a new button with neon hover effect

### ISSUE THREAD

**Issue by ann29-tdk** [Spyware007/Animating-Buttons#722]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

**Comment by Spyware007** [comment]
@ann29-tdk Aasigned to you!

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
