### ISSUE TITLE
adding a new button 

### ISSUE THREAD

**Issue by Sushilverma002** [Spyware007/Animating-Buttons#723]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
want to add new button hover , it look like this

https://github.com/Spyware007/Animating-Buttons/assets/114687502/350da834-18df-409d-a915-f7926680f814

**Comment by Spyware007** [comment]
@Sushilverma002 Assigned to you!

**Comment by Sushilverma002** [comment]
please check out the PR. #725
