### ISSUE TITLE
Twitter logo background not attractive

### ISSUE THREAD

**Issue by Shreyans2004** [Spyware007/Animating-Buttons#726]
The twitter logo has a black background,which is not looking attractive.
![WhatsApp Image 2023-05-28 at 22 17 35](https://github.com/Spyware007/Animating-Buttons/assets/128773151/71a75462-b03a-4160-878a-e76ea33cd894)
-------------------------------------------------------------------------------------------------
I can change the background so it looks like the below photo .
![WhatsApp Image 2023-05-28 at 22 17 42](https://github.com/Spyware007/Animating-Buttons/assets/128773151/22884bee-107d-4da6-921f-62988893f3a3)

**This is a(n):**

- [ ] Update to an existing Animated Button
- [x] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

Can you assign this task to me?

**Comment by Spyware007** [comment]
@Shreyans2004 Assigned to you!
