### ISSUE TITLE
Fixing buttons

### ISSUE THREAD

**Issue by Soumyajit2825** [Spyware007/Animating-Buttons#730]
**This is a(n):**

- [x] Update to an existing Animated Button
- [x] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
![Screenshot 2023-05-29 000321](https://github.com/Spyware007/Animating-Buttons/assets/100519291/f3994564-6e37-4465-b8c3-da41e53f1ee2)

![Screenshot 2023-05-29 000312](https://github.com/Spyware007/Animating-Buttons/assets/100519291/e3efd85b-41c8-4c1f-8ebf-4f6ad984d3b6)

These 2 buttons have errors

- 1st button's text is not visible due to larger size
- 2nd is not a button there may be some error in the code
- I want to add a button in place of 2nd button which I have provided through the screen-shot

Please assign me in these issues @Spyware007

**Comment by Spyware007** [comment]
@Soumyajit2825 Assigned to you!
