### ISSUE TITLE
Adding Hover button with bottom detail [GSSOC'23]

### ISSUE THREAD

**Issue by sohil1234** [Spyware007/Animating-Buttons#732]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I would like animated button which on hovering would give bottom detail effect.
 **Preview**

https://github.com/Spyware007/Animating-Buttons/assets/34830305/c4fb6c66-a581-43c4-8fc2-78f4436e1e4a

Pls assign this issue to me for GSSOC'23

**Comment by Spyware007** [comment]
@sohil1234 Assigned to you!

**Comment by PoorviShetty** [comment]
Hi, are you still working on this issue? If you've already made a PR with the changes that have been merged then please close the issue. If you have an open PR, please mention this issue number in your PR in order to link them.
