### ISSUE TITLE
Adding new 2 buttons

### ISSUE THREAD

**Issue by Soumyajit2825** [Spyware007/Animating-Buttons#733]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
I want to add 2 new animated buttons

- Hover Effect Button
- Read More button

**Comment by Spyware007** [comment]
@Soumyajit2825 Assigned to you!
Make sure you make 2 different buttons!

**Comment by Soumyajit2825** [comment]
@Spyware007 PR done
Please Check

**Comment by Soumyajit2825** [comment]
@Spyware007 Have you checked my changes ? 😄
