### ISSUE TITLE
Bug FIx 

### ISSUE THREAD

**Issue by Soumyajit2825** [Spyware007/Animating-Buttons#734]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [x] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
In the navbar the theme button and the github logo button is not alligned in a same style
I want to fix it 
![Screenshot 2023-05-29 002238](https://github.com/Spyware007/Animating-Buttons/assets/100519291/37017618-742f-4250-bfd6-2c0f56decfe6)

**Comment by Spyware007** [comment]
This is already assigned!
