### ISSUE TITLE
Search bar not responsive

### ISSUE THREAD

**Issue by gayatriagarwal19** [Spyware007/Animating-Buttons#736]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [x] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
The search bar on the home screen is not responsive and looks a bit off for mobile view.

![Animated Buttons - Google Chrome 29-05-2023 01_30_05](https://github.com/Spyware007/Animating-Buttons/assets/98116507/12852930-d1b0-4e06-b4ca-f6229c06900f)
![Animated Buttons - Google Chrome 29-05-2023 01_30_12](https://github.com/Spyware007/Animating-Buttons/assets/98116507/8be7732c-a132-4c54-9b6d-5509d699cf75)

I would like to work on this issue, please assign it to me under GSSoC23 @Spyware007

**Comment by Spyware007** [comment]
@gayatriagarwal19 Assigned to you!
