### ISSUE TITLE
 Add a new button

### ISSUE THREAD

**Issue by vishalkumarmahto** [Spyware007/Animating-Buttons#741]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I want to add an animated button.

**Comment by Spyware007** [comment]
@vishalkumarmahto Assigned to you!

**Comment by Umesh7Dixit** [comment]
@Spyware007 i want to Update to an existing Animated Button please assign it to me
