### ISSUE TITLE
Adding a new BUTTON

### ISSUE THREAD

**Issue by SakshiRawat13** [Spyware007/Animating-Buttons#742]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
I wish to add a new animated button to the site

Screenshot:
![image](https://github.com/Spyware007/Animating-Buttons/assets/97942987/dd3cfcee-bf70-4253-927d-d6e61fd159df)

**Comment by Spyware007** [comment]
@SakshiRawat13 Assigned to you!
