### ISSUE TITLE
Add a new button

### ISSUE THREAD

**Issue by riyaVerma1726** [Spyware007/Animating-Buttons#745]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes
- [x] Add a new button

**Details:**
I went through all the issues  of the repo and I want to add a new button.

Before hovering
![image](https://github.com/Spyware007/Animating-Buttons/assets/114503561/81d3febe-3163-48a0-bd84-ba052462a80b)

After hovering
![image](https://github.com/Spyware007/Animating-Buttons/assets/114503561/ad9176fa-7400-4dcf-88af-eeb68a8ad15b)

Kindly assign me this issue.
@PoorviShetty  and @Spyware007

**Comment by Spyware007** [comment]
@riyaVerma1726 Assigned to you!

**Comment by riyaVerma1726** [comment]
Thankyou @Spyware007
