### ISSUE TITLE
Add A new Submit Button with a tick sign on submitting

### ISSUE THREAD

**Issue by HarshSharma0801** [Spyware007/Animating-Buttons#748]
I would like to add a new animating button that can be used in various forms and other applications , that resembles a tick sign on submitting.

**Comment by HarshSharma0801** [comment]
Please assign this issue to me

**Comment by Spyware007** [comment]
@HarshSharma0801 Assigned to you!

**Comment by HarshSharma0801** [comment]
@Spyware007 Sir, Can you review my PR
