### ISSUE TITLE
Navbar Dark Mode

### ISSUE THREAD

**Issue by ManasMadan** [Spyware007/Animating-Buttons#755]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [X] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

The Navbar does not support dark mode as of now

<img width="960" alt="image" src="https://github.com/Spyware007/Animating-Buttons/assets/84731321/55b4cad9-7b63-4feb-a5a7-ff43b875ce0a">

Please assign me this under GSSoC 23. I have the knowledge and experience of required tech stack.

**Comment by Spyware007** [comment]
@ManasMadan Hey it supports dark mode someone messed up with that!
You can fix it!

**Comment by ManasMadan** [comment]
Hi @Spyware007 have solved the issue in the PR #808. Please Check and Merge the same. All Checks have been passed and there are no merge conflicts

**Comment by ManasMadan** [comment]
@Spyware007 Can You Please Check issue #756 and assign it to me
