### ISSUE TITLE
Navbar Icons Not Aligned

### ISSUE THREAD

**Issue by ManasMadan** [Spyware007/Animating-Buttons#756]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [X] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

The icons for dark mode toggle and github are not properly aligned

![image](https://github.com/Spyware007/Animating-Buttons/assets/84731321/f4d1bb96-ff78-48ed-a3a2-d8d9a9f6d815)

Please assign me this under GSSoC 23. I have the knowledge and experience of required tech stack.

**Comment by karananu** [comment]
Please assign me this under GSSoC 23. I have the knowledge and experience of required tech stack.

**Comment by NandineeSrivastava** [comment]
Please assign me this under gsscoc'23

**Comment by avinasdube** [comment]
I have fixed it already guys !
