### ISSUE TITLE
[ New Button ] : Skewed Glowing Neon Button [ GSSOC'23 ]

### ISSUE THREAD

**Issue by md-rosh02** [Spyware007/Animating-Buttons#766]
**This is a( Cool Skewed Glowing Neon Button ):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:
"Introducing the Skewed Glowing Neon Button!" Elevate your Website/Project experience with this sleek and attractive button that allows you to effortlessly catch the attention of the users. **

![Screenshot (36)](https://github.com/Spyware007/Animating-Buttons/assets/132879891/1561ae89-5de8-480f-83aa-c63b0e7d4ec0)

**Comment by CoderKaushik** [comment]
I would like to work on this issue, please assign it to me under GSSoC'23.

**Comment by md-rosh02** [comment]
@CoderKaushik I assign this issue to you😊
Start working on your project.

**Comment by md-rosh02** [comment]
@PoorviShetty @Spyware007 could you look in this matter and assign me this issue.

**Comment by md-rosh02** [comment]
@PoorviShetty @Spyware007 Could you plz assing me this issue???

**Comment by CoderKaushik** [comment]
@md-rosh02 I was assigned this issue and I'm currently working on it.

**Comment by md-rosh02** [comment]
@CoderKaushik who assigned you

**Comment by CoderKaushik** [comment]
@md-rosh02 You did sir 😅. I'm actually new to open source so it took me some time to notice I've no longer been assigned for some reason.

**Comment by CoderKaushik** [comment]
can you please reassign me this issue? I'm about done with it. @md-rosh02

**Comment by md-rosh02** [comment]
@CoderKaushik  bro i'm not the project admin @Spyware007 @PoorviShetty they are admins

**Comment by md-rosh02** [comment]
@Spyware007 @PoorviShetty Could plz assign me this issue ??

**Comment by CoderKaushik** [comment]
@md-rosh02 Okay bro, I actually completed the task. @Spyware007 @PoorviShetty please assign me the task for I've already completed it.

**Comment by md-rosh02** [comment]
@CoderKaushik ok bro you can do this project if they assign you😊

**Comment by md-rosh02** [comment]
I also have this project😊

**Comment by CoderKaushik** [comment]
@md-rosh02 sure bro, please pardon my ignorance for I'm still figuring out how to contribute.
