### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by i-am-yuvi** [Spyware007/Animating-Buttons#77]
**This is a(n):**
- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [x] Documentation / README.md changes

**Details:**
I would like to create a CONTRIBUTING.md file so that new comers can understand the basic principles to contribute to the repositories and other related information

**Comment by i-am-yuvi** [comment]
Please assign me

**Comment by Spyware007** [comment]
@i-am-yuvi  Assigned to you. 🚀
