### ISSUE TITLE
docs: add Pull Request Template

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Spyware007/Animating-Buttons#780]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

- I would like to add a pull request (PR) template to the repository.
- A blank PR template is not effective for reviews, as a template provides structure and an overview of what is needed when opening a PR.
- I am contributing under GSSoC'23 :)

> This repository lacks several things, and I am determined to bring it up to standards so that people can easily contribute. I will be creating various issues, so kindly assign them to me, and I will promptly address them to improve the overall user experience.

**Comment by Spyware007** [comment]
@Anmol-Baranwal Assigned to you!
All the best 🚀
