### ISSUE TITLE
docs: covert markdown issue template to issue form

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Spyware007/Animating-Buttons#781]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
- I am contributing under GSSoC'23 :)

#### Issue Forms

- Issue forms can be more user-friendly than Markdown templates, especially for contributors who may not be familiar with Markdown syntax. With issue forms, contributors can simply fill out the fields and provide the requested information.

- Issue forms can help standardize the information that contributors provide when creating issues. This can help to ensure that all relevant information is provided, reducing the need for follow-up questions and clarifications.

- With issue forms, you can ensure that all issues are created in a consistent format, with the same fields and information requested every time. This makes it easier for maintainers to review and respond to issues quickly.

**Comment by Spyware007** [comment]
@Anmol-Baranwal Assigned to you! 
All the best 💯
