### ISSUE TITLE
Add new Button

### ISSUE THREAD

**Issue by pearlrathour** [Spyware007/Animating-Buttons#783]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

Adding a new button that disappears when clicked.

Before clicking-
![image](https://github.com/Spyware007/Animating-Buttons/assets/99817664/d3bd5a35-66df-4572-a882-7ac76018cd81)

After clicking-
![image](https://github.com/Spyware007/Animating-Buttons/assets/99817664/0eed00aa-4812-4d37-8447-14efc1b4e53f)

**Comment by pearlrathour** [comment]
Please assign me this issue under GSSoC.

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
