### ISSUE TITLE
Want to add a new button with progress animation. Also want to make navbar more responsive for smaller screens.

### ISSUE THREAD

**Issue by Vraj1103** [Spyware007/Animating-Buttons#788]
**This is a(n):**

- [ x] Update to an existing Animated Button
- [ x] Any Error
- [ ] Proposal to the Repository
- [ x] Documentation / README.md changes

**Details:**

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
