### ISSUE TITLE
Add a new click animation "About Us" button [GSSOC'23]

### ISSUE THREAD

**Issue by yaswika0311** [Spyware007/Animating-Buttons#789]
This is a(n):

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

Details:
I want to add a new click animation button. That looks like this
https://github.com/Spyware007/Animating-Buttons/assets/120516365/a48fdc4a-5cd0-4c7d-982d-90f19257613d

please assign me this issue.

**Comment by Michelle031** [comment]
Please assign me this issue
