### ISSUE TITLE
Add new hover effective button

### ISSUE THREAD

**Issue by rimi0602** [Spyware007/Animating-Buttons#796]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I'd like to contribute by adding a new button on the site @Spyware007

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
