### ISSUE TITLE
Improve Button Styling

### ISSUE THREAD

**Issue by kumarankit999** [Spyware007/Animating-Buttons#801]
If we see the below given image before hovering on the button, the button is being totally in white color, and the text inside  is not visible clearly .

![image](https://github.com/Spyware007/Animating-Buttons/assets/111564362/79b9c259-9869-40b7-b3a0-1a3b29f99660)

**Details:**
The text inside the button before hovering shouldn't be in white color font, It should be in Black Font color

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
