### ISSUE TITLE
Icons Not Aligned Properly

### ISSUE THREAD

**Issue by kumarankit999** [Spyware007/Animating-Buttons#802]
If we see below picture, At the top-right corner of any page these both github & dark mode toggle button is not aligned properly .

![image](https://github.com/Spyware007/Animating-Buttons/assets/111564362/8ef9c46c-4aea-4cb4-87ee-a7ddcdc44548)

**Details:**
These both icons are not aligned .So we should do align the toggle button by giving a margin bottom of max 10px

![image](https://github.com/Spyware007/Animating-Buttons/assets/111564362/51d7420f-de88-4254-b3fd-f0ef8819f112)

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by adity2911** [comment]
closing as completed.
