### ISSUE TITLE
Responsive break in mobile view 

### ISSUE THREAD

**Issue by Tushar-sahani** [Spyware007/Animating-Buttons#806]
Responsivness break in mobile view and also there is lot more space left below the footer section that cause the bad user experience.

 
![Screenshot (16)](https://github.com/Spyware007/Animating-Buttons/assets/104075614/a3379811-39ea-4726-a17f-72cc6802a66c)
![Screenshot (17)](https://github.com/Spyware007/Animating-Buttons/assets/104075614/5cd6c7b3-5b68-4675-b335-675d87042881)

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Tushar-sahani** [comment]
Issue Fixed
