### ISSUE TITLE
Want to add css 3D Glowing checkbox buttons

### ISSUE THREAD

**Issue by Kalivarapubindusree** [Spyware007/Animating-Buttons#810]
I want to add 3D checkbox buttons for different icons for wifi, phone call, bluetooth etc

I am gssoc'23 contributor Can you please assign me this task @Spyware007

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
