### ISSUE TITLE
New Button

### ISSUE THREAD

**Issue by shraddha761** [Spyware007/Animating-Buttons#811]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

![Screenshot 2023-05-31 163505](https://github.com/Spyware007/Animating-Buttons/assets/106100728/2bdee4ba-a198-4cf1-9683-17a84ce16415)
![Screenshot 2023-05-31 163512](https://github.com/Spyware007/Animating-Buttons/assets/106100728/41cd49d0-45c2-49ab-a660-6e28fb24dc7e)

**Comment by Spyware007** [comment]
# Please check #1346
