### ISSUE TITLE
Want to add dribble shot button for sending button

### ISSUE THREAD

**Issue by Kalivarapubindusree** [Spyware007/Animating-Buttons#821]
I want to add one amazing  dribble button for sent button  using html ,css ,javascript.
Please assign me this task @Spyware007

**Comment by Kalivarapubindusree** [comment]
Can you please assign @Spyware007

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
