### ISSUE TITLE
Add to cart animated button

### ISSUE THREAD

**Issue by shraddha761** [Spyware007/Animating-Buttons#827]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

![Screenshot 2023-05-31 231823](https://github.com/Spyware007/Animating-Buttons/assets/106100728/1f921732-6891-4bc8-b9ce-7ec66a742e09)
![Screenshot 2023-05-31 231828](https://github.com/Spyware007/Animating-Buttons/assets/106100728/75d589a8-f8a5-4768-8590-9a02031df77b)

**Comment by Spyware007** [comment]
@shraddha761 Assigned to you!
All the best 🚀

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
