### ISSUE TITLE
Animated Send button 

### ISSUE THREAD

**Issue by shraddha761** [Spyware007/Animating-Buttons#828]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

![Screenshot 2023-05-31 232230](https://github.com/Spyware007/Animating-Buttons/assets/106100728/4b23e589-73cd-449e-9c53-31978398c9f5)
![Screenshot 2023-05-31 232241](https://github.com/Spyware007/Animating-Buttons/assets/106100728/45c6e8aa-1f94-47d5-b31d-d9c88423cfc4)

this button is fully  animated . Assign this issue to me under GSSOC'23

**Comment by Spyware007** [comment]
@shraddha761 Assigned to you!
All the best 🚀

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
