### ISSUE TITLE
New animated button

### ISSUE THREAD

**Issue by shraddha761** [Spyware007/Animating-Buttons#829]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

![Screenshot 2023-05-31 232259](https://github.com/Spyware007/Animating-Buttons/assets/106100728/4cd92b88-7985-4d3a-a8c6-56f6ad0da2b1)

![Screenshot 2023-05-31 232311](https://github.com/Spyware007/Animating-Buttons/assets/106100728/55348d12-049f-4308-af1c-a21745ac580c)

assign this issue to me under GSSOC'23

**Comment by Spyware007** [comment]
@shraddha761 Assigned to you!
All the best 🚀
