### ISSUE TITLE
New Animated Button

### ISSUE THREAD

**Issue by coderhersh** [Spyware007/Animating-Buttons#830]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

I want to add an animated button as shown in the picture below. Kindly, assign this issue to me under GSSOC'23.

![Screenshot 2023-06-01 091132](https://github.com/Spyware007/Animating-Buttons/assets/56130865/17c5f536-b199-470f-86ee-7306282756d3)
Before hovering

![Screenshot 2023-06-01 091259](https://github.com/Spyware007/Animating-Buttons/assets/56130865/401d170e-ca7e-42d6-b8e2-528894a52d29)
After hovering

**Comment by Spyware007** [comment]
@coderhersh Assigned to you!
All the best 🚀

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
