### ISSUE TITLE
Adding  new 3D button 

### ISSUE THREAD

**Issue by aishgowda327** [Spyware007/Animating-Buttons#840]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

**Comment by aishgowda327** [comment]
Hey ,I would like add a new 3D flip Button Please assign this issue.

**Comment by Spyware007** [comment]
@aishgowda327 Assigned to you!
All the best! 🚀

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
