### ISSUE TITLE
The website does not have meta tags with descriptions.

### ISSUE THREAD

**Issue by M-A-N-I-K** [Spyware007/Animating-Buttons#841]
-     Issue: The website does not have meta tags with descriptions.
-     Impact: This means that the website is not as visible in search results, and users are less likely to click on the website's links.
-     Resolution: The website should add meta tags with descriptions to all of its pages. This will help the website rank higher in search results and attract more visitors.

**Comment by Spyware007** [comment]
@M-A-N-I-K Assigned to you!
All the best! 🚀

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
