### ISSUE TITLE
Loading Animations Button

### ISSUE THREAD

**Issue by khushi1711** [Spyware007/Animating-Buttons#849]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [X] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

Loading Animations: If our project involves time-consuming processes or data retrieval, we can use loading animations for our buttons. These animations provide visual feedback to users, indicating that the system is processing their request.

I'm GSSOC'23 contributor.
Please assign this issue to me

**Comment by Spyware007** [comment]
@khushi1711 Assigned to you!
All the best 💯

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
