### ISSUE TITLE
Add 3D Flip Button -GSSOC'23

### ISSUE THREAD

**Issue by khushi1711** [Spyware007/Animating-Buttons#850]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [X] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

Hi, I am a contributor in GSSOC'23, I want to add a new Animated button in this project.
I will create a new 3D Flip Button int his project, 
It creates the illusion of a button flipping in a three-dimensional space. When you hover over the button, it performs a flipping animation to reveal the content on the other side. This type of button can add an interactive and visually appealing element to your project.
please assign me this task under label gssoc'23

**Comment by Spyware007** [comment]
@khushi1711 Assigned to you!
All the best🚀

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
