### ISSUE TITLE
Add a creative Footer Scetion

### ISSUE THREAD

**Issue by deepeshgupta3257** [Spyware007/Animating-Buttons#859]
**This is a(n):**

- [ ] Proposal to the Repository
- [x] Documentation / README.md changes
- [x] Update to an existing Animated Button
- [ ] Any Error

**Details:**
I have a quite good solution for your website to add a attractive and informative footer section which will consists of all the important information about the website and all the official social media handles. It can be a better option for the user that uses the website to get information about the website form the footer section also. It's not a problem but to have a good footer makes a website look cool and easy for a user to get the details about the social media handles and many more important part from the bottom also.

![image](https://github.com/Spyware007/Animating-Buttons/assets/108192513/2fe1d749-0077-43f6-9307-a7cf8728ee67)

So, please assign me this issue under GSSOC'23 so, that I can start working on this issue

**Comment by Spyware007** [comment]
# Please check #1346
