### ISSUE TITLE
CSS Animated Button Hover_Effect

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#874]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
"Hi, I am a contributor in GSSOC'23, and I would like to add a new CSS animated button with a hover effect to this project. I will create an animated button that features a star sparkle effect when clicked, along with a gradient background. The button will also undergo transformations in scale and color when hovered over.

This button will create the illusion of a sparkling space when clicked, and it will perform a star animation upon hover to reveal the content on the other side. This type of button can significantly enhance the interactivity and visual appeal of your project.

I kindly request to assign me this task under label gssoc'23.

![Screenshot (793)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/6312a1ec-c8b5-4ef0-951a-45b8acd41782)
![Screenshot (794)](https://github.com/Spyware007/Animating-Buttons/assets/101655716/067d52d7-6f18-4c9d-83c2-cfed518852dd)

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
