### ISSUE TITLE
Add to cart animated button

### ISSUE THREAD

**Issue by shraddha761** [Spyware007/Animating-Buttons#876]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

![Screenshot 2023-05-31 232413](https://github.com/Spyware007/Animating-Buttons/assets/106100728/cea29a70-b852-4de6-9235-f6e44fdf0f76)
![Screenshot 2023-05-31 232418](https://github.com/Spyware007/Animating-Buttons/assets/106100728/da3bda77-727c-4411-8b65-e358abb60734)

This button is fully animated with the help of js.
Assign this issue to me under GSSOC'23

**Comment by Spyware007** [comment]
# Please check #1346
