### ISSUE TITLE
New button

### ISSUE THREAD

**Issue by shraddha761** [Spyware007/Animating-Buttons#878]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

![Screenshot 2023-05-31 232544](https://github.com/Spyware007/Animating-Buttons/assets/106100728/8621713d-5719-4fde-bfcf-18243d9464d4)
![Screenshot 2023-05-31 232549](https://github.com/Spyware007/Animating-Buttons/assets/106100728/09ee7314-d31c-4767-b1d3-f2366e0f88bc)

this button is fully animated with help of JavaScript 
Assign this issue to me under GSSOC'23

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
