### ISSUE TITLE
fix the position of the scroll to top button

### ISSUE THREAD

**Issue by SakshiRawat13** [Spyware007/Animating-Buttons#905]
I want to fix the position of the scroll to top button.
This is what it looks like currently:
![image](https://github.com/Spyware007/Animating-Buttons/assets/97942987/faff5f75-faf6-4881-be6d-3093670cf1a7)

**This is a(n):**

- [x] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**

This is what it should look like:
![image](https://github.com/Spyware007/Animating-Buttons/assets/97942987/a4aedfcd-f141-4089-a1e0-f0aeae246a50)

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
