### ISSUE TITLE
Additions in Issue Template

### ISSUE THREAD

**Issue by Anshika-Jain02** [Spyware007/Animating-Buttons#912]
## Description:

*I noticed that the repository does not have an appropriate issue template.*

*Issue Template: I want to add  some more points to your issue template like styling changes, documentation, bugs, feature request etc*

Please assign this issue to me under Gssoc'23 @Spyware007

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
