### ISSUE TITLE
Adding New Animated Button

### ISSUE THREAD

**Issue by Harshu467** [Spyware007/Animating-Buttons#916]
**This is a(n):**

- [x ] Proposal to the Repository

**Details:**

New Animated button

**Comment by Harshu467** [comment]
Assign it to me

**Comment by Harshu467** [comment]
@PoorviShetty I have added please check and merge

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
