### ISSUE TITLE
Implementing an Animated Delete Button for Enhanced User Experience

### ISSUE THREAD

**Issue by Nishusk** [Spyware007/Animating-Buttons#919]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [x] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
**Description**
As part of GSSOC (GirlScript Summer of Code), I aim to implement a delete button functionality that provides a visually appealing and interactive experience for users. When the delete button is clicked, it will remove all occurrences of the word "delete" and visually animate them into a dustbin icon.

### Problem Statement
Currently, our application lacks a user-friendly way to remove instances of the word "delete." Users often have to manually edit the text or use alternative workarounds, which can be time-consuming and tedious.

### Proposed Solution
Introducing a delete button that streamlines the process of removing the word "delete" from the text. Clicking the button will automatically replace all instances of the word with a dustbin icon, creating a fun and interactive visual representation of the deletion action.

### Requirements
To address this issue, the following requirements need to be fulfilled:
- Implement a delete button with an appropriate visual representation, such as a trash can or dustbin icon.
- Detect all occurrences of the word "delete" in the text and replace them with the chosen visual representation.
- Apply smooth and visually pleasing animation effects to transition the word "delete" into the dustbin icon.
- Ensure that the delete functionality is accessible and works reliably across different browsers and devices.

Please assign this issue to me under GSSOC'23 (GirlScript Summer of Code).
![WhatsApp Image 2023-06-03 at 4 06 22 PM](https://github.com/Spyware007/Animating-Buttons/assets/101655716/0124a2a3-f5dd-4c6c-b55b-ae5139b1e624)

**Comment by Spyware007** [comment]
# Please check #1346
