### ISSUE TITLE
Navbar components not aligned!

### ISSUE THREAD

**Issue by ydvmudit07** [Spyware007/Animating-Buttons#920]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [x] Any Error
- [ ] Proposal to the Repository
- [ ] Documentation / README.md changes

**Details:**
The dark mode button is not aligned with the other components present on the navbar.

![image](https://github.com/Spyware007/Animating-Buttons/assets/120110061/ab134e96-5989-434b-8d0d-e8791d47dd75)

Kindly assign me this under GSSoC 23'. I have the knowledge and experience of required tech stack.

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by ydvmudit07** [comment]
Since you guys are going with the new UI, I guess the PR made for this issue won't be merged, right?

> # Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
