### ISSUE TITLE
docs: correct readme with proper format

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Spyware007/Animating-Buttons#925]
**This is a(n):**

- [ ] Update to an existing Animated Button
- [ ] Any Error
- [ ] Proposal to the Repository
- [x] Documentation / README.md changes

**Details:**

![image](https://github.com/Spyware007/Animating-Buttons/assets/74038190/7443bc55-133f-46e5-abdb-0099a66684e8)

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
