### ISSUE TITLE
Adding new button

### ISSUE THREAD

**Issue by shruuti321** [Spyware007/Animating-Buttons#931]
Hey I would like to add a new button to your project.
Kindly assign me this issue under GSSOC'23.

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
