### ISSUE TITLE
Add a review section .

### ISSUE THREAD

**Issue by Anamika-Ratna** [Spyware007/Animating-Buttons#936]
### Details

Hello , I would like to add a review section where some of the top reviews would be displayed .
So for this review section I would ask a favor from you . Kindly circulate the google form so that I can recieve the reviews . Some of the top reviews will be displayed on the website .
Google form:  https://forms.gle/YuR1BprkxzqWsawQ9

Therefore I request you to kindly assign me this task under the tag GSSoC- 23

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346

**Comment by Spyware007** [comment]
Sorry for the inconvinience, but we are closing all the issues! Please open a new issue if you want to contribute anything. Also now you can create a new button from the website itself! You will get points for those too! I will add the instructions on how to create a new button soon and create an empty pr for the same to get points!
