### ISSUE TITLE
Add one more button 

### ISSUE THREAD

**Issue by BhartiNagpure** [Spyware007/Animating-Buttons#937]
### Details

I would like to add one more button into this project to have the user more variety in the button and they can use it as they like ,
therefore I want to assigned me this task under GSSoC,23 tag.

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by Spyware007** [comment]
# Please check #1346
