### ISSUE TITLE
Remove duplicate animation buttons. 😅

### ISSUE THREAD

**Issue by Spyware007** [Spyware007/Animating-Buttons#99]
Remove the buttons which are repeated or having same animation.

**Comment by SainathPoojary** [comment]
hey @Spyware007, I want to work on this. Please assign it to me.

**Comment by LucianeFernandesRoque** [comment]
Hi, I want to work this issue

**Comment by Spyware007** [comment]
@SainathPoojary @LucianeFernandesRoque 
If you found any duplicate buttons remove all the files associated with it.

**Comment by LucianeFernandesRoque** [comment]
Hi, @Spyware007  i open PR 'https://github.com/Spyware007/Animating-Buttons/pull/114'
