### ISSUE TITLE
[Add] Someone added  a button outside the Buttons folder

### ISSUE THREAD

**Issue by sumitkr2000** [Spyware007/Animating-Buttons#997]
### Details

Hey @Spyware007 As I can see an unwanted button folder was added by abdulkhalid outside the button folder. I can remove the folder so that there will be not any future bugs. Please assign me this issue. Thank you!

### Screenshots

![Screenshot 2023-06-05 143030](https://github.com/Spyware007/Animating-Buttons/assets/100675296/0c06164f-ee13-4163-96ce-72b95a877c50)

### Type of Contribution

- [ ] Update to an existing Animated Button
- [ ] Adding a new Button
- [ ] Resolving a bug
- [X] Proposal to the Repository
- [ ] Changes related to documentation or README.md
- [ ] Other Changes

### Checklist

- [X] I have checked the existing [issues](https://github.com/Spyware007/Animating-Buttons/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Spyware007/Animating-Buttons/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by 0xabdulkhalid** [comment]
Bro @sumitkr2000, I already fixed it on my PR #986.

And please don't remove that it's not unwanted, you can just move it into the `Buttons` folder

**Comment by sumitkr2000** [comment]
@0xabdulkhalid Bro one is already present in the buttons folder. And another one is outside of it. Is it of any use?
